---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hufeng.
--- DateTime: 2023/4/26 下午7:34
---

local E = require 'ejoysdk_lua.ejoysdk'
local CONSTANTS = require 'ejoysdk_lua.ejoysdk_constants'
local JSON = require "ejoysdk_lua.ejoysdk_json"
local E_UTILS = require 'ejoysdk_lua.ejoysdk_utils'
local COMPAT = require 'ejoysdk_lua.compat.ejoysdk_compat'
local BitUtil = COMPAT.bitutil
local string_unpack = COMPAT.string.unpack


local M = {}
local TAG = 'http_security'


function M.update_sign_headers_ifneeded(method, url, headers, body, content_type)
    local fill_moment_token
    local fill_ejoy_token
    if headers then
        for k, v in pairs(headers) do
            if type(k) == 'string' then
                local lwk = k and k:lower()
                if lwk == 'moment-token' then
                    fill_moment_token = v
                elseif lwk == 'ejoy-token' then
                    fill_ejoy_token = v
                end
            end
        end

        if fill_moment_token then
            -- mtoken加签
            local EJ_SIGN = require "ejoysdk_lua.libs.signature"
            local url_info = E.HTTP.parse(url)
            if url_info then
                EJ_SIGN.general_authorization(method, url_info.path or '', url_info.query_ori_str or '', headers, body, content_type, fill_moment_token, EJ_SIGN.SIGN.MOMENT_TOKEN)
            end
        end

        if fill_ejoy_token then
            -- ejoytoken加签
            local EJ_SIGN = require "ejoysdk_lua.libs.signature"
            local url_info = E.HTTP.parse(url)
            if url_info then
                EJ_SIGN.general_authorization(method, url_info.path or '', url_info.query_ori_str or '', headers, body, content_type, fill_ejoy_token, EJ_SIGN.SIGN.EJOY_TOKEN)
            end
        end
    end
    return headers, fill_moment_token, fill_ejoy_token
end




function M.sign_headers_for_prevent_replay(method, url, headers, body)
    if headers then
        local url_info = E.HTTP.parse(url)
        if url_info then
            local EJ_SIGN = require "ejoysdk_lua.libs.signature"
            return EJ_SIGN.general_prevent_replay_request(method, url_info.query_ori_str or '', headers, body)
        end
    end

    E.LOG.debug(TAG, 'headers is nil, something wrong')
    return nil
end


function M.verify_response_for_prevent_modify(request_headers, url, response_headers, body, status)
    local stat = require 'ejoysdk_lua.ejoysdk_stat'
    local stat_action = 'http_verify_response_fail'
    local header_length = E_UTILS.tablelength(response_headers or {})
    if header_length > 0 then
        local stat_params = {response_headers = response_headers, url = url, request_headers=request_headers, response_body=body, status=status}
        local request_random_num = request_headers['ag-nonce']
        local response_random_value = response_headers['ag-nonce']
        if not request_random_num or not response_random_value then
            stat.stat_action(stat_action, 'request ag-nonce or response ag-nonce is nil, or two number is nil', false, stat_params)
            return false
        end

        if tonumber(request_random_num) ~= tonumber(response_random_value) then
            E.LOG.debug(TAG, 'request ag-nonce not equal response ag-nonce!!!!')

            --随机数跟request不匹配，说明response有问题
            stat.stat_action(stat_action, 'request ag-nonce not equal response ag-nonce', false, stat_params)
            return false
        end

        local sign_value_str = response_headers['platform-resp-signature']
        if not sign_value_str then
            stat.stat_action(stat_action, 'response header platform-resp-signature no value', false, stat_params)
            return false
        end

        if type(sign_value_str)~='string' or string.len(sign_value_str) <= 0 then
            stat.stat_action(stat_action, 'response header platform-resp-signature no string value or is empty string', false, stat_params)
            return false
        end

        local _,index_end = string.find(sign_value_str, 'signature:')

        if not index_end or tonumber(index_end) < 1 or index_end > string.len(sign_value_str) then
            stat.stat_action(stat_action, 'response header platform-resp-signature value format wrong', false, stat_params)
            return false
        end

        local signature_value = string.sub(sign_value_str, index_end+1) -- 提取签名

        local EJ_SIGN = require "ejoysdk_lua.libs.signature"
        local signature_result = EJ_SIGN.general_prevent_modify_response(response_headers, body)
        if signature_value ~= signature_result then
            stat_params.signature_result = signature_result
            stat.stat_action(stat_action, 'response body signature not equal', false, stat_params)
            return false
        end

        return true
    else

        -- response header 为空时，如果是PC的旧版本，要让其校验通过
        if E.Sysinfo.os() == 'windows' then
            local ejoysdk_version = E.get_sdk_version_name('EJOYSDK')
            local VER_CHECK = require 'ejoysdk_lua.ejoysdk_version_check'
            if VER_CHECK.compare_versions(ejoysdk_version, "2.4.4") < 0 then
                return true
            end
        end
    end

    local stat_params = {response_headers = response_headers, url = url, request_headers=request_headers, response_body=body}
    stat.stat_action(stat_action, 'response header is empty', false, stat_params)
    E.LOG.debug(TAG, 'headers is nil or empty, something wrong')
    return false
end


function M.decrypt_body(body, mtoken)
    local de_body
    -- 解密算法 https://yuque.antfin.com/ejoy-platform/ejoy-platform/mhpumw
    -- 密文：512bit + 8bit（version) + 8bit(key type) + 原始body bit
    -- 第一个byte random_bit 无用字符
    -- 第二个byte version，需要or random的 [8,16,24,32,40,48,56,64]
    -- 第三个key type，需要or random的 [72,80...136]
    --[[
    -- version 暂时不需要用到
    local version_bit = string_unpack('I1', body:sub(2,2))
    local version_bit_all = 0
    for i = 1, 8 do
        -- 这里加3是从第四个字节开始取高位，逐步右移动相加，最终和version xor
        local version_bit_s = BitUtil.rshift(BitUtil.band(string_unpack('I1', body:sub(i+3,i+3)), 128), i-1)
        version_bit_all = version_bit_all + version_bit_s
    end

    version_bit = BitUtil.bxor(version_bit, version_bit_all)
    -- E.LOG.debug("=================>version_bit:" .. tostring(version_bit))

    ]]
    local keytype_bit = string_unpack('I1', body:sub(3,3)) -- [72,80...136]
    local keytype_bit_all = 0
    for i = 1, 8 do
        -- 这里加11是从第12个字节开始取高位，逐步右移动相加，最终和keytype xor
        local keytype_bit_s = BitUtil.rshift(BitUtil.band(string_unpack('I1', body:sub(i+11,i+11)), 128), i-1)
        keytype_bit_all = keytype_bit_all + keytype_bit_s
    end

    keytype_bit = BitUtil.bxor(keytype_bit, keytype_bit_all)

    local sign_key
    local ramdom_key = body:sub(7,38)
    local EJ_SIGN = require "ejoysdk_lua.libs.signature"

    -- E.LOG.debug(TAG, "dencrypt:=>body:".. _ejoysdk_crypt.base64encode(body))
    -- E.LOG.debug(TAG, "dencrypt:=>keytype_bit_all:" .. tostring(keytype_bit_all))
    -- E.LOG.debug(TAG, "dencrypt:=>keytype_bit:" .. tostring(keytype_bit))
    -- E.LOG.debug(TAG ,"dencrypt:=>mtoken:" .. tostring(mtoken))

    -- 0代表moment-token 、1代表ejoy-token
    if tonumber(keytype_bit) == 0 then
        sign_key = EJ_SIGN.get_secret(mtoken)
    elseif tonumber(keytype_bit) == 1 then
        sign_key = EJ_SIGN.ejoy_sign_secret
    end

    if sign_key and ramdom_key then
        local final_key = _ejoysdk_crypt.sha1(sign_key .. ramdom_key)
        local rc4_key = _ejoysdk_crypt.rc4_key(final_key)
         E.LOG.debug(TAG,"dencrypt:=>sign_key:" .. tostring(sign_key))
        -- E.LOG.debug(TAG,"dencrypt:=>ramdom_key:" .. _ejoysdk_crypt.base64encode(ramdom_key))
        -- E.LOG.debug(TAG,"dencrypt:=>real_key:" .. _ejoysdk_crypt.base64encode(final_key))

        -- body
        local body_bit = body:sub(67)
        if body_bit then
            de_body = _ejoysdk_crypt.rc4_decrypt(body_bit, rc4_key)
            if de_body == nil then
                E.LOG.debug(TAG, "dencrypt: body is nil")
            end
            -- E.LOG.debug(TAG,"dencrypt:=>body:" .. de_body)
        else
            E.LOG.debug(TAG, "dencrypt: body_bit is nil")
        end
    else
        E.LOG.debug(TAG, "dencrypt: key is nil")
    end
    return de_body
end

function M.decode_by_content_type(params, info, body, url, mtoken)
    local acceptable = params.acceptable
    local headers = info.headers
    local content_type = headers and headers['Content-Type']
    local is_encrypt = 0
    -- 因为旧版本windows拿不到header，需要特殊处理
    local length = E_UTILS.tablelength(headers or {})
    if _ejoysdk.os() == "windows" and acceptable == E.HTTP.CT_JSON and length == 0 then
        if body and #body >= 1 then
            local firstByte = body:sub(1,1)
            local magic_num = string_unpack('I1', firstByte)
            if tonumber(magic_num) == 1 then
                is_encrypt = 1
            end
        end
    else
        local ejoy_rpc_info_str = headers and headers['ejoy-rpc-info']
        if ejoy_rpc_info_str == nil then
            ejoy_rpc_info_str = headers and headers['Ejoy-Rpc-Info']
        end
        if ejoy_rpc_info_str then
            -- 无论是不是返回raw_body，都需要解一下body
            -- ejoy-rpc-info=application/json; encrypt=true
            local si, ei = string.find(ejoy_rpc_info_str, 'encrypt%s-=%s-true')
            if si then -- 开启了加密
                is_encrypt = 1
                local encrypt_str = ejoy_rpc_info_str:sub(si, ei)
                local _, _, ori_content_type = string.find(ejoy_rpc_info_str, '^(.*);%s-' .. tostring(encrypt_str))
                content_type = ori_content_type
                -- E.LOG.debug(TAG, "dencrypt: content_type ".. tostring(content_type))
            end
        end
    end

    if is_encrypt == 1 then
        local de_ok, result = pcall(M.decrypt_body, body, mtoken)
        if de_ok then
            body = result
        else
            body = nil
            E.LOG.debug(TAG, "dencrypt: body fail")
        end
    end

    -- 需要解析body, 否则返回原始数据
    if not params.raw_body then
        local stat = require 'ejoysdk_lua.ejoysdk_stat'
        local stat_action = 'http_decode_fail'
        local stat_params = {params = params, info = info, url = url, encrypt = is_encrypt} -- params: SDK 请求参数，info: SDK HTTP 返回结果

        if info == nil then
            stat.stat_action(stat_action, 'empty_info', false, stat_params)
            return body
        end

        local function is_normal_request() -- 正常请求返回，上报异常解析
            return info.status == 200 and params.file == nil
        end

        if is_normal_request() then -- 解析结果需要关心
            if body == nil then
                stat.stat_action(stat_action, 'nil_body', false, stat_params)
                return body
            elseif body == '' then
                stat.stat_action(stat_action, 'empty_body', false, stat_params)
                return body
            end
        end

        if content_type == nil then
            content_type = acceptable
        else
            content_type = content_type:match('^[^;]+')
        end

        if content_type ~= acceptable and acceptable ~= nil then
            stat.stat_action(stat_action, 'content_type_diff_acceptable', false, stat_params)
            return nil
        end

        if content_type == E.HTTP.CT_JSON then
            local succ, json = pcall(JSON.decode, body)
            if succ then
                return json
            elseif is_normal_request() then
                _ejoysdk.log('content_type error')
                local error_msg = json
                if error_msg and type(error_msg) == 'string' then
                    stat_params.error_msg = _ejoysdk_crypt.base64encode(error_msg:sub(1, 500))
                end
                stat.stat_action(stat_action, 'content_type_error', false, stat_params)
                return nil
            end
        end
    end

    return body
end

function M.http_get_adapter_security(url, params, cb)

    params = params or {}
    params.headers = E.HTTP.check_and_update_headers(params.headers)

    -- 加签
    local _, mtoken = M.update_sign_headers_ifneeded('get', url, params.headers, '', '')


    local adapter_get_cb = function(info)
        local body = info.body

        -- windows如果不是200就不解密，这个是2019年刘金加的，具体原因不明，这次windows端也直接去掉对status的判断，所有status都走解密流程，三端对齐
        -- 解密和 raw_body 的逻辑在内部判断
        body = M.decode_by_content_type(params, info, body, url, mtoken)
        if not body and info.status == 200 then
            body = {
                code = CONSTANTS.EJOYSDK_ERROR_CODES.HTTP_REQUEST_BODY_NIL,
                message = 'resp body is nil'
            }
        end


        info.body = body
        if cb then
            cb(info)
        end
    end


    return E.HTTP.process_get(url, params, adapter_get_cb)
end

-- 这个适配层存在的前提是，游戏项目组不能直接调用我们的E.HTTP.process_post函数，而必须是调用我们包装过的函数比如E.HTTP.post，否则就可能会漏
function M.http_post_adapter_security(url, params, content_type, body, cb)
    -- 在这里做一些加签的操作，把结果塞到header里去
    params = params or {}

    params.headers = E.HTTP.check_and_update_headers(params.headers)
    if params.headers['Content-Type'] then
        assert(params.headers['Content-Type'] == content_type)
    end

    params.headers['Content-Type'] = content_type
    -- 不懂为啥安卓会在params这里放一个content-type
    params['Content-Type'] = content_type

    body = E.HTTP.smart_content(body, content_type)

    -- 防重放的加签开关
    if params.enable_sign_headers_for_request then
        -- 开始防重放加签，内部给headers添加几个签名字段，会有ag-开头的三个字段，其中ag-nonce是单独新增的，会影响到下方moment-token的加签算法，所以这个加签要在moment-token加签的前面
        M.sign_headers_for_prevent_replay('post', url, params.headers, body)
    end
    -- 目前moment-token的加签算法对header里所有ag-开头的key都参与计算，并且会先小写再参与计算，服务器也一样
    -- 上面的加签算法跟moment-token的加签算法使用同样的函数进行复用

    -- moment-token和ejoy-token加签
    local _, mtoken = M.update_sign_headers_ifneeded('post', url, params.headers, body, content_type)



    local adapter_cb = function(info)
        --这里对info做一些检查操作，比如对body做验签然后解密的流程
        local resp_body = info.body
        local status = info.status

        local status_need_verify_body = false
        -- 正常的HTTP状态码才去对body进行验签
        if status ~= nil and type(status) == 'number' and (status >= 200 and status < 300 or status == 0) then
            status_need_verify_body = true
        end
        if params.enable_sign_headers_for_response and status_need_verify_body  then
            -- 开始防篡改验签，入参需要request的随机数
            local signature_right = M.verify_response_for_prevent_modify(params.headers, url, info.headers, resp_body, status)
            if not signature_right then
                -- 验签失败
                info.body = {
                    code = CONSTANTS.EJOYSDK_ERROR_CODES.HTTP_RESPONSE_VERIFY_FAIL,
                    message = 'resp body is verify failed'
                }

                cb(info)
                return
            end
        end

        -- 对body判断下是否要解密，是否raw_body的逻辑在内部判断
        resp_body = M.decode_by_content_type(params, info, resp_body, url, mtoken)


        if not resp_body and status == 200 then
            resp_body = {
                code = CONSTANTS.EJOYSDK_ERROR_CODES.HTTP_REQUEST_BODY_NIL,
                message = 'resp body is nil'
            }
        end

        info.body = resp_body
        if cb then
            cb(info)
        end
    end


    return E.HTTP.process_post(url, params, content_type, body, adapter_cb)
end





return M