---
--- Generated by pangang(https://github.com/EmmyLua)
--- Created by ali.
--- DateTime: 2/15/23 6:14 PM
---

local E = require "ejoysdk_lua.ejoysdk"
local EC = require "ejoysdk_lua.ejoysdk_constants"

local TAG = "ej_calendar"

local M = {}

--[[
android only support alert and default, so we only use alert here,
https://developer.android.com/reference/kotlin/android/provider/CalendarContract.RemindersColumns.html#METHOD:kotlin.String
--]]
M.REMINDER_METHODS = {
    METHOD_ALERT = "alert"
}

-- 保证同样的权限请求不重复处理
local permissions_request_listeners_readonly = {}
local permissions_request_listeners_readwrite = {}

function M.is_support_calendar()
    -- check native support calendar
    return E.is_support_function(E.NATIVE_SUPPORT_FUNCTION_NAMES.ADD_CARLENDAR_EVENT)
end

local function is_support_no_permission_operation()
    return E.Sysinfo.os() == "android"
end

local function get_read_write_permission_options()
    -- check permission
    local android_calendar_permissions = {
        ["android.permission.WRITE_CALENDAR"] = {},
        ["android.permission.READ_CALENDAR"] = {}
    }

    local permissions = android_calendar_permissions
    -- use v3, show rationale dialog
    local options = {
        ['permissions'] = permissions
    }

    return options
end

local function get_read_permission_options()
    -- check permission
    local android_calendar_permissions = {
        ["android.permission.READ_CALENDAR"] = {}
    }

    local permissions = android_calendar_permissions
    -- use v3, show rationale dialog
    local options = {
        ['permissions'] = permissions
    }

    return options
end

local function check_calendar_read_write_permission(is_readonly, cb)
    if E.Sysinfo.os() ~= "android" then
        E.LOG.debug(TAG, "check_calendar_permission skip, just return true")
        cb(true)
        return
    end

    local options
    local requesting_listeners
    if is_readonly then
        requesting_listeners = permissions_request_listeners_readonly
        options = get_read_permission_options()
    else
        requesting_listeners = permissions_request_listeners_readwrite
        options = get_read_write_permission_options()
    end

    table.insert(requesting_listeners, cb)
    if requesting_listeners and #requesting_listeners > 1 then
        E.LOG.debug(TAG, "already has permission request, now just add listener and wait")
        return
    end

    E.Permission.check_permission_v3(options,function(succ, is_open_settings)
        -- 点击按钮回调
        if succ then
            -- 授权成功，可以继续调用接口
            E.LOG.debug(TAG, "calendar permission granted")
            for _, lis in ipairs(requesting_listeners) do
                lis(true)
            end
        else
            -- 授权失败
            E.LOG.debug(TAG, "calendar permission not granted")
            local err_code = EC.CALENDAR_ERROR_CODES.CODE_CALENDAR_PERMISSION_REJECT
            if is_open_settings then
                err_code = EC.CALENDAR_ERROR_CODES.CODE_PERMISSION_REJECT_OPEN_SETTINGS
            end

            for _, lis in ipairs(requesting_listeners) do
                lis(false, err_code, "calendar permission reject")
            end
        end

        -- reset listeners
        requesting_listeners = {}
    end)
end

local function check_before_calendar_operation(is_readonly, cb)
    if not M.is_support_calendar() then
        -- callback not support
        cb(false, EC.CALENDAR_ERROR_CODES.CODE_NOT_SUPPORT, "not support calendar")
        return
    end

    -- begin check permission
    check_calendar_read_write_permission(is_readonly, function(succ, ...)
        cb(succ, ...)
    end)
end

--[[
添加日历事件
@param params, table, 包含字段信息：
    @param event_info table，事件信息， 包含字段：
        @param start_time_mills number, 事件开始时间，单位毫秒
        @param end_time_mills number, 事件结束时间，单位毫秒
        @param title string, 事件标题
        @param description string，事件描述
        @param event_location string, 时间发生地点
    @param reminder_info table, 提醒信息，包含字段：
        @param minutes number, 事件发生前的分钟数，应在达到该时间时发出提醒。默认为0
        @param method_name string，提醒方法，可选，默认为 alert, 见 {@link M.REMINDER_METHODS}
@return
--]]
function M.add_event(params, cb)
    if not params or not params.event_info then
        E.LOG.warn(TAG, "add_event failed, params invalid")
        cb(false, EC.CALENDAR_ERROR_CODES.CODE_EVENT_PARAM_INVALID, "params or event is nil")
        return
    end

    if not params.reminder_info or next(params.reminder_info) == nil then
        params.reminder_info = {
            minutes = 0,
            method_name = M.REMINDER_METHODS.METHOD_ALERT
        }
    end

    check_before_calendar_operation(false, function(succ, ...)
        if succ then
            E.LOG.debug(TAG, "add_event begin")
            E.Calendar.add_event(params, function(_succ, ...)
                if cb then
                    cb(_succ, ...)
                end
            end)
        else
            local code, msg = ...
            if is_support_no_permission_operation() and code ~= EC.CALENDAR_ERROR_CODES.CODE_PERMISSION_REJECT_OPEN_SETTINGS then
                E.LOG.debug(TAG, "add_event support no permission operation")
                E.Calendar.add_event(params, cb)
            else
                E.LOG.warn(TAG, "add_event no permission return false, code:" .. tostring(code) .. ", msg:" .. tostring(msg))
                if cb then
                    cb(false, ...)
                end
            end
        end
    end)
end

--[[
删除日历事件
@param event_info table，事件信息， 同{@link #add_event}的 event_info字段，包含：
        @param start_time_mills number, 事件开始时间，单位毫秒
        @param end_time_mills number, 事件结束时间，单位毫秒
        @param title string, 事件标题
        @param description string，事件描述
        @param event_location string, 时间发生地点
@return
--]]
function M.delete_event(event_info, cb)
    if not event_info or next(event_info) == nil then
        E.LOG.warn(TAG, "delete_event failed, event_info invalid")
        cb(false, EC.CALENDAR_ERROR_CODES.CODE_EVENT_PARAM_INVALID, "params or event is nil")
        return
    end

    check_before_calendar_operation(false, function(succ, ...)
        if succ then
            E.LOG.debug(TAG, "delete_event begin")
            E.Calendar.delete_event(event_info, cb)
        else
            E.LOG.debug(TAG, "delete_event no permission return false")
            if cb then
                cb(false, ...)
            end
        end
    end)
end

--[[
更新日历事件
@param old_event_info table，事件信息。可选，如果不传，则逻辑同add_event
同{@link #add_event}的 event_info字段，包含：
        @param start_time_mills number, 事件开始时间，单位毫秒
        @param end_time_mills number, 事件结束时间，单位毫秒
        @param title string, 事件标题
        @param description string，事件描述
        @param event_location string, 时间发生地点
@params new_calendar_info, 日历信息，必填，如果不传则该接口返回失败（{@link EC.CALENDAR_ERROR_CODES.CODE_EVENT_PARAM_INVALID}）。
包含字段同{@link #add_event} 的 params

@return
--]]
function M.update_event(_old_event_info, _new_calendar_info, cb)
    if not _new_calendar_info or next(_new_calendar_info) == nil then
        E.LOG.warn(TAG, "update_event failed, _new_calendar_info invalid")
        cb(false, EC.CALENDAR_ERROR_CODES.CODE_EVENT_PARAM_INVALID, "new calendar info is nil")
        return
    end

    local params = {
        old_event_info = _old_event_info,
        new_calendar_info = _new_calendar_info
    }

    check_before_calendar_operation(false, function(succ, ...)
        if succ then
            E.LOG.debug(TAG, "update_event begin")
            E.Calendar.update_event(params, cb)
        else
            local code, msg = ...
            if is_support_no_permission_operation() and code ~= EC.CALENDAR_ERROR_CODES.CODE_PERMISSION_REJECT_OPEN_SETTINGS then
                E.LOG.debug(TAG, "add_event support no permission operation")
                E.Calendar.update_event(params, cb)
            else
                E.LOG.warn(TAG, "update_event no permission return false, code:" .. tostring(code) .. ", msg:" .. tostring(msg))
                if cb then
                    cb(false, ...)
                end
            end
        end
    end)
end

--[[
查询日历事件，目前只支持精确匹配事件，不支持批量查询事件。通过事件id，事件标题等信息获取日历的完整信息
@param event_info table，事件信息，必传
event_info字段，包含：
        @param start_time_mills number, 事件开始时间，单位毫秒
        @param end_time_mills number, 事件结束时间，单位毫秒
        @param title string, 事件标题
        @param event_id，事件id

@return 完整的日历信息数据结构, table, 字段信息如下：
    @param event_info table，事件信息， 包含字段：
        @param start_time_mills number, 事件开始时间，单位毫秒
        @param end_time_mills number, 事件结束时间，单位毫秒
        @param title string, 事件标题
        @param description string，事件描述
        @param event_location string, 时间发生地点
    @param reminder_info table, 提醒信息, 同 add_event的 params信息
--]]
function M.query_event(event_info, cb)
    if not event_info or next(event_info) == nil then
        E.LOG.warn(TAG, "query_event failed, event_info invalid")
        cb(false, EC.CALENDAR_ERROR_CODES.CODE_EVENT_PARAM_INVALID, "event_info is nil")
        return
    end

    check_before_calendar_operation(true, function(succ, ...)
        if succ then
            E.LOG.debug(TAG, "query_event begin")
            E.Calendar.query_event(event_info, cb)
        else
            E.LOG.warn(TAG, "query_event no permission return false")
            if cb then
                cb(false, ...)
            end
        end
    end)
end

--[[
查询日历事件 id，目前只支持精确匹配事件，不支持批量查询事件。通过事件标题等信息获取事件id
@param event_info table，事件信息。必传
event_info字段，包含：
        @param start_time_mills number, 事件开始时间，单位毫秒
        @param end_time_mills number, 事件结束时间，单位毫秒
        @param title string, 事件标题

@return @param event_id，string，事件id
--]]
function M.query_event_id(event_info, cb)
    if not event_info or next(event_info) == nil then
        E.LOG.warn(TAG, "query_event_id failed, event_info invalid")
        cb(false, EC.CALENDAR_ERROR_CODES.CODE_EVENT_PARAM_INVALID, "event_info is nil")
        return
    end

    check_before_calendar_operation(true,function(succ, ...)
        if succ then
            E.LOG.debug(TAG, "query_event_id begin")
            E.Calendar.query_event_id(event_info, cb)
        else
            E.LOG.warn(TAG, "query_event_id no permission return false")
            if cb then
                cb(false, ...)
            end
        end
    end)
end

--[[
查询日历事件是否存在，目前只支持精确匹配事件，不支持批量查询事件
@param event_info table，事件信息。必传
event_info字段，包含：
        @param start_time_mills number, 事件开始时间，单位毫秒
        @param end_time_mills number, 事件结束时间，单位毫秒
        @param title string, 事件标题

@return @param exists, true: 存在， false: 不存在
--]]
function M.is_event_exists(event_info, cb)
    M.query_event_id(event_info, function(ret)
        local succ = ret.succ
        if succ then
            local data = ret.data or {}
            local event_id = data.event_id
            local exists = event_id and event_id ~= "" and event_id ~= "0"
            if cb then
                cb(exists)
            end
        else
            if cb then
                cb(false)
            end
        end
    end)
end

return M