---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pangang.
--- DateTime: 2020/8/20 上午10:58
--- gangplank cdn config 管理
---
local E = require "ejoysdk_lua.ejoysdk"
local JSON = require 'ejoysdk_lua.ejoysdk_json'
local ET = require "ejoysdk_lua.ejoysdk_topic"
local CONSTANTS = require 'ejoysdk_lua.ejoysdk_constants'
local EM = require "ejoysdk_lua.ejoysdk_module"

local M = {}

M.CONFIG_KEY = {
    KEY_PLATFORM_DOMAIN = 'pf_domain',
    KEY_CHAT_CONFIG = 'pf_chat',
    KEY_HOST = 'host',
    KEY_CHAT_PORTS = 'ports', --聊天可选的端口列表
    KEY_AREA = 'area',
    KEY_URL_SPLICE_RULES = 'route-rule', -- 平台路由拼接规则
    KEY_RULE_APPEND_REGION = 'append_region', -- 是否拼接region, true - 需要拼接region, false - 不拼接region
    KEY_RULE_APPEND_SERVICE = 'service_rule', -- 0 - service拼接在二级域名，例如：p10082-{service}.ejoy.com
}

M.CONFIG_VAL = {
    -- 0 - service拼接在二级域名，例如：p10082-{service}.ejoy.com
    VAL_SERVICE_IN_DOMAIN = 0,
    -- 1 - service拼接在url path，例如：p10082-platform.ejoy.com/{service}
    VAL_SERVICE_IN_PATH = 1
}

local TAG = EM.MODULE.EJOYSDK_BASE_MODULE .. "gangplank_config"

local global_cdn_config = nil
local global_gangplank_config = nil
local current_publish_area = nil

-- 获取当前的发行地区。优先游戏设置，其次是包体的打包配置
local function init_current_publish_area()
    local publish_area = E.CONFIG.get_config(E.CONFIG.KEY.PUBLISH_AREA)
    if not publish_area or publish_area == '' then
        publish_area = E.get_meta_config(E.CONFIG.KEY.PUBLISH_AREA)
        E.LOG.debug(TAG, "ejoysdk_config没有设置publish_area，开始从meta_config读取")
        if publish_area then
            E.LOG.debug(TAG, "meta_config有publish_area，更新ejoysdk_config publish_area:"..publish_area)
            E.CONFIG.set_config(E.CONFIG.KEY.PUBLISH_AREA, publish_area)
        end
    end

    current_publish_area = publish_area
    E.LOG.debug(TAG, "init_current_publish_area: "..(current_publish_area or 'nil'))
end

local function check_gangplank_config_enabled()
    -- 如果国际同服，需要获取当前的gangplank地址
    local global_gangplank_enabled = E.CONFIG.get_config(E.CONFIG.KEY.GLOBAL_GANGPLANK_ENABLED)
    local multi_regions_enabled = E.CONFIG.get_config(E.CONFIG.KEY.MULTI_REGIONS_ENABLED)
    E.LOG.debug(TAG, 'init_gangplank_url_with_region, global_gangplank_enabled:' .. tostring(global_gangplank_enabled)
            .. ' ,multi_regions_enabled: ' .. tostring(multi_regions_enabled))
    return global_gangplank_enabled or multi_regions_enabled
end

function M.is_gangplank_config_enabled()
    local gp_cfg_enabled = check_gangplank_config_enabled()
    E.LOG.debug(TAG, "is_gangplank_config_enabled:" .. tostring(gp_cfg_enabled))
    return gp_cfg_enabled
end

function M.get_base_url_for_service(service)
    if service == nil then
        E.LOG.debug(TAG, 'get_base_url_for_service fail, service is nil')
        return nil
    end
    local product = E.CONFIG.get_config("product"):lower()
    local region = E.CONFIG.get_config("region")
    local splice_rules = E.CONFIG.get_splice_rules()
    local region_rule = splice_rules[E.CONFIG.RULE_KEY.RULE_REGION]
    if region and region_rule == E.CONFIG.URL_REGION_SPLICE_RULE.RULE_DEFAULT then
        region = '-' .. region:lower()
    else
        region = ''
    end
    local server_name = 'https://' .. product .. region .. '-' .. service .. M.server_domain_suffix()
    return server_name
end

function M.server_domain_suffix()
    local server_domain = E.CONFIG.get_config(E.CONFIG.KEY.SERVER_DOMAIN)
    if not server_domain or server_domain == '' then
        server_domain = E.get_meta_config(E.META_CONFIG_KEY.SERVER_DOMAIN)
        E.LOG.debug(TAG, "ejoysdk_config没有设置server_domain，开始从meta_config读取")
        if server_domain then
            E.LOG.debug(TAG, "meta_config有server_domain，更新ejoysdk_config server_domain:"..server_domain)
            E.CONFIG.set_config(E.CONFIG.KEY.SERVER_DOMAIN, server_domain)
        end
    end

    -- 补上域名前缀的.
    if server_domain and server_domain ~= '' then
        if not E.Utils.start_with(server_domain, '.') then
            E.LOG.warn(TAG, 'server_domain_suffix server_domain doesnt have dot prefix, add one')
            server_domain = '.' .. server_domain
        end
    else
        server_domain = E.CONFIG.DOMAIN_EJOY
    end

    return server_domain
end


local function gen_gangplank_config_url()
    local server_domain = M.server_domain_suffix()
    local product = E.CONFIG.get_config('product'):lower()
    local gangplank_config_url = 'https://global-config' .. server_domain .. '/' .. product .. '/gangplank-config'
    E.LOG.debug(TAG, "get config server_domain:"..(server_domain or 'nil')..', and final url:'..gangplank_config_url)

    return gangplank_config_url
end

-- 请求gangplank 全球节点列表
local function request_gangplank_config(cb)
    local gangplank_config_url = gen_gangplank_config_url()

    E.LOG.debug(TAG .. "request_gangplank_config > url:" .. gangplank_config_url)
    E.HTTP.get(gangplank_config_url, { trace = true , opentracing = { span_buz = 'init' } }, function(resp)
        E.LOG.debug(TAG .. "request_gangplank_config response >")
        E.log(resp)
        local status = resp.status
        local body = resp.body
        if status == 200 then
            E.LOG.debug(TAG, "request_gangplank_config resp:" .. body)
            local body_json = JSON.decode(body)
            E.log(body_json)
            global_cdn_config = body_json
            --cb(true, body['gangplank-config'])
            --local config_str = "{\"gangplank-config\": [{\"area\": \"CN\", \"region\": \"A\", \"default\": true}, {\"area\": \"HK\", \"region\": \"B\", \"default\": false}]}"
            if body_json and body_json['gangplank-config'] then
                E.LOG.debug(TAG, 'parse gangplank config body success!')
                cb(true, body_json['gangplank-config'])
            else
                E.LOG.error(TAG, 'parse gangplank config body failed!')
                cb(false, status, 'gangplank-config body parse failed')
            end
            ET.publish(ET.gangplank.GLOBAL_CDN_CONFIG_SUCC, body_json)
        else
            cb(false, status, body and body.message or '')
        end
    end)
end

-- 用于单元测试，请勿调用
function M.request_gangplank_config_for_unittest(cb)
    request_gangplank_config(cb)
end

-- 检查手机本地地区，优先是发行地区，如果为空则找手机本地的country，如果因为兼容问题导致country为空则默认为hk
-- ISO 3166 alpha-2国家代码，并遵照平台内约定统一转为小写
local function check_local_area()
    local local_area = current_publish_area
    if local_area and local_area ~= '' then
        E.LOG.debug(TAG, "check_config_region current_publish_area NOT nil, use it as local area:"..(local_area or 'nil'))
        return local_area
    end

    local country = E.CONFIG.get_config('district')
    local_area = country and country:lower()
    E.LOG.debug(TAG, "check_config_region current_publish_area IS nil, now check device country setting:"..(local_area or 'nil'))
    if local_area and local_area ~= '' then
        return local_area
    end

    local_area = CONSTANTS.GLOBAL_GANGPLANK_CONSTANTS.DEFAULT_GANGPLANK_REGION
    local message = 'could not find region, use default url:' .. local_area
    E.LOG.warn(TAG, 'init_gangplank_url_with_region, ' .. message)

    return local_area
end

local function check_region_for_local_area(local_area, gangplank_config_arr)
    local local_gangplank_region = nil
    local default_gangplank_region = nil
    for _, v in pairs(gangplank_config_arr) do
        --服务端的area字段映射玩家所在地区信息
        if v.area and v.area == local_area then
            local_gangplank_region = v.region
            E.LOG.debug(TAG, 'init_gangplank_url_with_region, finded local gangplank region:' .. (v.region or 'nil'))
            break
        end

        --默认gangplank 服务地区
        if v.default then
            E.LOG.debug(TAG, 'init_gangplank_url_with_region, find default gangplank region:' .. (v.region or 'nil'))
            default_gangplank_region = v.region
        end
    end

    if local_gangplank_region == nil and default_gangplank_region then
        local_gangplank_region = default_gangplank_region
        E.LOG.debug(TAG, 'init_gangplank_url_with_region, use default region:' .. default_gangplank_region)
    end

    if local_gangplank_region then
        E.LOG.debug(TAG, 'set local gangplank region:' .. local_gangplank_region)
        E.CONFIG.set_config(E.CONFIG.KEY.LOCAL_GANGPLANK_REGION, local_gangplank_region)
    end

    return local_gangplank_region
end

-- 游戏没有设置region，通过地区找对应region
local function check_config_region(gangplank_config_arr)
    --1. 获取本地地区值
    local local_area = check_local_area()

    --2. 找到并设置默认的本地gangplank 服务地区信息
    local local_gangplank_region = check_region_for_local_area(local_area, gangplank_config_arr)

    --3. 如果游戏没有设置region，则使用地区信息获取的region覆盖
    if local_gangplank_region and (not E.CONFIG.get_config(E.CONFIG.KEY.REGION)) then
        E.LOG.debug(TAG, 'region not set, use local gangplank region instead:' .. local_gangplank_region)
        E.CONFIG.set_config(E.CONFIG.KEY.REGION, local_gangplank_region)
    end

    -- 如果是全球同服，则需要检查 local_gangplank_region
    local global_gangplank_enabled = E.CONFIG.get_config(E.CONFIG.KEY.GLOBAL_GANGPLANK_ENABLED)
    if global_gangplank_enabled then
        E.LOG.debug(TAG, "global_gangplank_enabled is true, so need check local_gangplank_region")
        if local_gangplank_region then
            return true
        else
            local err_msg = 'has no default url for region:' .. local_area
            E.LOG.error(TAG, 'init_gangplank_url_with_region, ' .. err_msg)
            return false, CONSTANTS.GLOBAL_GANGPLANK_ERROR_CODE.GLOBAL_GANGPLANK_URL_INVALID, err_msg
        end
    else
        E.LOG.debug(TAG, "global_gangplank_enabled is false, so NO need check local_gangplank_region, and return true")
        return true
    end
end

local function check_web_domain_whitelist()
    local current_config = M.get_current_cdn_config()
    if current_config == nil then
        E.LOG.debug(TAG, "check_web_domain_whitelist, current_config is nil, so skip")
        return
    end

    local domain_whitelist = current_config.domain_whitelist
    if domain_whitelist and type(domain_whitelist) == 'table' then
        local WC = require "ejoysdk_lua.ejoysdk_web_config"
        for _, host in ipairs(domain_whitelist) do
            WC.add_injection_host(host)
        end
    end
end

local function check_platform_domain_rule_in_config()
    local current_config = M.get_current_cdn_config()
    if current_config == nil then
        E.LOG.debug(TAG, "check_init_platform_servers, current_config is nil, so skip set splice rule")
        return
    end

    local glocal_cdn_config = M.get_global_cdn_config()
    local rules_config = glocal_cdn_config[M.CONFIG_KEY.KEY_URL_SPLICE_RULES]
    local rules = {}

    E.LOG.debug(TAG, "begin check rule config >>")
    E.log(rules_config)

    -- read from config
    if rules_config then
        -- default need append region in url
        local need_append_region = rules_config[M.CONFIG_KEY.KEY_RULE_APPEND_REGION]
        if need_append_region then
            E.LOG.debug(TAG, "rules_config is NOT nil, need_append_region is true")
            rules[E.CONFIG.RULE_KEY.RULE_REGION] = E.CONFIG.URL_REGION_SPLICE_RULE.RULE_DEFAULT
        else
            E.LOG.debug(TAG, "rules_config is NOT nil, need_append_region is false")
            rules[E.CONFIG.RULE_KEY.RULE_REGION] = E.CONFIG.URL_REGION_SPLICE_RULE.RULE_NO_REGION
        end

        local service_rule = rules_config[M.CONFIG_KEY.KEY_RULE_APPEND_SERVICE] or M.CONFIG_VAL.VAL_SERVICE_IN_DOMAIN
        if service_rule == M.CONFIG_VAL.VAL_SERVICE_IN_DOMAIN then
            E.LOG.debug(TAG, "rules_config is NOT nil, service_rule is VAL_SERVICE_IN_DOMAIN")
            rules[E.CONFIG.RULE_KEY.RULE_SERVICE] = E.CONFIG.URL_SERVICE_SPLICE_RULE.RULE_DEFAULT
        else
            E.LOG.debug(TAG, "rules_config is NOT nil, service_rule is RULE_SERVICE_SPLICE_IN_PATH")
            rules[E.CONFIG.RULE_KEY.RULE_SERVICE] = E.CONFIG.URL_SERVICE_SPLICE_RULE.RULE_SERVICE_SPLICE_IN_PATH
        end
    else
        E.LOG.debug(TAG, "rules_config is nil, service_rule and region rule is default")
        rules[E.CONFIG.RULE_KEY.RULE_REGION] = E.CONFIG.URL_REGION_SPLICE_RULE.RULE_DEFAULT
        rules[E.CONFIG.RULE_KEY.RULE_SERVICE] = E.CONFIG.URL_SERVICE_SPLICE_RULE.RULE_DEFAULT
    end


    -- 1. 优先全域名替换
    local platform_domain = current_config[M.CONFIG_KEY.KEY_PLATFORM_DOMAIN]
    if platform_domain then
        E.LOG.debug(TAG, "check_init_platform_servers config has pf_domain, so we [UPDATE] domain and set rule to RULE_FULL_DOMAIN_SPLICE")
        -- 目前海外的cdnconfig 的 pf_domain 设置的平台域名是整个域名替换，所以这里设置为 RULE_FULL_DOMAIN_SPLICE
        rules[E.CONFIG.RULE_KEY.RULE_SERVICE] = E.CONFIG.URL_SERVICE_SPLICE_RULE.RULE_FULL_DOMAIN_SPLICE
        E.CONFIG.set_domain(platform_domain)
    else
        -- 2. 如果无全域名替换，则使用本地拼接方式
        E.LOG.debug(TAG, "check_init_platform_servers config NOT has pf_domain, so we [RESET] domain and set rule to default")

        local server_domain = M.server_domain_suffix()
        E.CONFIG.set_domain(server_domain)
    end

    --更新 url 拼接规则
    E.CONFIG.set_splice_rules(rules)

    -- 更新平台服务地址
    E.CONFIG.update_ejoysdk_service()
end

local function init_gangplank_config(cb)

    --优先使用sdkconfig和外部设置的server_domain
    local server_domain = M.server_domain_suffix()
    E.CONFIG.set_domain(server_domain)
    E.LOG.debug(TAG, 'init_gangplank_config, set server domain ' .. tostring(server_domain))
    E.CONFIG.update_ejoysdk_service()

    if not check_gangplank_config_enabled() then
        E.LOG.debug(TAG, 'init_gangplank_url_with_region, do not request gangplank from server and return success')
        cb(true)
        return
    end

    E.LOG.debug(TAG, 'init_gangplank_url_with_region, now begin check gangplank url')
    request_gangplank_config(function(succ, ...)
        if succ then
            -- 1. 获取全球的gangplank 配置列表
            local config_arr = ...
            if not config_arr then
                local err_msg = 'request_gangplank_config response config arr is empty'
                E.LOG.error(TAG, 'init_gangplank_url_with_region, err_msg:' .. err_msg)
                cb(false, CONSTANTS.GLOBAL_GANGPLANK_ERROR_CODE.GLOBAL_GANGPLANK_CONFIG_EMPTY, err_msg)
                return
            else
                E.LOG.debug(TAG, 'request_gangplank_config success >>')
                E.log(config_arr)
                global_gangplank_config = config_arr
            end

            local ret, code, msg = check_config_region(config_arr)

            -- 检查cdn config里面的平台域名和拼接规则
            check_platform_domain_rule_in_config()

            -- 检查、添加 global-config 下发的 webview 白名单
            check_web_domain_whitelist()

            cb(ret, code, msg)
        else
            local status, message = ...
            E.LOG.error(TAG, 'status:' .. (status or 'nil') .. ", msg:" .. (message or 'nil'))
            cb(false, status, message)
        end
    end)
end

-- 初始化config
function M.init_config(cb)
    -- 读取本地的publish area
    init_current_publish_area()

    -- 初始化gangplank config
    init_gangplank_config(function(succ, ...)
        cb(succ, ...)
    end)
end

function M.get_current_cdn_config()
    if not global_cdn_config then
        return nil
    end

    local gangplank_configs = M.get_global_gangplank_configs()
    if not gangplank_configs or #gangplank_configs == 0 then
        return nil
    end

    local region = E.CONFIG.get_config(E.CONFIG.KEY.REGION)
    local local_area = check_local_area()

    local select_region_gangplank_config = nil
    local select_area_gangplank_config = nil
    local default_gangplank_config = nil

    for _, gangplank_config in pairs(gangplank_configs) do
        if gangplank_config.region and region and gangplank_config.region:lower() == region:lower() then
            select_region_gangplank_config = gangplank_config
        end

        if gangplank_config.area and local_area and gangplank_config.area:lower() == local_area:lower() then
            select_area_gangplank_config = gangplank_config
        end

        if gangplank_config.default then
            default_gangplank_config = gangplank_config
        end
    end

    -- 当前的region对应的gangplank_config不是默认的，则返回当前的配置
    if select_region_gangplank_config and not select_region_gangplank_config.default then
        E.LOG.debug(TAG, "get_current_cdn_config result>> select_region_gangplank_config, region:"..(region or 'nil'))
        return select_region_gangplank_config
    elseif select_area_gangplank_config then
        E.LOG.debug(TAG, "get_current_cdn_config result>> select_area_gangplank_config, local_area:"..(local_area or 'nil'))
        return select_area_gangplank_config
    else
        E.LOG.debug(TAG, "get_current_cdn_config result>> default_gangplank_config, local_area:"..(local_area or 'nil')..", region:"..(region or 'nil'))
        return default_gangplank_config
    end
end

function M.get_current_chat_config()
    local cdn_config = M.get_current_cdn_config()
    if cdn_config == nil then
        E.LOG.warn(TAG, "get_current_chat_config failed, current cdn config is nil")
        return nil
    end

    return cdn_config[M.CONFIG_KEY.KEY_CHAT_CONFIG]
end

function M.get_global_cdn_config()
    return global_cdn_config
end

function M.get_global_gangplank_configs()
    return global_gangplank_config
end

function M.current_publish_area()
    return current_publish_area
end

local function check_item_result(check_result, check_item, expect_value, current_value)
    if expect_value == current_value then
        check_result[check_item] = {
            result = true,
            msg = "expect:"..tostring(expect_value)..", now:"..tostring(current_value)
        }
    else
        check_result[check_item] = {
            result = false,
            msg = "expect:"..tostring(expect_value)..", now:"..tostring(current_value)
        }
    end
end

function M.test_config(global_cdn_config_str, expect_result)
    -- reset region
    E.CONFIG.set_config(E.CONFIG.KEY.REGION, nil)
    E.CONFIG.set_config(E.CONFIG.KEY.LOCAL_GANGPLANK_REGION, nil)

    -- mock data
    local body_json = JSON.decode(global_cdn_config_str)
    global_cdn_config = body_json
    global_gangplank_config = body_json['gangplank-config']

    -- 读取本地的publish area
    init_current_publish_area()
    check_config_region(global_gangplank_config)
    check_platform_domain_rule_in_config()

    -- get result
    local region = E.CONFIG.get_config(E.CONFIG.KEY.REGION)
    local local_region = E.CONFIG.get_config(E.CONFIG.KEY.LOCAL_GANGPLANK_REGION)
    local local_area = check_local_area()
    local current_domain = E.CONFIG.get_domain()
    local current_url_rules = E.CONFIG.get_splice_rules()

    --check
    local result = {}
    check_item_result(result, 'region', expect_result.region, region)
    check_item_result(result, 'publish_area', expect_result.publish_area, current_publish_area)
    check_item_result(result, 'local_region', expect_result.local_region, local_region)
    check_item_result(result, 'local_area', expect_result.local_area, local_area)
    check_item_result(result, 'current_domain', expect_result.current_domain, current_domain)
    check_item_result(result, 'service_rule', expect_result.service_rule, current_url_rules[E.CONFIG.RULE_KEY.RULE_SERVICE])
    check_item_result(result, 'region_rule', expect_result.region_rule, current_url_rules[E.CONFIG.RULE_KEY.RULE_REGION])
    E.LOG.debug(TAG, "test_config result >>")
    E.log(result)
end

return M