---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ali.
--- DateTime: 3/1/22 3:53 PM
---
local STAT = require "ejoysdk_lua.ejoysdk_stat"
local UTILS = require "ejoysdk_lua.ejoysdk_utils"
local E = require "ejoysdk_lua.ejoysdk"

local M = {}
M.INNER_LOG_LEVEL = UTILS.INNER_LOG_LEVEL

local DOWNLOAD_ACTION = "ejoy_http_download"

local log_level = UTILS.INNER_LOG_LEVEL.DEBUG

function M.stat_download_state(download_state_obj, _retry_times, limit_speed)
    if not download_state_obj then
        return
    end

    --_ejoysdk.log("stat_download_state >> state:" .. tostring(download_state_obj.state) .. ", download_state_obj.percent:" .. tostring(download_state_obj.percent))
    if download_state_obj.state == "downloading" then
        if download_state_obj.percent >= 0 and download_state_obj.percent % 10 ~= 0 then
            return
        end
    end

    local params = {
        url = download_state_obj.url,
        state = download_state_obj.state,
        tag = download_state_obj.tag,
        code = download_state_obj.err_code,
        msg = download_state_obj.err_msg,
        size = download_state_obj.size,
        downloading_size = download_state_obj.recv_bytes or 0,
        duration = download_state_obj.duration,
        progress = download_state_obj.percent,
        retry_times = _retry_times,
        speed = download_state_obj.speed
    }

    STAT.stat_action(DOWNLOAD_ACTION, "download_state_changed", limit_speed, params)
end

function M.stat_multi_download_state(download_state_obj, model_name)
    if not download_state_obj then
        return
    end

    local percent = download_state_obj.percent or 0
    --_ejoysdk.log("stat_download_state >> state:" .. tostring(download_state_obj.state) .. ", download_state_obj.percent:" .. tostring(download_state_obj.percent) .. ", download_state_obj.duration:" .. tostring(download_state_obj.duration))
    local _downloading_size = download_state_obj.downloading_size or 0
    local _duration_sec = download_state_obj.duration or 0
    local _speed_kbps = 0
    if _downloading_size > 0 and _duration_sec > 0 then
        local size_kb = _downloading_size / 1024
        _speed_kbps = size_kb / _duration_sec
    end

    local params = {
        state = download_state_obj.state,
        tag = download_state_obj.tag,
        code = download_state_obj.err_code,
        msg = download_state_obj.err_msg,
        size = download_state_obj.total_size,
        downloading_size = download_state_obj.downloading_size,
        duration = download_state_obj.duration,
        progress = percent,
        speed = _speed_kbps,
        total_count = download_state_obj.total_count,
        finish_count = download_state_obj.finish_count,
        model_name = model_name
    }
    
    STAT.stat_action(DOWNLOAD_ACTION, "multi_download_state_changed", model_name, params)
end

function M.stat_action(action, action_type, result, params)
    local stat_params = params or {}
    STAT.stat_action(action, action_type, result, stat_params)
end

function M.stat_action_fail(action, action_type, ...)
    local params = {}
    local args = ...
    local args_type = type(args)
    if args_type == 'table' then
        params = args
    else
        local code, msg = ...
        params.code = code
        params.msg = msg
    end

    STAT.stat_action_fail(action, action_type, params)
end

function M.set_log_level(_log_level)
    log_level = _log_level
    if _log_level >= UTILS.INNER_LOG_LEVEL.WARN then
        UTILS.set_global_log_enable(false)
    else
        UTILS.set_global_log_enable(true)
    end
end

function M.is_log_allow_with_level(_log_level)
    return log_level <= _log_level
end

function M.log_debug(tag, msg)
    if log_level > UTILS.INNER_LOG_LEVEL.DEBUG then
        return
    end

    E.LOG.debug(tag, msg)
end

function M.log_warn(tag, msg)
    if log_level > UTILS.INNER_LOG_LEVEL.WARN then
        return
    end

    E.LOG.warn(tag, msg)
end

function M.stat_action_unimportant(action, action_type, result, params)
    STAT.stat_action(action, action_type, result, params)
end

return M