---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pangang.
--- DateTime: 2/16/22 3:45 PM
--- 详细状态、事件定义参考设计文档：https://yuque.antfin-inc.com/ejoy-platform/ejoy-platform/gwe6u1
---
local Class = require "ejoysdk_lua.ejoysdk_class"
local E = require "ejoysdk_lua.ejoysdk"
local EC = require "ejoysdk_lua.ejoysdk_constants"
local UTILS = require 'ejoysdk_lua.ejoysdk_utils'
local HRU = require "ejoysdk_lua.res.ejoy_http_res_utils"
local ET = require "ejoysdk_lua.ejoysdk_topic"
local DST = require "ejoysdk_lua.res.model.http_download_stat"
local utils = require "ejoysdk_lua.ejoysdk_utils"
-- 状态机使用描述：https://gitee.com/houjinxin/lua-state-machine/tree/master#usage
local FSM = UTILS.fsm
local M = Class:Inherit('EjoyHttpDownloadTask')

local TAG = "http_down_task"

M.DOWNLOAD_STATE = {
    -- 下载初始状态
    IDLE = "idle", -- 默认状态
    FAILED = "failed",
    -- 下载任务暂停状态，可以断点续传
    STOPPED = "stopped",
    -- 下载中状态
    DOWNLOADING = "downloading",
    -- 下载完成状态
    COMPLETE = "complete"
}

M.DOWNLOAD_CHECK_STATE = {
    COMPLETE_FILE_VALID = "complete_valid", --资源完整
    COMPLETE_FILE_INVALID = "complete_invalid", --下载完成的资源无效，下载组件会删除该文件重新下载

    DOWNLOADING_FILE_INVALID = "downloading_invalid", --下载中的资源无效，下载组件会删除该下载中的文件和重置对应断点续传信息，并重新下载
    DOWNLOADING_FILE_INCOMPLETE = "downloading_incomplete", --下载中
    DOWNLOADING_FILE_VALID = "downloading_valid", --文件处于下载中状态，但是文件检查完整，可以直接rename

    NOT_DOWNLOAD = "not_download", -- 文件未启动下载
    UNKNOWN = "unknown" -- 未知
}

M.INNER_LOG_LEVEL = {
    INFO = 0,
    DEBUG = 1,
    WARN = 2,
    ERROR = 3
}

--[[
    state obj key字段描述
    state：当前下载状态，参考：M.DOWNLOAD_STATE
    file_path: 文件下载路径
    size：文件总大小，单位字节
    recv_bytes：文件已经接收大小，单位字节
    err_code：错误码
    err_msg：错误信息
--]]
M.STATE_KEY = {
    STATE = "state",
    FILE_PATH = "file_path",
    SIZE = "size",
    RECV_BYTES = "recv_bytes",
    SPEED = "speed",
    ERR_CODE = "err_code",
    ERR_MSG = "err_msg",
    STATE_CHANGED = "state_changed",
    PERCENT = "percent",
    TAG = "tag"
}

M.PROGRESS_INFO_KEY = {
    FILE_PATH = "file_path",
    SIZE = "size",
    RECV_BYTES = "recv_bytes",
    SPEED = "speed",
    PERCENT = "percent",
    TAG = "tag",
    TASK_ID = "task_id"
}

M.RANGE_INFO_KEY = {
    ETAG = "etag",
    LAST_MODIFIED = "last_modified",
    COMPLETE_SIZE = "complete_size",
    URL = "url",
    TEMP_FILE_PATH = "temp_file_path"
}

M.TASK_INIT_PARAMS = {
    DEST_FILE_PATH = 'dest_file_path',
    FILE_RELA_PATH = "file_rela_path", -- 相对于storage_path，file_rela_path + storage_path = dest_file_path
    FILE_TEMP_PATH = 'file_temp_path',
    TEMP_RELA_PATH = "temp_rela_path", -- 相对于storage_path，temp_rela_path + storage_path = file_temp_path
    STORAGE_PATH = "storage_path", -- 存储根路径
    TASK_ID = 'task_id',
    DEST_FILE_INFO = 'file_dest_info',
    CHECKED_INIT_STATE = "checked_init_state", -- 详细见 M.DOWNLOAD_CHECK_STATE

    -- local info
    LOCAL_INFO = "local_info",
    LOCAL_FIN_EXISTS = "fin_exists",
    LOCAL_FIN_SIZE = "fin_size",
    LOCAL_TMP_EXISTS = "tmp_exists",
    LOCAL_TMP_SIZE = "tmp_size",
    LOCAL_MD5 = "md5",

    -- checked init_info
    CHECKED_STATE_INFO = "checked_init_info", -- 详细见 M.CHCKED_FILE_STATE_KEY
}

M.FILE_DEST_INFO_KEY = {
    URL = "url", -- 可以是url，也可以是path
    NAME = "name", -- 文件名
    STORAGE_PATH = "storage_path", -- 存储空间路径：例如外部或内部存储，详细见storage_type
    DEST_RELA_PATH = "dest_file_rela_path", -- 为（相对路径 + 文件名），dest_file_path = storage_path + dest_file_rela_path
    DEST_FILE_DIR = "dest_file_dir", -- 文件name所处的目录
    DEST_FILE_PATH = "dest_file_path" -- 目标完整路径：dest_file_path = storage_path + dest_file_rela_path
}

-- 下载状态机状态
local _STATES = {
    IDLE = "idle",
    STOPPED = "stopped",
    DOWNLOADING = "downloading",
    COMPLETE = "complete"
}

local _EVENTS = {
    INIT = "init",
    INIT_SUCC = "init_succ",
    START_DOWNLOAD = "start_download",
    REMOVE_DOWNLOAD = "remove_download",
    STOP_DOWNLOAD = "stop_download",
    STOP_DOWNLOAD_SUCC = "stop_download_succ",
    RESUME_DOWNLOAD = "resume_download",
    RESET_DOWNLOAD = "reset_download"
}

-- 单元测试对外暴露
M._UNITEST_EVENT_EXPORT = _EVENTS

local DOWNLOADING_SUFFIX = "_dl_bak_"
local RETRY_TIME_DELAY = 1

M.DOWNLOADING_FILE_SUFFIX = DOWNLOADING_SUFFIX
M.DEFAULT_PROGRESS_NOTIFY_INTERVAL_MILLIS = 1000
M.CHCKED_FILE_STATE_KEY = {
    REAL_SIZE = "real_size",
    TOTAL_SIZE = "total_size",
    CHECKED_STATE = "checked_state" -- 见：M.DOWNLOAD_CHECK_STATE
}

function M.static_get_download_temp_file_path(model_instance, dest_file_dir, name)
    return model_instance:_get_download_temp_file_path(dest_file_dir, name)
end

function M:model_task_name()
    local task_id = nil
    if self then
        task_id = self._data.task_id
    end

    local model_name = self._data.model_instance:get_model_name()
    return tostring(model_name) .. tostring("_") .. tostring(task_id)
end

function M:get_log_tag()
    local task_id = nil
    if self then
        task_id = self._data.task_id
    end

    local log_prefix = self._data.model_instance:get_module_log_prefix()
    local model_name = self._data.model_instance:get_model_name()
    local tag = tostring(log_prefix) .. "#" .. tostring(model_name)
    tag = tag .. "#" .. task_id
    return tag
end

function M:get_log_level()
    local gloabal_config = self._data.model_instance:get_global_config()
    local log_level = gloabal_config.log_output_level or M.INNER_LOG_LEVEL.INFO
    return log_level
end

function M:log_warn(message)
    if not message or message == '' then
        return
    end

    local log_level = self:get_log_level()
    if log_level > M.INNER_LOG_LEVEL.WARN then
        return
    end

    local tag = self:get_log_tag()
    E.LOG.warn(tag, message)
end

function M:log_debug(message)
    if not message or message == '' then
        return
    end

    local log_level = self:get_log_level()
    if log_level > M.INNER_LOG_LEVEL.DEBUG then
        return
    end

    local tag = self:get_log_tag()
    E.LOG.debug(tag, message)
end

function M:_is_log_level_allow(log_level)
    local cur_log_level = self:get_log_level()
    return cur_log_level > log_level
end

function M:_notify_download_state_changed()
    assert("_notify_download_state_changed not call with ':'")
    if not self._data.initted then
        self:log_debug("skip notify while initting")
        return
    end

    local current_state_obj = self._data.download_state
    -- mark state changed
    local last_state = self._data.last_download_state
    local current_state = current_state_obj.state
    if current_state ~= last_state then
        current_state_obj.state_changed = true
        self._data.last_download_state = current_state
    else
        current_state_obj.state_changed = false
    end

    local notify_state = current_state_obj
    if not self._data.disable_deepcopy_result then
        notify_state = utils.deepcopy(current_state_obj)
    end
    -- 统计打点
    if not (self._data.opts and self._data.opts.disable_stat) then
        local download_config = self._data.model_instance.static_get_global_download_config()
        local limit_speed = download_config.limit_speed
        DST.stat_download_state(notify_state, self._data.current_retry_times, limit_speed)
    end
    -- publish global events
    ET.publish(ET.download.DOWNLOAD_STATE_CHANGED, self._data.model_name, self._data.tag, notify_state)

    -- callback listener
    if self._data.download_state_listener then
        self._data.download_state_listener(notify_state.state, notify_state)
    end
end

function M:_notify_download_progress_changed()
    if not self._data.initted then
        self:log_debug("skip notify while initting")
        return
    end

    local speed
    if self:is_downloading() then
        speed = self._data.download_state.speed
    else
        speed = 0
    end

    -- check download speed
    local progress_info = {
        [M.PROGRESS_INFO_KEY.SIZE] = self._data.download_state.size,
        [M.PROGRESS_INFO_KEY.RECV_BYTES] = self._data.download_state.recv_bytes,
        [M.PROGRESS_INFO_KEY.PERCENT] = self._data.download_state.percent,
        [M.PROGRESS_INFO_KEY.FILE_PATH] = self._data.download_state.file_path,
        [M.PROGRESS_INFO_KEY.SPEED] = speed,
        [M.PROGRESS_INFO_KEY.TAG] = self._data.download_state.tag,
        [M.PROGRESS_INFO_KEY.TASK_ID] = self._data.download_state.task_id
    }

    -- callback listener
    if self._data.download_progress_listener then
        self._data.download_progress_listener(progress_info)
    end

    -- publish progress change listener
    ET.publish(ET.download.DOWNLOAD_PROGRESS_CHANGED, self._data.model_name, self._data.tag, progress_info)
end

-- 发送状态机时间内部包装
function M:_fsm_equeue_event_at_front(event_name, ...)
    if self._data.debug_enable then
        self:log_debug("_fsm_send_event:" .. tostring(event_name))
        ET.publish(ET.download.DOWNLOAD_EVENT_SUBMIT, self._data.model_name, self._data.tag, event_name)
    end

    self._data.download_fsm:enqueue_event(event_name, true, ...)
end

function M:_fsm_enqueue_event(event_name, ...)
    if self._data.debug_enable then
        self:log_debug("_fsm_send_event:" .. tostring(event_name))
        ET.publish(ET.download.DOWNLOAD_EVENT_SUBMIT, self._data.model_name, self._data.tag, event_name)
    end

    self._data.download_fsm:enqueue_event(event_name, false, ...)
end

-- 需要限定from，在异步的场景多个transition冲突时只有符合当前状态的from才可以切换
function M:_fsm_transition_to(from_state, to_state, ...)
    local fsm = self._data.download_fsm
    if not from_state then
        from_state = fsm.current
    end

    self:log_debug("_fsm_transition_to, from:" .. tostring(from_state) .. ", to_state:" .. tostring(to_state))

    fsm:transition(from_state, to_state, ...)
end

function M:_fsm_on_async_event_finished(event_name)
    local fsm = self._data.download_fsm
    fsm:notify_async_finish(event_name)
end

function M:_stop_download_task(cb, from)
    if self:_is_log_level_allow(M.INNER_LOG_LEVEL.DEBUG) then
        E.LOG.debug(TAG, "_stop_download_task begin:")
    end

    local transition_handler = function()
        -- try stop download from idle state, for we could not judge if native still downloading
        local current_state = self._data.download_fsm.current
        if current_state == _STATES.DOWNLOADING then
            self:_fsm_transition_to(from, _STATES.STOPPED)
        end
    end

    --  check if support
    local is_support_http_stop = E.is_support_function(E.NATIVE_SUPPORT_FUNCTION_NAMES.HTTP_STOP)
    if not is_support_http_stop then
        self:log_warn("_stop_download_task is not support")
        transition_handler()
        if cb then
            cb(true)
        end
    end

    local task_id = self:task_id()
    E.HTTP.stop({task_id}, {}, function(succ)
        if self:_is_log_level_allow(M.INNER_LOG_LEVEL.DEBUG) then
            self:log_debug("_stop_download_task result:" .. tostring(succ))
        end

        if succ then
            -- try stop download from idle state, for we could not judge if native still downloading
            transition_handler()
        end

        if cb then
            cb(succ)
        end
    end)
end

function M:_do_remove_file(file_path)
    local exists = HRU.is_file_exists(file_path)
    local result
    local err_code = nil
    local err_msg = nil
    if not exists then
        -- not exists we judge it as succ
        result = true
    else
        result, err_msg = HRU.os_remove(file_path)
        -- TODO:这里根据删除操作返回的result来修改错误码的逻辑，包括后续根据result来修改状态机的逻辑，不是很健壮，待后续处理
        if not result then
            err_code = EC.DOWNLOAD_ERROR_CODES.REMOVE_FILE_FAILED
        end
    end

    self:log_debug("_do_remove_file result:" .. tostring(result) .. ", path:" .. tostring(file_path) .. ", code:" .. tostring(err_code) .. ", err_msg:" .. tostring(err_msg))
    return result, err_code, err_msg
end

function M:_remove_downloading_file()
    local downloading_file_path = self._data.temp_file_path
    local succ, code, msg = self:_do_remove_file(downloading_file_path)

    if succ then
        self:_fsm_transition_to(_STATES.STOPPED, _STATES.IDLE)
    end
    return succ, code, msg
end

function M:_remove_local_downloaded_file()
    local downloaded_file = self._data.dest_file_path
    local succ, code, msg = self:_do_remove_file(downloaded_file)

    local global_config = self._data.model_instance:get_global_config()
    local cache_config_enabled = true
    if type(global_config.use_cache_complete_file_md5) == 'boolean' then
        cache_config_enabled = global_config.use_cache_complete_file_md5
    end
    --  sync other cache
    if cache_config_enabled then
        self._data.model_instance:_mark_file_incomplete(self._data.task_id, self._data.dest_file_path)
    end

    return succ, code, msg
end

function M:_rename_local_downloading_to_complete_file()
    local result = E.File.rename_fullpath(self._data.temp_file_path, self._data.dest_file_path)
    if not result then
        -- 尝试再rename一次，避免偶现rename文件时被其它进程占用的场景
        local _msg
        result, _msg = E.File.rename_fullpath(self._data.temp_file_path, self._data.dest_file_path)
        if not result then
            return false, _msg
        end
    end

    local global_config = self._data.model_instance:get_global_config()
    local cache_config_enabled = true
    if type(global_config.use_cache_complete_file_md5) == 'boolean' then
        cache_config_enabled = global_config.use_cache_complete_file_md5
    end

    --_ejoysdk.log("_rename_local_downloading_to_complete_file, cache_config_enabled:" .. tostring(cache_config_enabled))
    if cache_config_enabled and not self._data.invoker_managed_md5_data then
        --  sync other cache
        local md5_str = self._data.file_ext and self._data.file_ext.md5 or nil
        if md5_str and md5_str ~= '' then
            self._data.model_instance:_update_complete_file_md5(self._data.task_id, self._data.dest_file_path, md5_str)
        end
    end

    return true
end

function M:_remove_downloaded_file_state()
    local succ, code, msg = self:_remove_local_downloaded_file()

    if succ then
        self:_fsm_transition_to(_STATES.COMPLETE, _STATES.IDLE)
    end
    return succ, code, msg
end

function M:_check_complete_file_md5()
    local md5_result = M.static_check_complete_file_md5(self._data.model_instance, self._data.task_id, self._data.dest_file_path)
    return md5_result
end

function M.static_check_complete_file_md5(model_instance, task_id, dest_file_path)
    local global_config = model_instance:get_global_config()
    local cache_config_enabled = true
    if type(global_config.use_cache_complete_file_md5) == 'boolean' then
        cache_config_enabled = global_config.use_cache_complete_file_md5
    end

    local md5_result
    if cache_config_enabled then
        md5_result = model_instance:_get_complete_file_md5_cache(task_id, dest_file_path)
    end

    if not md5_result or md5_result == '' then
        md5_result = HRU.check_file_md5(dest_file_path)
    end

    if DST.is_log_allow_with_level(DST.INNER_LOG_LEVEL.DEBUG) then
        DST.log_debug(TAG, "_check_complete_file_md5 path:" .. tostring(dest_file_path) .. ", md5:" .. tostring(md5_result))
    end

    return md5_result
end

function M:_update_downloading_range_info(range_info)
    self:log_debug("_update_downloading_range_info begin")
    self._data.model_instance:_update_file_range_info(self._data.task_id, range_info)
end

function M:_reset_downloading_range_info()
    self:log_debug(TAG, "_reset_downloading_range_info begin")
    self:_update_downloading_range_info(nil)
end

-- here downloading is already begin, and file valid check is finished at native side, so directly update local cache
function M:_on_receive_download_response_header(headers)
    local content_length = headers["Content-Length"] or headers["content-length"] or 0
    content_length = tonumber(content_length)

    local range_info = {
        [M.RANGE_INFO_KEY.ETAG] = headers["ETag"] or headers["Etag"] or headers["etag"],
        [M.RANGE_INFO_KEY.LAST_MODIFIED] = headers["Last-Modified"] or headers["last-modified"],
        [M.RANGE_INFO_KEY.COMPLETE_SIZE] = content_length,
        [M.RANGE_INFO_KEY.URL] = self._data.url
        --[M.RANGE_INFO_KEY.TEMP_FILE_PATH] = self._data.temp_file_path -- 暂时用不到，节省缓存文件占用空间
    }

    self:log_debug("_on_receive_download_response_header, begin _update_downloading_range_info")
    self:_update_downloading_range_info(range_info)
end

function M:_do_start_download()
    local url = self._data.url
    local log_level = self:get_log_level()
    -- 切换备用域名进行重试
    local retry_times = self._data.current_retry_times or 0
    if self._data.file_ext and self._data.file_ext.backup_urls and type(self._data.file_ext.backup_urls) == 'table' and retry_times > 0 then
        local backup_urls_count = #self._data.file_ext.backup_urls
        if backup_urls_count > 0 then
            local retry_index = retry_times % (backup_urls_count + 1)
            if retry_index > 0 and retry_index <= backup_urls_count then
                url = self._data.file_ext.backup_urls[retry_index]
                if log_level <= M.INNER_LOG_LEVEL.DEBUG then
                    self:log_debug("start_download, retry_times:" .. tostring(retry_times) .. " backup_url:" .. tostring(url))
                end
            end
        end
    end

    local task_id = self._data.task_id
    local global_config = self._data.model_instance:get_global_config()
    local file_expect_size = self._data.file_ext and self._data.file_ext.size or nil
    local max_retry_times = self._data.max_retry_times or global_config.max_retry_times
    local connect_timeout = global_config.connect_timeout
    local read_timeout = global_config.read_timeout
    local _use_independent_pool = self._data.use_independent_pool -- 是否使用独立线程池
    if type(_use_independent_pool) ~= 'boolean' then
        _use_independent_pool = global_config.use_independent_pool
    end

    if log_level <= M.INNER_LOG_LEVEL.DEBUG then
        self:log_debug("do_start_download max retry times:" .. tostring(max_retry_times) .. ", connect_timeout:" .. tostring(connect_timeout) .. ", read timeout:" .. tostring(read_timeout) .. ", use_independent_pool:" .. tostring(_use_independent_pool))
    end
    --E.log("global_config >>")
    --E.log(global_config)

    local downloading_file_path = self._data.temp_file_path
    if log_level <= M.INNER_LOG_LEVEL.DEBUG then
        self:log_debug("start_download, temp_file_path:" .. downloading_file_path)
    end

    local down_fail_handler = function(code, msg)
        self:log_warn("download error " .. tostring(self._data.name) .. ", code:" .. tostring(code) .. ", msg:" .. tostring(msg))
        if code == EC.DOWNLOAD_ERROR_CODES.CANCELLED then
            -- 下载停止事件是内部触发处理，无需单独处理为下载出错
            self:log_debug("down_fail_handler download cancelled received, already processed inner, skip")
            return
        end

        local need_delete_file = false
        if (code >=400 and code < 500) and code ~= 408 and code ~= 429 and code ~= 499 then
            need_delete_file = true
        end
        --- 错误码为md5校验失败、range不匹配需要删除文件(native)
        if code == EC.EJOYSDK_ERROR_CODES.RES_DOWNLOAD_MD5_MISMATCH or need_delete_file then
            self:log_debug("download_fail_handler, md5 check failed:" .. tostring(code) .. ", begin rm file:" .. tostring(downloading_file_path))

            HRU.os_remove(downloading_file_path)
            self._data.download_state.recv_bytes = 0
            self._data.download_state.percent = 0
        end

        self._data.current_retry_times = self._data.current_retry_times + 1
        if self._data.current_retry_times > max_retry_times then
            -- send download failed
            self:log_warn("retry times reaches max times now send download failed event, code:" .. tostring(code) .. ", msg:" .. tostring(msg))

            -- 更新下载失败错误信息
            self._data.download_state.err_code = code
            self._data.download_state.err_msg = msg
            self:_fsm_transition_to(_STATES.DOWNLOADING, _STATES.STOPPED)
        else
            -- mark download state retrying here
            -- do retry
            E.Timer.once(
                    RETRY_TIME_DELAY,
                    function()
                        if self._data.download_fsm.current ~= _STATES.DOWNLOADING then
                            --self:log_debug("current stopped, skip retrying")
                            return
                        end

                        self:log_warn(string.format("down_file fail,retry cnt=%s file=%s", self._data.current_retry_times, tostring(self._data.name)))
                        self:_do_start_download()
                    end
            )
        end
    end

    local down_succ_handler = function()
        self:log_debug("down_succ_handler received, send download_succ event:" .. tostring(self:task_tag_name()))
        -- send download succ event
        self:_fsm_transition_to(_STATES.DOWNLOADING, _STATES.COMPLETE)
    end

    local _down_cb = function(ret)
        -- ios 的 status有概率为nil, 这里做兜底处理
        ret.status = ret.status or EC.GLOBAL_GANGPLANK_ERROR_CODE.GLOBAL_HTTP_RESPONSE_STATUS_INVALID

        if (ret.status >= 200 and ret.status < 300) or ret.status == 0 then

            -- windows 用lua c的md5计算，IOS和Android用自己native的。原因目前发现lua c的 md5 代码有性能问题，Android和IOS的代码效率较lua c的高
            -- 所以此时返回200的时候Android和IOS都是校验md5成功的，所以check_md5_result默认为true
            local check_md5_result = true
            local expect_md5_str = self._data.file_ext and self._data.file_ext.md5 or nil
            if _ejoysdk.os() == "windows" and expect_md5_str then
                local md5_hex_str = HRU.check_file_md5(downloading_file_path)
                check_md5_result = (md5_hex_str == expect_md5_str)
                E.LOG.debug(TAG, "windows check md5 result, cur:" .. tostring(md5_hex_str) .. ", expect:" .. tostring(expect_md5_str) .. ", result:" .. tostring(check_md5_result))
            end


            local file_real_size
            local file_size_check
            if not file_expect_size or file_expect_size == 0 then
                local file_exists, file_size = HRU.is_file_exists(downloading_file_path)
                if file_exists then
                    file_size_check = true
                    file_real_size = file_size
                else
                    file_size_check = false
                    file_real_size = 0
                end
            else
                local is_valid, _file_exists, file_size = HRU.check_file_valid(downloading_file_path, file_expect_size)
                if is_valid then
                    file_size_check = true
                else
                    file_size_check = false
                end

                file_real_size = file_size
            end

            self:log_debug("recv file download succ, file_size_check result:" .. tostring(file_size_check) .. ", size:" .. tostring(file_real_size) .. ", check md5 result:" .. tostring(check_md5_result))
            if file_size_check and check_md5_result then
                local result, msg = self:_rename_local_downloading_to_complete_file()
                if result then
                    self:log_debug("succ move from:" .. tostring(downloading_file_path) .. ", to:" .. tostring(self._data.dest_file_path))

                    -- callback succ
                    self._data.download_state.size = file_real_size
                    down_succ_handler()
                else
                    DST.stat_action_fail("download_finish_rename_failed", self._data.dest_file_path, url, msg)
                    down_fail_handler(EC.EJOYSDK_ERROR_CODES.RES_DOWNLOAD_RENAME_FAILED, "download finish file rename failed, " .. tostring(msg))
                end

            else
                down_fail_handler(EC.EJOYSDK_ERROR_CODES.RES_DOWNLOAD_MD5_MISMATCH, "download finish file invalid")
            end
        else
            self:log_warn("receive download failed:" .. tostring(ret.status))
            down_fail_handler(ret.status, "download failed")
        end
    end

    local last_noti_clock = 0
    local _progress = function(_, _file, recv, total, _headers)
        if self._data.download_state.state ~= _STATES.DOWNLOADING then
            --self:log_debug('state not downloading, not callback progress function....')
            return
        end

        if self._data.download_state.size == 0 then
            self._data.download_state.size = total
        end

        -- update receive bytes
        self._data.download_state.recv_bytes = recv

        local p = math.floor(recv / total * 100)
        local current_percent = self._data.download_state.percent
        local progress_changed = p ~= current_percent
        self._data.download_state.percent = p

        if log_level <= M.INNER_LOG_LEVEL.DEBUG then
            self:log_debug("lua recv progress:" .. tostring(recv) .. ", total:" .. tostring(total) .. ", p:" .. tostring(p) .. ", current_p:" .. tostring(current_percent) .. ", speed:" .. tostring(self._data.download_state.speed) .. ", limit:" .. tostring(self._data.model_instance:get_global_config().max_bandwidth_kbytes_per_sec))
        end
        -- 这里判断大于是因为进度通知队列的优先级比事件通知队列低，会出现下载完成先收到，此时进度100%， 但是进度通知后收到，导致后面的进度小于100%

        -- 限制通知频率
        local currnet_noti_clock = E.system_clock()
        -- 通知当前的下载进度
        local progress_notify_interval_millis = self._data.progress_notify_interval_millis or global_config.progress_notify_interval_millis
        if (currnet_noti_clock - last_noti_clock > progress_notify_interval_millis) then
            self:log_debug("lua recv progress:" .. tostring(recv) .. ", total:" .. tostring(total) .. ", p:" .. tostring(p) .. ", current_p:" .. tostring(current_percent) .. ", speed:" .. tostring(self._data.download_state.speed) .. ", limit:" .. tostring(self._data.model_instance:get_global_config().max_bandwidth_kbytes_per_sec))
            local biz_name = self:model_task_name()
            local speed_val = HRU.check_download_speed(biz_name, recv, total)
            if speed_val >= 0 then
                self._data.download_state.speed = speed_val
            end

            last_noti_clock = currnet_noti_clock

            self:_notify_download_progress_changed()
        end

        if progress_changed then
            -- notify download progress changed
            self:_notify_download_state_changed()
        end
    end

    local _header_cb = function(_headers)
        --E.LOG.debug(TAG, "receive headers >>")
        --E.log(_headers)
        -- 更新headers
        self:_on_receive_download_response_header(_headers)
    end

    local _global_config = self._data.model_instance:get_global_config()
    -- try get limit speed enable state
    local _enable_limit_speed = self._data.enable_limit_speed
    if _enable_limit_speed == nil then
        _enable_limit_speed = _global_config.enable_limit_speed
    end

    local _download_range_enable = self._data.enable_download_range
    if _download_range_enable == nil then
        _download_range_enable = _global_config.enable_download_range
    end

    if log_level <= M.INNER_LOG_LEVEL.DEBUG then
        self:log_debug("enable_limit_speed:" .. tostring(_enable_limit_speed) .. ", range enable:" .. tostring(_download_range_enable))
    end

    local down_params = {
        taskId = task_id,
        file = downloading_file_path,
        checksum = self._data.file_ext and self._data.file_ext.md5 or nil,
        connectionTimeout = connect_timeout,
        dataRetrievalTimeout = read_timeout,
        progress = _progress,
        header_cb = _header_cb,
        enable_download_range = _download_range_enable,
        use_independent_pool = _use_independent_pool,
        thread_count = 5,
        priority = self._data.priority,
        enable_limit_speed = _enable_limit_speed,
        headers = {} -- 这里的
    }

    -- 设置断点续传headers
    if _download_range_enable then
        if log_level <= M.INNER_LOG_LEVEL.DEBUG then
            self:log_debug("enabled download range")
        end
        local range_info = self._data.model_instance:_get_file_range_info_by_id(task_id)
        if range_info then
            local etag = range_info[M.RANGE_INFO_KEY.ETAG]
            local last_modified = range_info[M.RANGE_INFO_KEY.LAST_MODIFIED]
            local if_range_field = etag
            if not if_range_field or if_range_field == "" then
                if_range_field = last_modified
            end

            down_params["param_if_range"] = if_range_field
            self:log_debug("start download, param_if_range:" .. tostring(if_range_field))
        else
            self:log_debug("start download, no last range info, not set param_if_range")
        end

        --update range header
        local range_fun_name
        local _os = _ejoysdk.os()
        if _os == 'android' then
            range_fun_name = E.NATIVE_SUPPORT_FUNCTION_NAMES.HTTP_DOWNLOAD_RANGE
        elseif _os == 'ios' then
            range_fun_name = E.NATIVE_SUPPORT_FUNCTION_NAMES.HTTP_DOWNLOAD_RANGE
        else
            range_fun_name = E.NATIVE_SUPPORT_FUNCTION_NAMES.HTTP_DOWNLOAD_RANGE_V1
        end

        if E.is_support_function(range_fun_name) then
            if self._data.download_state.recv_bytes and self._data.download_state.recv_bytes > 0 then
                down_params.headers = down_params.headers or {}
                local _is_exist, size = HRU.is_file_exists(down_params.file)
                -- 以下不按header的驼峰格式传入，因为想行为上同ejoysdk.HTTP.Header，HTTP.Header.New会将sdk params里面的key都转小写
                down_params.headers['range'] = 'bytes=' .. tostring(size) .. '-'
                -- check_and_update_headers change Range to lower case
                self:log_debug(' range download continue, start with size:'.. tostring(self._data.download_state.recv_bytes))
            else
                self:log_debug(' start download new file')
            end
        end
    else
        if log_level <= M.INNER_LOG_LEVEL.DEBUG then
            self:log_debug("start download, enable_download_range false, skip set if-range")
        end
    end

    -- do url encode
    -- try check if url already encoded
    local decode_url = E.HTTP.decode_uri(url)
    local is_url_encode = decode_url ~= url
    if not is_url_encode then
        url = E.HTTP.encode_uri(url)
    end

    if log_level <= M.INNER_LOG_LEVEL.DEBUG then
        self:log_debug("do http get with url:" .. tostring(url))
    end

    --_ejoysdk.log("process_get max retry times:" .. tostring(max_retry_times) .. ", use_independent_pool:" .. tostring(_use_independent_pool) .. ", url:" .. tostring(url))
    E.HTTP.process_get(url, down_params, _down_cb)
end

function M:_inner_start_download()
    self:_do_start_download()
    -- 真正开始下载，已经提交任务到native了，才切换状态。不然提前停止任务会发现native没有任务
    self:_fsm_transition_to(nil, _STATES.DOWNLOADING)
end

function M:_check_init_download_state()
    local checked_info = self._data.init_check_params[M.TASK_INIT_PARAMS.CHECKED_STATE_INFO]
    if checked_info then
        local checked_state = self._data.init_check_params[M.TASK_INIT_PARAMS.CHECKED_INIT_STATE]
        return checked_state, checked_info
    else
        return M._static_check_init_download_state(self._data.url, self._data.task_id, self._data.file_ext, self._data.file_dest_info, self._data.model_instance, self._data.init_check_params)
    end
end

-- 静态检查下载是否完成
-- @return state and current size, state in {@M.DOWNLOAD_STATE}
function M._static_check_init_download_state(url, task_id, file_ext, file_dest_info, model_instance, init_check_params)
    local dest_file_path = file_dest_info.dest_file_path
    file_ext = file_ext or {}
    local size = file_ext.size or 0
    local file_has_md5 = file_ext.md5 and file_ext.md5 ~= ''
    local expect_file_md5_value = file_ext.md5
    init_check_params = init_check_params or {}
    local file_local_info = init_check_params[M.TASK_INIT_PARAMS.LOCAL_INFO]
    local finish_file_exists = false
    local tmp_file_exists = false
    local finish_file_size = 0
    local tmp_file_size = 0
    local fin_md5
    -- 外部已经传入了检测信息
    if file_local_info then
        finish_file_exists = file_local_info[M.TASK_INIT_PARAMS.LOCAL_FIN_EXISTS]
        tmp_file_exists = file_local_info[M.TASK_INIT_PARAMS.LOCAL_TMP_EXISTS]
        finish_file_size = file_local_info[M.TASK_INIT_PARAMS.LOCAL_FIN_SIZE] or 0
        tmp_file_size = file_local_info[M.TASK_INIT_PARAMS.LOCAL_TMP_SIZE] or 0
        fin_md5 = file_local_info[M.TASK_INIT_PARAMS.LOCAL_MD5]
    end

    -- 1. 先检查dest_file_path 是否存在，存在则检查md5和size
    -- 2. 检查downloading文件的rangeinfo是否更改，再检查文件的md5和size
    local state_info = {
        [M.CHCKED_FILE_STATE_KEY.TOTAL_SIZE] = size
    }

    local fin_exists
    if file_local_info then
        fin_exists = finish_file_exists
    else
        fin_exists = HRU.file_exists(dest_file_path)
    end
    if fin_exists then
        -- 这里需要校验md5，保证同名文件再次提交时可以重新下载
        if file_has_md5 then
            local real_file_md5 = fin_md5 or M.static_check_complete_file_md5(model_instance, task_id, dest_file_path) -- here md5 is optimized
            if real_file_md5 == expect_file_md5_value then
                if not size or size == 0 then
                    if finish_file_size > 0 then
                        size = finish_file_size
                    else
                        size = HRU.get_file_size(dest_file_path)
                    end
                end

                --self:log_debug("_init already exists valid file, transition to complete state")
                state_info[M.CHCKED_FILE_STATE_KEY.REAL_SIZE] = size
                state_info[M.CHCKED_FILE_STATE_KEY.TOTAL_SIZE] = size
                return M.DOWNLOAD_CHECK_STATE.COMPLETE_FILE_VALID, state_info
            else
                --E.LOG.debug(TAG, "file exists and not valid, remove it:" .. tostring(dest_file_path))
                state_info[M.CHCKED_FILE_STATE_KEY.REAL_SIZE] = 0
                return M.DOWNLOAD_CHECK_STATE.COMPLETE_FILE_INVALID, state_info
            end
        else
            local real_size = finish_file_size
            if real_size == 0 then
                real_size = HRU.get_file_size(dest_file_path)
            end

            -- size 0 is also could not compare, so need return valid
            if real_size == size or size == 0 then
                --self:log_debug("_init already exists valid file, transition to complete state")
                state_info[M.CHCKED_FILE_STATE_KEY.REAL_SIZE] = real_size
                state_info[M.CHCKED_FILE_STATE_KEY.TOTAL_SIZE] = real_size
                return M.DOWNLOAD_CHECK_STATE.COMPLETE_FILE_VALID, state_info
            else
                --E.LOG.debug(TAG, "file exists and not valid, remove it:" .. tostring(dest_file_path))
                state_info[M.CHCKED_FILE_STATE_KEY.REAL_SIZE] = 0
                return M.DOWNLOAD_CHECK_STATE.COMPLETE_FILE_INVALID, state_info
            end
        end
    else
        local downloading_file_path = init_check_params[M.TASK_INIT_PARAMS.FILE_TEMP_PATH]
        if not downloading_file_path then
            downloading_file_path = M.static_get_download_temp_file_path(model_instance, file_dest_info.dest_file_dir, file_dest_info.name)
        end
        -- 任务创建时如果发现文件是_dl_bak_结尾则代表是下载中状态，此时有两种情况：
        -- 1. 上次文件下载到一半
        -- 2. lua虚拟机重启，native仍然在下载。这种情况Lua逻辑需要重新调用start_download保证流程完整，而native需要支持正在下载中的task能和当前start_download的调用对应，即下载状态回调需要对应
        -- 所以统一处理是此时初始化时发送消息给native 停止下载消息，然后切到paused状态
        local is_downloading
        local downloading_file_size
        if file_local_info then
            is_downloading = tmp_file_exists
            downloading_file_size = tmp_file_size
        else
            is_downloading, downloading_file_size = HRU.is_file_exists(downloading_file_path)
        end

        state_info[M.CHCKED_FILE_STATE_KEY.REAL_SIZE] = downloading_file_size
        if is_downloading then
            -- 检查断点续传信息
            local last_range_info = model_instance:_get_file_range_info_by_id(task_id)
            if last_range_info then
                local _last_url = last_range_info[M.RANGE_INFO_KEY.URL]
                if _last_url ~= url then
                    E.LOG.warn(TAG, "last downloading file, url changes, last:" .. tostring(_last_url) .. ", current:" .. tostring(url))
                    local stat_params = {
                        last_url = _last_url,
                        url = url,
                        dest_file_path = downloading_file_path
                    }
                    DST.stat_action("resume_download_url_change", nil, false, stat_params)

                    state_info[M.CHCKED_FILE_STATE_KEY.REAL_SIZE] = 0 -- not same file, so here is 0
                    return M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_INVALID, state_info
                end

                -- 检查下载任务是否完成。可能游戏切后台之后lua虚拟机暂停，无法收到下载完成事件，但是下载文件完整。此时文件有两种可能已下载完成，未下载完成
                local total_file_size = size
                if total_file_size == 0 then
                    total_file_size = last_range_info[M.RANGE_INFO_KEY.COMPLETE_SIZE] or 0
                end

                -- 更新上次下载进度
                total_file_size = tonumber(total_file_size)
                state_info[M.CHCKED_FILE_STATE_KEY.TOTAL_SIZE] = total_file_size -- update total_size
                if total_file_size ~= downloading_file_size then
                    return M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_INCOMPLETE, state_info
                end

                -- 此时文件可能下载完成，需要校验文件是否下载完
                if file_has_md5 then
                    local downloading_file_md5 = HRU.check_file_md5(downloading_file_path)
                    if downloading_file_md5 == expect_file_md5_value then
                        --self:log_debug("_init already exists valid file, transition to complete state")
                        return M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_VALID, state_info
                    else
                        --self:log_debug("_init already exists, but invalid, md5 not same transition to idle state, downloading_md5:" .. tostring(downloading_file_md5) .. ", expect_md5:" .. tostring(self._data.file_ext.md5))
                        --self:log_debug("begin remove downloading file:" .. tostring(downloading_file_path))
                        state_info[M.CHCKED_FILE_STATE_KEY.REAL_SIZE] = 0 -- size same but md5 different, so the file is invalid
                        return M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_INVALID, state_info
                    end
                else
                    --self:log_debug("_init already exists valid file, transition to complete state, no md5 check, size check is succ")
                    return M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_VALID, state_info
                end
            else
                state_info[M.CHCKED_FILE_STATE_KEY.REAL_SIZE] = 0 -- not has last range info, so we do not range download, the downloading size here is 0
                return M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_INVALID, state_info
            end
        else
            state_info[M.CHCKED_FILE_STATE_KEY.REAL_SIZE] = 0 -- not exists, so here is 0
            return M.DOWNLOAD_CHECK_STATE.NOT_DOWNLOAD, state_info
        end
    end
end

-- task 初始化
function M:_init(_task_id, _url, _file_ext, _opts, params, _model_instance)
    assert(self, "call task New with missing ':'mark")

    local fsm_callbacks = {
        ["on" .. _EVENTS.INIT] = function(_f_self, from)
            if from ~= _STATES.IDLE then
                self:log_debug("init event always processed by undefined state")
                return FSM.SYNC
            end

            local downloading_file_path = self._data.temp_file_path
            local file_state, checked_state_info = self:_check_init_download_state()
            local total_size = checked_state_info.total_size
            self._data.download_state.size = total_size -- update total_size
            if file_state == M.DOWNLOAD_CHECK_STATE.COMPLETE_FILE_VALID then
                -- update state size
                self._data.download_state.size = checked_state_info.total_size
                self:_fsm_transition_to(_STATES.IDLE, _STATES.COMPLETE)
            elseif file_state == M.DOWNLOAD_CHECK_STATE.COMPLETE_FILE_INVALID then
                -- 删除无效文件
                self:_remove_local_downloaded_file()
                -- remain idle
            elseif file_state == M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_INVALID then
                HRU.os_remove(downloading_file_path)
                -- update last range_info to nil
                self:_reset_downloading_range_info()
                -- remain idle
            elseif file_state == M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_INCOMPLETE then
                local downloading_size = checked_state_info.real_size
                self._data.download_state.recv_bytes = downloading_size
                self._data.download_state.percent = 0
                if total_size > 0 then
                    self._data.download_state.percent = math.floor(downloading_size / total_size * 100)
                end

                -- 切到stopped状态
                self:_fsm_transition_to(_STATES.IDLE, _STATES.STOPPED)
            elseif file_state == M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_VALID then
                -- its complete
                -- change downloading file to complete file
                local result, msg = self:_rename_local_downloading_to_complete_file()
                if result then
                    self:_fsm_transition_to(_STATES.IDLE, _STATES.COMPLETE)
                else
                    self:log_warn("rename failed, " .. tostring(msg))
                    -- 切到stopped状态
                    self:_fsm_transition_to(_STATES.IDLE, _STATES.STOPPED)
                end
            elseif file_state == M.DOWNLOAD_CHECK_STATE.DOWNLOADING_FILE_INVALID then
                -- md5 not same, it's invalid
                HRU.os_remove(downloading_file_path)
                -- reset current download state
                self._data.download_state.recv_bytes = 0
                self._data.download_state.percent = 0
                -- remain idle
            end

            self:_fsm_equeue_event_at_front(_EVENTS.INIT_SUCC)
            return FSM.SYNC
        end,
        ["on" .. _EVENTS.INIT_SUCC] = function(_fsm, _from, ...)
            self:log_debug("init succ")
            self._data.initted = true
            return FSM.SYNC
        end,
        ["on" .. _EVENTS.START_DOWNLOAD] = function(_fsm, from, ...)
            self:log_debug("receive start_download event, from:" .. tostring(from))
            if from == _STATES.IDLE then
                self:_inner_start_download()
                return FSM.SYNC
            elseif from == _STATES.STOPPED then
                -- submit resume_download event
                self:_fsm_equeue_event_at_front(_EVENTS.RESUME_DOWNLOAD, ...)
                return FSM.SYNC
            elseif from == _STATES.DOWNLOADING then
                self:log_debug("start_download already downloading, now callback directly")
                -- a new invoke on cached task, notify with current task state
                self:_notify_download_progress_changed()
                self:_notify_download_state_changed()
                return FSM.SYNC
            elseif from == _STATES.COMPLETE then
                self:log_debug("start_download already downloaded, now callback downloaded state directly")
                -- a new invoke on cached task, notify with current task state
                self:_notify_download_progress_changed()
                self:_notify_download_state_changed()
                return FSM.SYNC
            end
        end,
        ["on" .. _EVENTS.RESUME_DOWNLOAD] = function(_fsm, from, ...)
            if from ~= _STATES.STOPPED then
                self:log_debug("resume download in not paused state, return")
                return FSM.SYNC
            end

            self:log_debug("resume download begin")
            -- 断点续传就不能删除文件了
            --self:_remove_downloading_file()
            self:_inner_start_download()
            return FSM.SYNC
        end,
        ["on" .. _EVENTS.STOP_DOWNLOAD] = function(_fsm, from, ...)
            local p_cb = ...
            local p_cb_wrapper = function(p_succ, ...)
                if p_succ then
                    self:log_debug("stop_download succ")
                else
                    local p_code, p_msg = ...
                    self:log_warn("stop_download failed, code:" .. tostring(p_code) .. ", msg:" .. tostring(p_msg))
                end

                if p_cb then
                    p_cb(p_succ, ...)
                end
            end

            if from == _STATES.IDLE then
                self:log_debug("pause in idle state, just return true")
                p_cb_wrapper(true)
                return FSM.SYNC
            elseif from == _STATES.STOPPED or from == _STATES.COMPLETE then
                self:log_debug("stop in state: " .. tostring(from) ..", just return true")
                p_cb_wrapper(true)
                return FSM.SYNC
            elseif from == _STATES.DOWNLOADING then
                self:_stop_download_task(function(succ, ...)
                    if succ then
                        self:_fsm_equeue_event_at_front(_EVENTS.STOP_DOWNLOAD, p_cb)
                    else
                        local cd_code, cd_msg = ...
                        p_cb_wrapper(false, cd_code, cd_msg)
                    end

                    self:_fsm_on_async_event_finished(_EVENTS.STOP_DOWNLOAD)
                end)

                return FSM.ASYNC
            end
        end,
        ["on" .. _EVENTS.RESET_DOWNLOAD] = function(_fsm, from, ...)
            local reset_download_cb = ...
            local download_cb_wrapper = function(succ, ...)
                if reset_download_cb then
                    reset_download_cb(succ, ...)
                end
            end

            if from == _STATES.IDLE then
                self:_fsm_equeue_event_at_front(_EVENTS.START_DOWNLOAD, ...)
                return FSM.SYNC
            elseif from == _STATES.STOPPED then
                --  remove downloading file and start download
                local r_succ = self:_remove_downloading_file()
                if r_succ then
                    -- begin start download
                    self:_fsm_equeue_event_at_front(_EVENTS.RESET_DOWNLOAD, ...)
                else
                    -- callback download listener failed
                    download_cb_wrapper(false, EC.DOWNLOAD_ERROR_CODES.REMOVE_FILE_FAILED, "remove downloading file failed")
                end

                return FSM.SYNC
            elseif from == _STATES.DOWNLOADING then
                -- cancel download, and remove downloading file, then transition to undefined state and send reset download event
                self:_stop_download_task(function(rd_succ, ...)
                    if rd_succ then
                        self:_fsm_equeue_event_at_front(_EVENTS.RESET_DOWNLOAD, reset_download_cb)
                    else
                        -- callback download listener, canncel previous task failed. And retain current state
                        download_cb_wrapper(false, EC.DOWNLOAD_ERROR_CODES.STOP_DOWNLOAD_FAILED, "stop download task failed")
                    end

                    -- wait for future transition
                    self:_fsm_on_async_event_finished(_EVENTS.RESET_DOWNLOAD)
                end)

                return FSM.ASYNC
            elseif from == _STATES.COMPLETE then
                -- delete downloaded file, and start download, transition to downloading state
                local succ = self:_remove_downloaded_file_state()
                if succ then
                    self:_fsm_equeue_event_at_front(_EVENTS.RESET_DOWNLOAD, ...)
                else
                    download_cb_wrapper(false, EC.DOWNLOAD_ERROR_CODES.REMOVE_FILE_FAILED, "remove downloaded file failed")
                end

                return FSM.SYNC
            end
        end,
        ["on" .. _EVENTS.REMOVE_DOWNLOAD] = function(_fsm, from, ...)
            local rd_cb = ...
            local rd_cb_wrapper = function(rd_succ, ...)
                if rd_cb then
                    rd_cb(rd_succ, ...)
                end
            end

            --self:log_debug("event remove_download, from:" .. tostring(from))
            if from == _STATES.IDLE then
                self:log_debug("remove_download succ, begin callback")
                rd_cb_wrapper(true)
                return FSM.SYNC
            elseif from == _STATES.STOPPED then
                local succ, err_code, err_msg = self:_remove_downloading_file()
                if succ then
                    self:_fsm_equeue_event_at_front(_EVENTS.REMOVE_DOWNLOAD, ...)
                else
                    rd_cb_wrapper(false, err_code, err_msg)
                end

                return FSM.SYNC
            elseif from == _STATES.DOWNLOADING then
                self:_stop_download_task(function(rd_succ, ...)
                    if rd_succ then
                        self:_fsm_equeue_event_at_front(_EVENTS.REMOVE_DOWNLOAD, rd_cb)
                    else
                        local c_code, c_message = ...
                        self:log_warn("event remove_download, cancel download task faild, code:" .. tostring(c_code) .. ", message:" .. tostring(c_message))
                        rd_cb_wrapper(false, c_code, c_message)
                    end

                    self:_fsm_on_async_event_finished(_EVENTS.REMOVE_DOWNLOAD)
                end)

                return FSM.ASYNC
            elseif from == _STATES.COMPLETE then
                local r_result, r_code, r_msg = self:_remove_downloaded_file_state()
                if r_result then
                    self:_fsm_equeue_event_at_front(_EVENTS.REMOVE_DOWNLOAD, ...)
                else
                    rd_cb_wrapper(false, r_code, r_msg)
                end

                return FSM.SYNC
            end
        end,
        ---- states listener
        ["onenter" .. _STATES.IDLE] = function(_fsm, from, ...)
            self:log_debug("onenter idle, from:" .. tostring(from) .. ", reset current download state")
            local current_download_state = self._data.download_state
            current_download_state.state = M.DOWNLOAD_STATE.IDLE
            current_download_state.recv_bytes = 0
            current_download_state.err_code = 0
            current_download_state.err_msg = nil
            current_download_state.percent = -1
            current_download_state.speed = 0

            -- 重置测速数据
            local biz_name = self:model_task_name()
            HRU.reset_download_speed(biz_name)

            self._data.current_retry_times = 0
            -- notify download state changed
            self:_notify_download_progress_changed()
            self:_notify_download_state_changed()
        end,
        ["onenter" .. _STATES.STOPPED] = function(_fsm, from, ...)
            self:log_debug("onenter stopped, from:" .. tostring(from))
            local current_download_state = self._data.download_state
            if current_download_state.err_code == 0 then
                current_download_state.err_code = EC.DOWNLOAD_ERROR_CODES.CANCELLED
                current_download_state.err_msg = "download cancelled"
                current_download_state.state = M.DOWNLOAD_STATE.STOPPED
            else
                current_download_state.state = M.DOWNLOAD_STATE.FAILED
            end
            current_download_state.speed = 0

            -- 重置测速数据
            local biz_name = self:model_task_name()
            HRU.reset_download_speed(biz_name)

            self._data.current_retry_times = 0
            -- notify download state changed
            self:_notify_download_progress_changed()
            self:_notify_download_state_changed()
        end,
        ["onenter" .. _STATES.COMPLETE] = function(_f_self, from, ...)
            self:log_debug("onenter complete, from:" .. tostring(from))
            local current_download_state = self._data.download_state
            current_download_state.state = M.DOWNLOAD_STATE.COMPLETE
            current_download_state.err_code = 0
            current_download_state.err_msg = nil
            current_download_state.percent = 100
            current_download_state.recv_bytes = current_download_state.size
            current_download_state.speed = 0
            if self._data.download_begin_time > 0 then
                current_download_state.duration = E.time() - self._data.download_begin_time
            end

            if from == M.DOWNLOAD_STATE.DOWNLOADING then
                -- 下载完成，重置断点续传信息
                self:_reset_downloading_range_info()
            end

            self._data.current_retry_times = 0
            -- notify download state changed
            self:_notify_download_state_changed()
        end,
        ["onenter" .. _STATES.DOWNLOADING] = function(_f_self, _from, ...)
            self:log_debug("onenter downloading, from:" .. tostring(_from))
            local current_download_state = self._data.download_state
            current_download_state.state = M.DOWNLOAD_STATE.DOWNLOADING
            current_download_state.err_code = 0
            current_download_state.err_msg = nil

            self._data.download_begin_time = E.time()
            -- notify download state changed
            self:_notify_download_state_changed()
        end,
        ["onleave" .. _STATES.DOWNLOADING] = function(_f_self, _to, ...)
            self:log_debug("onleave downloading, to:" .. tostring(_to))
            -- 反注册progress_cb
            E.HTTP.unregister_progress_cb(self._data.task_id)
        end
    }

    local _download_fsm = FSM.create({
        initial = _STATES.IDLE,
        events = {
            -- ejoy 的状态机目前不支持数组
            --{ name = _EVENTS.INIT, from = _STATES.UNDEFINED, to = { _STATES.UNDEFINED, _STATES.PAUSED, _STATES.COMPLETE} },
            { name = _EVENTS.INIT, from = _STATES.IDLE, to = _STATES.IDLE },
            { name = _EVENTS.INIT, from = _STATES.IDLE, to = _STATES.STOPPED },
            { name = _EVENTS.INIT, from = _STATES.IDLE, to = _STATES.COMPLETE },

            { name = _EVENTS.INIT_SUCC, from = _STATES.IDLE},
            { name = _EVENTS.INIT_SUCC, from = _STATES.STOPPED },
            { name = _EVENTS.INIT_SUCC, from = _STATES.COMPLETE },

            { name = _EVENTS.START_DOWNLOAD, from = _STATES.IDLE, to = _STATES.DOWNLOADING },
            { name = _EVENTS.START_DOWNLOAD, from = _STATES.STOPPED, to = _STATES.DOWNLOADING },
            { name = _EVENTS.START_DOWNLOAD, from = _STATES.COMPLETE, to = _STATES.DOWNLOADING },

            { name = _EVENTS.RESUME_DOWNLOAD, from = _STATES.STOPPED, to = _STATES.DOWNLOADING },

            { name = _EVENTS.STOP_DOWNLOAD, from = _STATES.IDLE, to = _STATES.STOPPED },
            { name = _EVENTS.STOP_DOWNLOAD, from = _STATES.STOPPED, to = _STATES.STOPPED },
            { name = _EVENTS.STOP_DOWNLOAD, from = _STATES.DOWNLOADING, to = _STATES.STOPPED },
            { name = _EVENTS.STOP_DOWNLOAD, from = _STATES.COMPLETE, to = _STATES.STOPPED },
            -- 同上
            --{ name = _EVENTS.RESET_DOWNLOAD, from = {_STATES.PAUSED, _STATES.DOWNLOADING, _STATES.COMPLETE}, to = _STATES.UNDEFINED },
            { name = _EVENTS.RESET_DOWNLOAD, from = _STATES.STOPPED, to = _STATES.IDLE },
            { name = _EVENTS.RESET_DOWNLOAD, from = _STATES.DOWNLOADING, to = _STATES.IDLE },
            { name = _EVENTS.RESET_DOWNLOAD, from = _STATES.COMPLETE, to = _STATES.IDLE },
            { name = _EVENTS.RESET_DOWNLOAD, from = _STATES.IDLE, to = _STATES.DOWNLOADING },

            { name = _EVENTS.REMOVE_DOWNLOAD, from = _STATES.IDLE, to = _STATES.IDLE },
            { name = _EVENTS.REMOVE_DOWNLOAD, from = _STATES.STOPPED, to = _STATES.IDLE },
            { name = _EVENTS.REMOVE_DOWNLOAD, from = _STATES.DOWNLOADING, to = _STATES.IDLE },
            { name = _EVENTS.REMOVE_DOWNLOAD, from = _STATES.COMPLETE, to = _STATES.IDLE }
        },

        callbacks = fsm_callbacks
    })

    params = params or {}
    local _init_check_params = params.init_check_params or {}
    local _file_dest_info = params.file_dest_info
    self._data = {
        initted = false,
        model_name = _model_instance:get_model_name(),
        task_id = _task_id,
        tag = _file_ext and _file_ext.tag or _task_id,
        max_retry_times = _opts and _opts.max_retry_times or nil,
        progress_notify_interval_millis = _opts and _opts.progress_notify_interval_millis or nil,
        use_independent_pool = nil,
        url = _url,
        name = _file_dest_info.name,
        dest_file_dir = _file_dest_info.dest_file_dir,
        dest_file_path = _file_dest_info.dest_file_path,
        temp_file_path = nil,
        current_retry_times = 0,
        download_begin_time = 0,
        file_ext = _file_ext,
        opts = _opts,
        enable_download_range = _opts and _opts.enable_download_range,
        enable_limit_speed = _opts and _opts.enable_limit_speed,
        priority = _opts and _opts.priority or nil,
        disable_deepcopy_result = _opts and _opts.disable_deepcopy_result or false,
        download_state_listener = params.download_state_listener,
        download_progress_listener = params.download_progress_listener,
        download_state = {
            state = _STATES.IDLE,
            tag = _file_ext and _file_ext.tag or _task_id,
            url = _url,
            file_path = _file_dest_info.dest_file_path,
            size = _file_ext and _file_ext.size or 0,
            recv_bytes = 0,
            err_code = 0,
            err_msg = 0,
            percent = -1, -- 0也需要更新给游戏，所以默认值为-1
            duration = 0,
            task_id = _task_id,
            speed = 0
        },
        download_fsm = _download_fsm,
        model_instance = _model_instance,
        debug_enable = _model_instance:get_global_config().debug_enable,
        init_check_params = _init_check_params,
        file_dest_info = _file_dest_info,
        invoker_managed_md5_data = false -- 外部是否管理了md5，默认为false
    }

    if _opts and type(_opts.use_independent_pool) == "boolean" then
        self._data.use_independent_pool = _opts.use_independent_pool
    end

    -- 准备临时下载目录和文件路径
    local temp_file_path
    if _init_check_params[M.TASK_INIT_PARAMS.FILE_TEMP_PATH] then
        temp_file_path = _init_check_params[M.TASK_INIT_PARAMS.FILE_TEMP_PATH]
    else
        temp_file_path = M.static_get_download_temp_file_path(_model_instance, _file_dest_info.dest_file_dir, _file_dest_info.name)
    end
    self._data.temp_file_path = temp_file_path
    self._data.download_state.temp_file_path = temp_file_path

    -- check outside own the md5
    local outside_local_info = _init_check_params[M.TASK_INIT_PARAMS.LOCAL_INFO]
    self._data.invoker_managed_md5_data = outside_local_info and outside_local_info[M.TASK_INIT_PARAMS.LOCAL_MD5] ~= nil

    self:log_debug("_init begin, task_id:" .. tostring(_task_id) .. ", url:" .. tostring(_url) .. ", file_name:" .. tostring(self._data.name) .. ", dest_path:" .. tostring(self._data.dest_file_dir) .. ", dest_file_path:" .. tostring(self._data.dest_file_path) .. ", outside managed md5:" .. tostring(self._data.invoker_managed_md5_data))
    -- init download
    self:_fsm_equeue_event_at_front(_EVENTS.INIT)
end

function M:start_download()
    assert(self, "call start_download missing ':' mark!")

    self:log_debug("start_download invoke received begin:" .. tostring(self._data.download_fsm.current))
    self:_fsm_enqueue_event(_EVENTS.START_DOWNLOAD)
end

function M:reset_download()
    assert(self, "call reset_download missing ':' mark!")

    self:log_debug("reset_download invoke received begin:" .. tostring(self._data.download_fsm.current))
    self:_fsm_enqueue_event(_EVENTS.RESET_DOWNLOAD)
end

function M:stop_download(cb)
    assert(self, "call stop_download missing ':' mark!")

    self:log_debug("stop_download invoke received begin:" .. tostring(self._data.download_fsm.current))
    self:_fsm_enqueue_event(_EVENTS.STOP_DOWNLOAD, function(succ, ...)
        if succ then
            self:log_debug("stop_download succ")
        else
            local code, msg = ...
            self:log_debug("stop_download failed, code:" .. tostring(code) .. ", msg:" .. tostring(msg))
        end

        if cb then
            cb(succ, ...)
        end
    end)
end

function M:remove_download(cb)
    assert(self, "call remove_download missing ':' mark!")

    self:log_debug("remove_download invoke begin")
    self:_fsm_enqueue_event(_EVENTS.REMOVE_DOWNLOAD, function(succ, ...)
        if succ then
            self:log_debug("remove_download succ")
        else
            local code, msg = ...
            self:log_debug("remove_download failed, code:" .. tostring(code) .. ", msg:" .. tostring(msg))
        end

        if cb then
            cb(succ, ...)
        end
    end)
end

function M:get_download_state(no_copy)
    if not no_copy then
        local state_obj = UTILS.deepcopy(self._data.download_state)
        state_obj[M.STATE_KEY.STATE_CHANGED] = nil
        return state_obj
    else
        return self._data.download_state
    end
end

function M:task_id()
    if not self then
        return nil
    end

    return self._data.task_id
end

-- 获取task 别名，如果游戏没有设置别名，则使用内部生成的task_id
function M:task_tag_name()
    if not self then
        return nil
    end

    return self._data.tag
end

function M:task_info()
    if not self then
        return nil
    end

    return {
        task_id = self._data.task_id,
        tag = self._data.tag,
        url = self._data.url,
        dest_file_path = self._data.dest_file_path,
        temp_file_path = self._data.temp_file_path,
        download_state = self:get_download_state()
    }
end

function M:is_downloading()
    return self._data.download_state.state == _STATES.DOWNLOADING
end

return M