---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liujin.
--- DateTime: 2019/6/5 7:21 PM
---

local E = require "ejoysdk_lua.ejoysdk"
local EV = require 'ejoysdk_lua.ejoysdk_vendors'
local UNI = require "ejoysdk_lua.vendors.unisdk"
local JSON = require 'ejoysdk_lua.ejoysdk_json'
local EM = require "ejoysdk_lua.ejoysdk_module"
local Constants = require "ejoysdk_lua.ejoysdk_constants"

--目标平台是否支持
local SYNC_IS_PLATFORM_SUPPORT = 'SYNC_IS_PLATFORM_SUPPORT'

--分享操作action
local ASYNC_SHARE_TO_PLATFORM  = 'ASYNC_SHARE_TO_PLATFORM'

--系统分享操作action
local ASYNC_SHARE_TO_SYSTEM = 'SHARE_TO_SYSTEM'

--安卓系统分享app
local ASYNC_SHARE_TO_APP = 'SHARE_TO_APP'

--邀请操作action
local ASYNC_INVITE_TO_PLATFORM  = 'ASYNC_INVITE_TO_PLATFORM'

--邀请
local INTERNAL_EVENT = {
    EVT_FACEBOOK_GAMEREQUEST_PULLUP = 'EVT_FACEBOOK_GAMEREQUEST_PULLUP'
}

local TAG = EM.MODULE.SOCIAL .. 'social'

local FB_VENDOR_NAME = 'FB'
local UM_VENDOR_NAME = 'UMENG'
local TW_VENDOR_NAME = 'TWITTER_LOGIN'
local LINE_VENDOR_NAME = 'LINE'
local INSTAGRAM_VENDOR_NAME = 'INSTAGRAM'
local WHATSAPP_VENDOR_NAME = 'WHATSAPP'
local KAKAOTALK_VENDOR_NAME = 'KAKAOTALK'
local ZALO_VENDOR_NAME = 'ZALO'

local SYSTEM_VENDOR_NAME = 'SYSTEM'

local local_pullup_listener;

local M = {}


--分享的目标平台
M.SHARE_PLATFORM = {
    --分享到facebook时间线
    facebook_share_timeline  = 'facebook_share_timeline',
    --分享到facebook messenger 好友
    facebook_share_messenger = 'facebook_share_messenger',
    --分享到微信 好友
    wechat_share_messenger = 'wechat_share_messenger',
    --分享到微信 朋友圈
    wechat_share_timeline = 'wechat_share_timeline',
    --分享到QQ 好友
    qq_share_messenger = 'qq_share_messenger',
    --分享到QQ 空间
    qq_share_qzone = 'qq_share_qzone',
    --分享到新浪微博
    sina_share_weibo = 'sina_share_weibo',

    --分享到twitter，推文
    twitter_share_timeline = 'twitter_share_timeline',
    --分享到更多其他系统应用
    twitter_share_more = 'twitter_share_more',
    --系统分享
    system_share = 'system_share',
    --分享到Line好友
    line_share_messenger = 'line_share_messenger',
    -- 分享到 Instagram 快拍
    instagram_share_story = 'instagram_share_story',
    -- 分享到 Instagram 动态
    instagram_share_timeline = 'instagram_share_timeline',
    -- 分享到 whatsapp
    whatsapp_share = 'whatsapp_share',
    -- 分享到zalo(越南)
    zalo_share = 'zalo_share',

    -- 分享到Kakaotalk的消息对话
    kakaotalk_share_messenger = 'kakaotalk_share_messenger',

    -- 拉起微信小程序
    wx_mini_program = 'wx_mini_program',

    --分享到微信 好友（走系统分享）
    wechat_share_messenger_v2 = 'wechat_share_messenger_v2',
    --分享到微信 朋友圈（走系统分享）
    wechat_share_timeline_v2 = 'wechat_share_timeline_v2'
}

--邀请的目标平台
M.INVITE_PLATFORM = {
    --facebook 游戏邀请
    facebook_invite_gamerequest  = 'facebook_invite_gamerequest',
}

-- 微信小程序类型：开发版test，体验版preview 和正式版release
M.MINI_PROGRAM_TYPE = {
    release = 'release',
    preview = 'preview',
    test = 'test'
}

M.WHITE_LIST = {

    -- Android微信包名
    android_weixin_package_name = 'com.tencent.mm',
    -- Android分享到聊天activity
    android_weixin_share_friend_activity = 'com.tencent.mm.ui.tools.ShareImgUI',
    -- Android分享到朋友圈activity
    android_weixin_share_timeline_activity = 'com.tencent.mm.ui.tools.ShareToTimeLineUI',

    -- iOS微信包名
    ios_weixin_package_name = 'com.tencent.xin.sharetimeline'
}


local platform_vendor = {
        facebook_share_timeline = FB_VENDOR_NAME,
        facebook_share_messenger = FB_VENDOR_NAME,
        facebook_invite_gamerequest = FB_VENDOR_NAME,
        --分享到微信 好友
        wechat_share_messenger = UM_VENDOR_NAME,
        --分享到微信 朋友圈
        wechat_share_timeline = UM_VENDOR_NAME,
        --分享到QQ 好友
        qq_share_messenger = UM_VENDOR_NAME,
        --分享到QQ 空间
        qq_share_qzone = UM_VENDOR_NAME,
        --分享到新浪微博
        sina_share_weibo = UM_VENDOR_NAME,

        --分享到twitter，TW_VENDOR_NAME 或使用友盟分享
        twitter_share_timeline = TW_VENDOR_NAME,
        twitter_share_more = TW_VENDOR_NAME,
        system_share = SYSTEM_VENDOR_NAME,
        line_share_messenger = LINE_VENDOR_NAME,
        instagram_share_story = INSTAGRAM_VENDOR_NAME,
        instagram_share_timeline = INSTAGRAM_VENDOR_NAME,
        whatsapp_share = WHATSAPP_VENDOR_NAME,
        kakaotalk_share_messenger = KAKAOTALK_VENDOR_NAME,
        zalo_share = ZALO_VENDOR_NAME,

        wx_mini_program = UM_VENDOR_NAME,

        wechat_share_messenger_v2 = SYSTEM_VENDOR_NAME,
        wechat_share_timeline_v2 = SYSTEM_VENDOR_NAME

}

local fill_weixin_system_share_params = function(platform, params)
    if platform == M.SHARE_PLATFORM.wechat_share_messenger_v2 then
        if _ejoysdk.os() == 'android' then
            params['package_name'] = M.WHITE_LIST.android_weixin_package_name
            params['package_activity_name'] = M.WHITE_LIST.android_weixin_share_friend_activity
        elseif _ejoysdk.os() == 'ios' then
            local white_list = {
                M.WHITE_LIST.ios_weixin_package_name
            }
            params['ios_white_list'] = white_list
        end
    elseif platform == M.SHARE_PLATFORM.wechat_share_timeline_v2 then
        if _ejoysdk.os() == 'android' then
            params['package_name'] = M.WHITE_LIST.android_weixin_package_name
            params['package_activity_name'] = M.WHITE_LIST.android_weixin_share_timeline_activity
        elseif _ejoysdk.os() == 'ios' then
            local white_list = {
                M.WHITE_LIST.ios_weixin_package_name
            }
            params['ios_white_list'] = white_list
        end
    end
end

local is_local_path = function(url)
    if url then
        local prefix = string.sub(url, 1, 4)
        return string.lower(prefix) ~= 'http'
    end
    return false
end

-- 兼容分享参数里面本地路径不同的前缀，系统分享是'/'，友盟分享是'file:///'
--  iOS不用做这个判断，native层做了兼容，如果本地路径的图片不存在，会保留为空对象
local is_file_exists = function(path)
    if not path then
        return false
    end
    local file_exists = true
    if _ejoysdk.os() == "android" then
        local prefix = string.sub(path, 1, 7)
        if prefix == 'file://' then
            path = string.sub(path, 8, path.length)
        end
        _ejoysdk.log('check file path >> ' .. tostring(path))
        local file = io.open(path, "rb")
        file_exists = file ~= nil
        if file_exists then
            file:close()
        end
    end
    return file_exists
end

local check_params_if_invalid = function(params)
    for k, v in pairs(params) do
        if k == 'media' then
            for _, media in pairs(v) do
                local type = media['type']
                local data = media['data']
                if (type == 'image_url' or type == 'file_path') and is_local_path(data) then
                    local exists = is_file_exists(data)
                    if not exists then
                        return true, Constants.SHARE_ERROR_CODES.INVALID_PARAMETER, 'local path file is not exist'
                    end
                end
            end
        end
    end
    return false
end

local need_request_image_file = function(platform, params)
    local need_request_image_file_flag = false
    local medias = params.media
    if platform == M.SHARE_PLATFORM.facebook_share_timeline
            or platform == M.SHARE_PLATFORM.facebook_share_messenger
            or platform == M.SHARE_PLATFORM.line_share_messenger
            or platform == M.SHARE_PLATFORM.instagram_share_story
            or platform == M.SHARE_PLATFORM.instagram_share_timeline
            or platform == M.SHARE_PLATFORM.whatsapp_share
            or platform == M.SHARE_PLATFORM.twitter_share_more
            or platform == M.SHARE_PLATFORM.twitter_share_timeline
            or platform == M.SHARE_PLATFORM.zalo_share
            or platform == M.SHARE_PLATFORM.system_share
            or platform == M.SHARE_PLATFORM.wechat_share_messenger_v2
            or platform == M.SHARE_PLATFORM.wechat_share_timeline_v2 then
        --只支持下一张图，目前需要下载的也只有一张
        if type(medias) == 'table' and #medias == 1 then
            local media = medias[1] or {}
            local media_type = media.type
            if (media_type == 'image_url' or media_type == 'file_path') and type(media.data) == 'string'  and string.sub(media.data, 1, 4) == 'http' then
                need_request_image_file_flag = true
            end
        end
    end
    return need_request_image_file_flag
end

local try_request_image_file = function(params, cb)
    --下载图片
    local media = params.media[1]
    local url = media.data
    local EMM = require "ejoysdk_lua.res.ejoy_res_model_factory"
    local DM = require "ejoysdk_lua.res.model.ejoy_http_download_model"
    local http_res_model = EMM.get_http_res_model("ejoysdk_social")
    local task, _err_code, _err_msg = http_res_model:create_task(url, {}, {}, function(_state, state_obj)
        -- 监听下载状态
        if _state == DM.DOWNLOAD_STATE.COMPLETE then
            local img_path = state_obj.file_path
            E.LOG.debug(TAG, "image download succ")
            -- media.data值改为下载后的地址
            media.data = img_path
            cb(true)
        elseif _state == DM.DOWNLOAD_STATE.FAILED then
            E.LOG.debug(TAG, "image download fail")
            cb(false, Constants.SHARE_ERROR_CODES.DOWNLOAD_FAILED, 'download image failed')
        end
    end)
    if task ~= nil then
        task:start_download()
    else
        E.LOG.debug(TAG, "image download fail, task create fail")
        cb(false, Constants.SHARE_ERROR_CODES.DOWNLOAD_CREATE_TASK_FAILED, 'download image fail, create task failed')
    end
end


function M.register_pullup_listener(pullup_listener)
    E.LOG.debug(TAG, 'social register_pullup_listener')
    local first_init = false
    if pullup_listener then
        if local_pullup_listener == nil then
            first_init = true
        end

        local_pullup_listener = pullup_listener
    end

    if first_init then
        local result = {}
        UNI.register_event_cb(FB_VENDOR_NAME, function(type, body)
            if type == INTERNAL_EVENT.EVT_FACEBOOK_GAMEREQUEST_PULLUP then
                result.pullup_platform = M.INVITE_PLATFORM.facebook_invite_gamerequest
                result.data = body;
                E.LOG.debug(TAG, "social receive facebook gamerequest pullup!")
                E.LOG.debug(TAG, body)
                local_pullup_listener(result)
            end
        end)
    end
end

-- 社交平台是否支持
function M.is_support(platform)
    local vendor_name = platform_vendor[platform]
    local vendor = EV.get(vendor_name)
    if vendor and vendor:is_support_ability({EV.ABILITY.SHARE}) then
        return vendor.is_share_support()
    end

    local param = {
        platform = platform
    }
    local ret = UNI.sync_call(vendor_name, SYNC_IS_PLATFORM_SUPPORT, param, nil)
    local is_support = (ret and ret['support']) or false
    if _ejoysdk.os() == 'ios' and (vendor == SYSTEM_VENDOR_NAME or vendor_name == SYSTEM_VENDOR_NAME) then
        -- is_support = true -- 仅iOS特有，必然支持
        if (platform == M.SHARE_PLATFORM.wechat_share_messenger_v2 or platform == M.SHARE_PLATFORM.wechat_share_timeline_v2) then
            is_support = E.Sysinfo.is_app_install('weixin://')
        else
            is_support = true
        end
    end
    if _ejoysdk.os() == 'android' and (platform == M.SHARE_PLATFORM.wechat_share_messenger_v2
            or platform == M.SHARE_PLATFORM.wechat_share_timeline_v2) then
        -- 如果没有安装微信的话，返回false
        is_support = E.Sysinfo.is_app_install(M.WHITE_LIST.android_weixin_package_name)
    end
    if is_support then
        E.LOG.debug(TAG, "is support: " .. tostring(platform))
    else
        E.LOG.debug(TAG, "is not support: ".. tostring(platform))
    end

    return is_support
end

-- support方法返回的support类型可能是bool可能是table，v2这里做一次封装
function M.is_support_v2(platform)
    local support = M.is_support(platform)
    local is_support_share = false
    local support_type = type(support)
    if support_type == 'boolean' then
        -- 如果返回数据是boolean值，直接取值是否支持分享
        is_support_share = support
    elseif support_type == 'table' then
        -- 如果返回数据是table值，判断 (has_installed and has_share_infos)
        local has_installed  = support.has_installed or false
        local has_share_infos = support.has_share_infos or false
        is_support_share = has_installed and has_share_infos
    end
    return is_support_share
end

local function share_to_system(param, cb)
    if _ejoysdk.os() =='android' then
        local media_url
        local type
        if param.media and param.media[1] then
            media_url = param.media[1].data
            type = param.media[1].type
        end
        local share_to_app_params = {
            message = param.message,
            package_name = param.package_name,
            package_activity_name = param.package_activity_name,
            type = type
        }
        if type == 'image_url' then
            share_to_app_params.image_url = media_url
        elseif type == 'file_path' then
            share_to_app_params.file_path = media_url
        end

        E.async_call(ASYNC_SHARE_TO_APP, share_to_app_params, nil, cb)
    elseif _ejoysdk.os() == 'ios' then
        E.async_call(ASYNC_SHARE_TO_SYSTEM, function(info)
            cb(JSON.decode(info))
        end , JSON.encode(param))
    elseif  _ejoysdk.os() == 'windows' then
        local media_url
        local type
        if param.media and param.media[1] then
            media_url = param.media[1].data
            type = param.media[1].type
        end
        -- Windows端分享文件用另存为文件处理
            local info = {}
        if _ejoysdk.saveasfile and type == 'file_path'  then
            local result = _ejoysdk.saveasfile(media_url)
            E.LOG.debug(TAG, "share_to_system window result=" .. result)
            info.succ = (result == 0)
            info.code = result;
            cb(info)
        else
            E.LOG.debug(TAG, "share_to_system window not support")
            info.succ = false
            cb(info)
        end
    end
end

-- 分享
function M.share(platform, param, callback)
    E.LOG.tips(TAG, 'If you get a share error')
    local is_invalid, code, msg = check_params_if_invalid(param)
    if is_invalid then
        callback(false, code, msg)
        return
    end
    local vendor_name = platform_vendor[platform]
    param['platform'] = platform

    -- 将二进制图片数据拼接
    local index = 0
    local image_datas = {}
    for k, v in pairs(param) do
        if k == 'media' then
            for _, media in pairs(v) do
                local type=media['type']
                local media_data
                if type == 'image_b64' then
                    media_data = _ejoysdk_crypt.base64decode(media['data'])
                else
                    if type == 'image_data' then
                        media_data = media['data']
                    end
                end

                if (media_data) then
                    table.insert(image_datas, media_data)

                    local len = #media_data
                    media['type'] = 'image_chunk'
                    media['data'] = {
                        index  = index,
                        length = len
                    }

                    index = index + len;
                end
            end
        end
    end

    local chunk_data = table.concat(image_datas)

    local share_wrapper = function(cb)
        local need_request_image_file_flag = need_request_image_file(platform, param)
        if need_request_image_file_flag then
            try_request_image_file(param, function(succ, ...)
                if succ then
                    cb()
                else
                    local request_img_code, request_img_msg = ...
                    callback(false, request_img_code, request_img_msg)
                end
            end)
        else
            --不需要下载图片，直接执行分享
            cb()
        end
    end

    share_wrapper(function()
        if vendor_name == SYSTEM_VENDOR_NAME then
            fill_weixin_system_share_params(platform, param)
            local cb = function(info)
                if info.succ then
                    callback(true)
                else
                    --错误码三端native未统一，lua层封装
                    -- Android：info.message，iOS：nil，Windows：info.code
                    local temp_code = (info.code or 0)
                    local temp_msg =  (info.msg or info.message or '')
                    callback(false, temp_code, temp_msg)
                    E.LOG.error(TAG, 'share fail, code is ' .. tostring(temp_code) .. ', msg is ' .. tostring(temp_msg))
                end
            end
            share_to_system(param, cb)
        else
            local vendor = EV.get(vendor_name)
            if vendor and vendor:is_support_ability({EV.ABILITY.SHARE}) then
                vendor.share(param, chunk_data, callback)
            else
                UNI.async_call(vendor_name, ASYNC_SHARE_TO_PLATFORM, param, chunk_data, function(succ, ...)
                    if succ then
                        local body = ...
                        callback(true, body)
                    else
                        local _, body = ...
                        E.LOG.error(TAG, 'share fail, code is ' .. tostring(body.error_code) .. ', msg is ' .. tostring(body.error_msg))
                        callback(false, body.error_code, body.error_msg)
                    end
                end)
            end
        end
    end)
end

-- 游戏邀请接口
-- @param platform: string类型，需要使用的邀请平台，参考INVITE_PLATFORM定义的常量值
-- @param param: table类型，包含title, message, data
--   @title: 邀请通知显示的标题
--   @message：邀请通知显示的内容
--   @data: 自定义附加的自由格式的数据，最大长度为255个字符。用于传递邀战等场景的房间信息等
function M.invite(platform, param, callback)
    local vendor = platform_vendor[platform]
    param['platform'] = platform

    local cb = function(succ, ...)
        if succ then
            local body = ...
            callback(true, body)
        else
            local _, body = ...
            callback(false, body.error_code, body.error_msg)
        end
    end

    UNI.async_call(vendor, ASYNC_INVITE_TO_PLATFORM, param, nil, cb)
end


return M