---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ligs.
--- DateTime: 2020-07-04 16:59
---

local E = require "ejoysdk_lua.ejoysdk"
local launcher = require 'ejoysdk_lua.ejoysdk_launcher'
local gangplank = require 'ejoysdk_lua.ejoysdk_gangplank'
local USER = require 'ejoysdk_lua.user_center.ejoysdk_usercenter'
local EAM = require 'ejoysdk_lua.agreement.ejoysdk_agreement'
local LUTIL = require 'ejoysdk_lua.native.utils.Utils'
local ECS = require 'ejoysdk_lua.custom.ejoysdk_custom_service'
local EM = require "ejoysdk_lua.ejoysdk_module"
local M = {}
--local logout_callback
local ticket

local TAG = EM.MODULE.NATIVE .. 'core.login'

local function get_ticket(cb)
    if (ticket and string.len(ticket) > 0) then
        cb(ticket)
    else
        launcher.server_list_ticket(function(succ, ...)
            if succ then
                local hash, _time = ...
                ticket = hash
                cb(ticket)
            else
                cb(nil)
            end
        end)
    end
end

-- 获取服务器列表
function M.get_server_list(cb)
    -- https://yuque.antfin-inc.com/ejoy-platform/user_guide/wiwha9#29970154
    get_ticket(function(ret_ticket)
        if (ret_ticket and string.len(ret_ticket) > 0) then
            launcher.server_list_detail(ret_ticket, function(succ, server_list)
                if succ then
                    LUTIL.notify(cb, true, "获取服务器列表成功", server_list)
                else
                    LUTIL.notify(cb, false, "获取列表失败")
                end
            end)
        else
            LUTIL.notify(cb, false, "ticket获取失败")
        end
    end)
end

-- 获取公告
function M.get_anns(cb)
    -- https://yuque.antfin-inc.com/ejoy-platform/user_guide/wiwha9#adf850a7
    get_ticket(function(ret_ticket)
        if (ret_ticket and string.len(ret_ticket) > 0) then
            launcher.ticket_detail("login", nil, nil, function(succ, anns)
                if succ then
                    -- 获取公告内容成功, anns为包含公告内容的json字符串
                    LUTIL.notify(cb, true, "获取公告成功", anns)
                else
                    -- 获取公告ticket失败
                    LUTIL.notify(cb, false, "获取公告失败")
                end
            end)
        else
            LUTIL.notify(cb, false, "ticket获取失败")
        end
    end)
end

-- 登录
function M.login(params)
    params = params or {}
    local vendor_name = params.login_vendor
    gangplank.acquire_token(vendor_name)
end

-- 进入游戏
function M.enter_game(params)
    params = params or {}
    local token = params.token or gangplank.user_info().token
    local login_server = params.login_server

    if token and '' ~= token then
        gangplank.login_with_token(login_server, token)
    end
end

function M.open_user_center(params)
    params = params or {}
    local vendor_name = params.vendor
    gangplank.open_user_center(vendor_name)
    return LUTIL.notify_resp(true)
end

function M.open_custom_service(params, cb)
    params = params or {}
    ECS.show_custom_service(params, function(succ, ...)
        if succ then
            LUTIL.notify(cb, true, '成功')
        else
            local code, msg = ...
            LUTIL.notify(cb, code, msg)
        end
    end)
end

function M.show_userinfo_completion(params, cb)
    -- 有可能不传params
    if type(params) == 'function' then
        cb = params
        params = {}
    end

    params = params or {}
    gangplank.open_userinfo_completion(params.vendor, function(succ)
        LUTIL.notify(cb, succ, '')
    end)
end

-- 适用于进入游戏的场景
function M.set_player_info(player_info)
    gangplank.set_player_info(player_info, "enterGame")
end

-- 登出
function M.logout()
    gangplank.logout()
end

function M.user_info()

    local gangplank_user_info = gangplank.user_info()
    if gangplank_user_info then
        if USER.user_info() and USER.user_info().token and string.len(USER.user_info().token) then
            gangplank_user_info['usercenter_token'] = USER.user_info().token
        end
    end

    return LUTIL.notify_resp(true, '', gangplank_user_info or {})

    --notify(cb, 200, "", gangplank_user_info)
end

function M.sdk_info()
    local INIT = require "ejoysdk_lua.native.core.init"
    return LUTIL.notify_resp(true, '', INIT.get_opts())
end

M.show_agreement = EAM.show_agreement

-- tests for demo
M.analog_enter_game = function(player_id, player_name, game_server, cb)
    local analog = require 'sdk_test.analog'
    analog.login(player_id, function(succ)
        if succ then
            E.LOG.debug(TAG, '进入游戏成功')
            local player_info = {
                player_id = player_id,
                player_name = player_name,
                server_id = game_server
            }
            E.LOG.debug(TAG, player_info)
            LUTIL.notify(cb, true, '获取角色成功: ' .. player_name)
            gangplank.set_player_info(player_info, "enterGame")
        else
            LUTIL.notify(cb, false, '进入游戏失败')
        end
    end)
end

M.anlog_login_game = function(params, cb)
    local analog = require 'sdk_test.analog'
    local game_token = params.game_token
    local game_server = params.game_server
    local player_name = params.player_name
    analog.init(game_token)

    analog.create_player(game_server, player_name, function(succ, player_id)
        if succ then
            M.analog_enter_game(player_id, player_name, game_server, cb)
        else
            LUTIL.notify(cb, false, '创建角色失败') --创角失败都认为是登录成功
        end
    end)
end
return M