---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ligs.
--- DateTime: 2020-07-04 16:59
---
--local E = require 'ejoysdk_lua.ejoysdk'
local gangplank = require 'ejoysdk_lua.ejoysdk_gangplank'
local LUTIL = require 'ejoysdk_lua.native.utils.Utils'
local EM = require "ejoysdk_lua.ejoysdk_module"
local pay_callback
local M = {}

local _TAG = EM.MODULE.NATIVE .. 'core.pay'

function M.pay(params, cb)
    pay_callback = cb

    local product_id = params.product_id
    local vendor_name = params.pay_vendor
    local ext = params.ext or {}
    local count = params.count

    -- 自定义实现年龄输入
    --ext.pay_limit_age_cb = function(rules, input)
        --DO SOMETHING
        --input({area='jp',birthday='20100601'})
        --input({})
        --input({area='jp'})
        --input({birthday='234234'})
        --input()
    --end

    --ext.pay_limit_custom_err = true -- 自定义错误页时打开

    gangplank.pay(vendor_name, product_id, count, ext)
end

--获取商品信息
function M.get_product_list(params, cb)
    local vendor_name = params.pay_vendor
    gangplank.get_product_list(vendor_name, function(succ, ...)
        if succ then
            local products = ...
            LUTIL.notify(cb, true, "获取商品列表成功", products)
        else
            local code = ...
            LUTIL.notify(cb, false, "获取商品列表失败,code:" .. code, nil)
        end
    end)
end

M.pay_listener = function(succ, ...)
    if succ then
        local orderId, _ext = ...
        LUTIL.notify(pay_callback, true, '支付成功', { orderId = orderId })
    else
        local orderId, code, msg, ext = ...
        ext = ext or {}
        LUTIL.notify(pay_callback, false, '支付失败, code: ' .. code .. " ,msg: " .. msg, { order_id = orderId, code = code, msg = msg, ext = ext })
    end
end

return M