---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pangang.
--- DateTime: 2019/8/30 上午10:10
---
local ET = require "ejoysdk_lua.ejoysdk_topic"
local E = require "ejoysdk_lua.ejoysdk"
local USER = require 'ejoysdk_lua.user_center.ejoysdk_usercenter'
local EM = require "ejoysdk_lua.ejoysdk_module"
local _agreement_log = require 'ejoysdk_lua.ejoysdk_log_mgr'
local ESTAT = require 'ejoysdk_lua.ejoysdk_stat'

local TAG =  EM.MODULE.AGREEMENT .. 'agreement'

local AGREEMENT_SERVICE = {
    agreement_for_sign = '/policy/eurl_sign',
    agreement_for_view = '/policy/eurl'
}

local agree_result = {
    result = false,
    url_version = 0,
}
local agree_callback = nil
local agree_ejoy_token = nil

local M = {}
--用户需要签署用户协议
M.ERR_CODE_REJECT_FOR_AGREEMENT = 421

local function stat_action(action, type, result, params)
    local _params = params or {}
    _params[ESTAT.STAT_KEY.IS_PRIORITY_HIGH] = true
    ESTAT.stat_action(action, type, result, _params)
end

local function get_agreement_url(service)
    local holo_url_base = E.CONFIG.get_config('holo')
    return holo_url_base .. service
end

local function open_url(service, screen_orientation,params)
    if E.WebView.is_opened() then
        E.Timer.once(1, function()
            open_url(service, screen_orientation,params)
        end)
        return
    end

    local url = get_agreement_url(service)
    url = url .. '?language=' .. E.CONFIG.get_config('lang')

    --params = params or {}
    --params.area = E.CONFIG.get_config(E.CONFIG.KEY.PUBLISH_AREA)
    --params.channel = E.get_channel()
    local publish_area = E.CONFIG.get_config(E.CONFIG.KEY.PUBLISH_AREA)
    if(publish_area and publish_area ~= '')then
       url = url .. '&area='..publish_area
    end

    local channel_id = E.get_channel()
    if(channel_id and channel_id ~= '') then
        url = url .. '&channel='..channel_id
    end

    local user_info = USER.user_info()
    local country = (((user_info or {}).location or {}).userLocation or {}).country
    if(country and country ~= '') then
        url = url .. '&user_location=' .. country
    end

    local pkg_name = E.get_pkg_info().pkg_name
    if (pkg_name and pkg_name ~= '') then
        url = url .. '&pkg_name=' .. pkg_name
    end

    if(params and type(params)=='table')then
        local query = E.HTTP.urlencode2(params)

        if query and query ~= '' then
            url = url .. '&' .. query
        end
    end

    E.LOG.debug(TAG,"agreement_url: "..url)

    local options = {
        ['.ejoy.com'] = {
            transparent = true
        }
    }
    local server_domain = E.CONFIG.get_config(E.CONFIG.KEY.SERVER_DOMAIN)
    if server_domain and server_domain ~= '' then
        options[server_domain] = {
            transparent = true
        }
    end

    E.WebView.open(url, options,
            {
                compactMode = true,
                use_cutout = true,
                screen_orientation = screen_orientation
            })
end

local function show_agreement_webview(service, screen_orientation,params)

    E.WebView.closing_agreement_callback = nil
    if E.WebView.is_opened() then
        E.WebView.close() -- FIXME 目前只允许打开一个页面，必须先提前关闭, 关闭事件是异步的，这个文件里也会收到关闭的通知
        E.WebView.closing_agreement_callback = function()
            open_url(service, screen_orientation,params)
        end
    else
        open_url(service, screen_orientation,params)
    end

end

--打开用户协议页面，可以设置屏幕方向
function M.show_agreement(screen_orientation,params)
    show_agreement_webview(AGREEMENT_SERVICE.agreement_for_view, screen_orientation,params)
end

local function webview_js_callback(_value)
    E.LOG.debug(TAG, "webview_js_callback receive agreement_result event!")
    local args = _value.args
    if args.type == 'agreement_result' then
        agree_result.result = args.result
        agree_result.url_version = args.version
        -- stat agreement result
        stat_action("ejoy_agreement_result", agree_result.url_version, agree_result.result)

        E.LOG.debug(TAG,"webview_js_callback receive agreement_result:")
        E.LOG.debug(TAG, args)

        ET.unsubscribe('webview_jsargs', webview_js_callback)

        E.WebView.close()
    end
end

local function request_agree_eurl(agree_h5_ver, ejoy_token, cb)
    local eg = require 'ejoysdk_lua.ejoysdk_gangplank'
    local url = eg.gangplank_logined_url('/eurl_signed', '2')
    E.LOG.debug(TAG, 'request agree begin: ' .. tostring(url))
    local params = {}
    params["version"] = tostring(agree_h5_ver)
    params["pkg_info"] = E.get_pkg_info()
    local user_info = USER.user_info()
    if user_info and user_info.location then
        params["location_info"] = user_info.location
    end

    local headers = {
        acceptable = E.HTTP.CT_JSON,
        headers = { ['ejoy-token'] = ejoy_token }
    }

    E.HTTP.post(
            url,
            headers,
            E.HTTP.CT_JSON,
            params,
            function(resp)
                if resp.status == 200 then
                    if resp.body.code == 0 then
                        cb(true)
                    else
                        cb(false, resp.body.code, resp.body.message)
                    end
                else
                    cb(false, resp.status, 'http error')
                end
            end
    )
end

local function webview_close_callback(_value)
    E.LOG.debug(TAG, "listen_webview_close_event")
    if E.WebView.closing_agreement_callback and type(E.WebView.closing_agreement_callback) == 'function' then
        E.WebView.closing_agreement_callback()
        E.WebView.closing_agreement_callback = nil
        return
    end

    --check agree result
    if agree_result.result then
        E.LOG.debug(TAG, "agreement page result: true, user agree")
        --同意
        --request server for accept
        request_agree_eurl(agree_result.url_version, agree_ejoy_token, function(succ, ...)
            if agree_callback then
                if succ then
                    E.LOG.debug(TAG,"request_agree_eurl result succ")
                    agree_callback(true)
                    -- stat agreement close
                    stat_action("ejoy_agreement_close_eurl_result", true, agree_result.url_version)
                else
                    local code, msg = ...
                    E.LOG.warn(TAG, "request_agree_eurl result fail, code:" .. tostring(code) .. ", errMsg:" .. tostring(msg))
                    agree_callback(false)
                    -- stat agreement close
                    local stat_msg = tostring(code) .. "-" .. tostring(msg)
                    stat_action("ejoy_agreement_close_eurl_result", false, stat_msg)
                end
            end
        end)

        -- stat agreement close
        stat_action("ejoy_agreement_close_request_eurl", agree_result.url_version, agree_result.result)
    else
        --拒绝
        E.LOG.warn(TAG, "agreement page result: false, user decline")
        if agree_callback then
            agree_callback(false)
        end

        -- stat agreement close
        stat_action("ejoy_agreement_close_skip_eurl", agree_result.url_version, agree_result.result)
    end

    --重置agree_result
    agree_result = {
        result = false,
        url_version = 0,
    }
    ET.unsubscribe('webview_close', webview_close_callback)
    ET.unsubscribe('webview_jsargs', webview_js_callback)
    E.LOG.debug(TAG, "unsubscribe event webview_close")
    E.LOG.debug(TAG, "unsubscribe event webview_jsargs")
end

function M.handle_login_reject_error(status, ejoy_token, cb)
    if status ~= M.ERR_CODE_REJECT_FOR_AGREEMENT then
        return false
    end

    local os = E.Sysinfo.os()
    if os == "windows" and not E.support_webview() then
        -- 有时候会有手机端已签署了协议，但是PC端扫码后还需要再次签署的情况，如果没有webview则直接返回，跟以前一样
        E.LOG.warn(TAG, 'do not has webview component, return now.')
        return
    end

    E.LOG.debug(TAG, 'handle_login_reject_error agreement handler handled this status')

    agree_callback = cb
    agree_ejoy_token = ejoy_token

    ET.unsubscribe('webview_jsargs', webview_js_callback)
    ET.unsubscribe('webview_close', webview_close_callback)

    E.LOG.debug(TAG, "subscribe event webview_jsargs, webview_close")
    ET.subscribe('webview_jsargs', webview_js_callback)
    ET.subscribe('webview_close', webview_close_callback)

    E.LOG.debug(TAG, "handle_login_reject_error, need user agreement!")
    show_agreement_webview(AGREEMENT_SERVICE.agreement_for_sign)
    return true
end

return M
