---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pangang.
--- DateTime: 2021/7/27 2:21 PM
--- 描述：资源下载管理类，支持顺序下载、并行下载、检查下载状态和下载状态通知
---
local E = require 'ejoysdk_lua.ejoysdk'
local CONSTANTS = require 'ejoysdk_lua.ejoysdk_constants'
local EM = require "ejoysdk_lua.ejoysdk_module"
local M = {}
local TAG = EM.MODULE.RES .. "ejoysdk_res_download"
local HRU = require "ejoysdk_lua.res.ejoy_http_res_utils"

local DOWNLOAD_STATES = {
    DOWNLOADED = "downloaded",
    DOWNLOADING = "downloading",
    UNKNOWN = "unknown"
}

local downloading_files = {}
local temp_suffix = "_dl_bak_"

local function stat(action, key, action_type)
    local ejoysdk_stat = require 'ejoysdk_lua.ejoysdk_stat'
    E.LOG.debug(TAG, "action=" .. tostring(action) .. ', key=' .. tostring(key))
    ejoysdk_stat.stat_action(action, action_type, nil, { url = key })
end


-- 检查已经下载文件、检查是否下载中
local function check_file_state(file_path)
    if HRU.is_file_exists(file_path) then
        E.LOG.debug(TAG, "check_file_state file exists, now return downloaded")
        return DOWNLOAD_STATES.DOWNLOADED
    end

    local download_listeners = downloading_files[file_path]
    if download_listeners and next(download_listeners) ~= nil then
        return DOWNLOAD_STATES.DOWNLOADING
    else
        return DOWNLOAD_STATES.UNKNOWN
    end
end

-- 下载资源
-- 检查资源临时下载目录，监听下载状态，检查空间，网络切换（状态暂停）
function M.download(params, cb)
    local dest_file = params.dest
    local temp_file = params.dest .. temp_suffix
    local state = check_file_state(dest_file)

    local add_download_listener = function(_dest_file, listener)
        downloading_files[_dest_file] = downloading_files[_dest_file] or {}
        local download_listeners = downloading_files[_dest_file]
        table.insert(download_listeners, listener)
    end

    if state == DOWNLOAD_STATES.DOWNLOADED then
        E.LOG.debug(TAG, "download check_file_state downloaded, return true directly")
        cb(true)
        return
    elseif state == DOWNLOAD_STATES.DOWNLOADING then
        E.LOG.debug(TAG, "download check_file_state downloading, add callback and return")
        add_download_listener(dest_file, cb)
        return
    else
        add_download_listener(dest_file, cb)
    end

    local stat_action = 'res_download'
    local key = params.key or ''
    stat(stat_action, key)

    local down_params = {
        file = temp_file,
        checksum = params.checksum,
        timeout = params.timeout
        --followRedirects = true -- android 关闭自动redirect，用于获取oss文件名
    }

    if params.force_update then
        -- 强刷的情况下防止因下载等待时间过长
        down_params.connectionTimeout = 5000
        down_params.dataRetrievalTimeout = 5000
    end

    local download_result_callback = function(succ, ...)
        local listeners = downloading_files[dest_file] or {}
        for _, lis in ipairs(listeners) do
            lis(succ, ...)
        end

        -- 清空下载中文件状态
        downloading_files[dest_file] = nil
    end

    E.LOG.debug(TAG, "begin download:" .. tostring(params.url))
    E.HTTP.get(params.url, down_params, function(resp)
        local status = (resp ~= nil) and resp.status or CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_RESPONSE_INVALID
        local succ = status == 200
        local msg
        if succ then
            HRU.os_rename(temp_file, dest_file)
            msg = nil
        else
            if status == CONSTANTS.EJOYSDK_ERROR_CODES.RES_DOWNLOAD_MD5_MISMATCH then
                E.LOG.warn(TAG, "download failed, for download md5 mismatch, remove temp file:" .. tostring(temp_file))
                HRU.os_remove(temp_file)
            end

            msg = "download failed"
        end

        -- callback download result
        download_result_callback(succ, status, msg)

        if succ then
            stat(stat_action , key, true)
            E.LOG.debug(TAG, "download succ:" .. tostring(params.url))
        else
            stat(stat_action , key, false)
            E.LOG.debug(TAG, "download failed, msg:" .. tostring(msg) .. ", url:" .. tostring(params.url))
        end
    end)
end

function M.register_download_state_listener()

end

return M