---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hanami.
--- DateTime: 6/26/22 8:24 PM
---
---
local STAT = require "ejoysdk_lua.ejoysdk_stat"
local E = require "ejoysdk_lua.ejoysdk"

local TAG = 'free_flow#free_flow_stat'


local M = {}

M.FREE_FLOW_ACTION = {
    -- 初始化
    FREE_FLOW_INIT = 'free_flow_init',
    -- 展示用户协议
    FREE_FLOW_SHOW_AUTH = 'free_flow_show_auth',
    -- 用户点击用户协议结果
    FREE_FLOW_SHOW_AUTH_RESULT = 'free_flow_show_auth_result',
    -- 获取号码认证token
    FREE_FLOW_GET_TOKEN_RESULT = 'free_flow_get_token_result',
    -- 领取流量包请求结果
    FREE_FLOW_RECEIVE_REQUEST_RESULT = 'free_flow_receive_request_result',
    -- 流量包领取结果
    FREE_FLOW_RECEIVE_RESULT = 'free_flow_receive_result',
    -- 展示查询流量包领取结果loading
    FREE_FLOW_RECEIVE_SHOW_LOADING  = 'free_flow_receive_show_loading',
    -- 轮询频率变化
    FREE_FLOW_RECEIVE_LOADING_INTERVAL = 'free_flow_receive_loading_interval',
    -- 领取成功页面
    FREE_FLOW_SHOW_RECEIVE_SUCC_PAGE = 'free_flow_show_receive_succ_page',
    -- 展示领取流量包失败页面
    FREE_FLOW_SHOW_RECEIVE_FAIL = 'free_flow_show_receive_fail',
    -- 领取失败页面点击返回重试
    FREE_FLOW_SHOW_RECEIVE_FAIL_RETRY = 'free_flow_show_receive_fail_retry',
    -- 领取失败页面点击进入游戏
    FREE_FLOW_SHOW_RECEIVE_FAIL_ENTER = 'free_flow_show_receive_fail_enter',
    -- 领取成功页面点击进入游戏
    FREE_FLOW_SHOW_RECEIVE_SUCC_ENTER = 'free_flow_show_receive_succ_enter',
    -- 是否有订购中的订单
    FREE_FLOW_HAS_ORDERING_ORDER = 'free_flow_has_ordering_order',
    -- 获取掩码结果
    FREE_FLOW_GET_MASK_RESULT = 'free_flow_get_mask_result',
    -- 免流量toast提示
    FREE_FLOW_TOAST = 'free_flow_toast',
    -- 显示电信可领取免流量弹窗
    DX_GET_FREE_FLOW_PAGE = 'dx_get_free_flow_page',
    -- 显示电信可领取免流量弹窗-点击登录
    DX_GET_FREE_FLOW_PAGE_LOGIN_BUTTON = 'dx_get_free_flow_page_login_button'
}

local action_type = 'free_flow'


function M.stat_action(action, result, params)
    E.LOG.debug(TAG, 'stat action, action >> ' .. tostring(action) .. ', and result >> ' .. tostring(result))
    local stat_params = params or {}
    stat_params["is_priority_high"] = true
    STAT.stat_action(action, action_type, result, stat_params)
end


return M