---
--- 浮窗Webview浏览器
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ligs.
--- DateTime: 2022/6/20 16:12
---

local E = require 'ejoysdk_lua.ejoysdk'
local JSON = require 'ejoysdk_lua.ejoysdk_json'
local Floater = {}

Floater.Action = {
    CREATE = 1,
    SHOW = 2,
    HIDE = 3,
    DESTROY = 4,
    OPEN_URL = 5,
    RELOAD = 6,
    SIZE = 7,
    POSITION = 8,
    DRAGGABLE = 9,
    CALL_JS = 10,
    FRAME = 11,
    SET_FRAME = 12
}

Floater.Event = {
    -- ABOUT WINDOW
    SHOW = 101,
    HIDE = 102,
    CLOSE = 103,
    CHANGED_SIZE = 104,
    CHANGED_POSITION = 105,

    -- ABOUT USERINTERACTION
    CLICK = 201,

    -- ABOUT PAGE
    PAGE_LOAD_START = 301,
    PAGE_LOAD_FINISHED = 302,
}

local OPERATOR = "FLOATER"
local event_callback = nil
local adjust_size = false-- 目前为s3使用，s3是自己计算的

local EJOY_FLOATER_EVENT = 'EJOY_FLOATER_EVENT'
_ejoysdk.register_cb(
        EJOY_FLOATER_EVENT,
        function(event_id, params, _chunk)
            if not event_callback then
                return
            end

            local f_event_callback = event_callback[event_id]

            if f_event_callback and type(f_event_callback) == 'function' then
                f_event_callback(params)
            end
        end
)

local function call(async, action, params, cb)
    params = params or {}
    params.action = action
    local os = _ejoysdk.os()
    if async == true then
        if os == 'android' then
            E.async_call(OPERATOR, params, nil, cb)
        else
            if os == 'ios' or os == 'windows' then
                E.async_call(OPERATOR, cb, JSON.encode(params))
            end
        end
    else
        if os == 'android' then
            return E.sync_call(OPERATOR, params)
        else
            if os == 'ios' or os == 'windows' then
                return E.sync_call(OPERATOR, -1, JSON.encode(params)) -- -1这里cbid做占位
            end
        end
    end
end

local function adjustSize(is_pixel, x, y, width, height)
    x = x or 0
    y = y or 0
    width = width or 0
    height = height or 0

    if adjust_size == true and _ejoysdk.os() == 'ios' then
        -- ios使用的是point，而外面传进来的是pixel，需要转换
        local screen_size = E.Sysinfo.screen()
        local scale = screen_size.scale
        local offset = 0.5
        if (is_pixel) then
            -- pixel to point
            x = math.floor(x / scale + offset)
            y = math.floor(y / scale + offset)
            width = math.floor(width / scale + offset)
            height = math.floor(height / scale + offset)
        else
            -- point to pixel
            x = math.floor(x * scale + offset)
            y = math.floor(y * scale + offset)
            width = math.floor(width * scale + offset)
            height = math.floor(height * scale + offset)
        end
    end
    return x, y, width, height

end

local function adjustToPoint(x, y, width, height)
    return adjustSize(true, x, y, width, height)
end

local function adjustToPixel(x, y, width, height)
    return adjustSize(false, x, y, width, height)
end

function Floater.async_call(action, params, cb)
    call(true, action, params, cb)
end

function Floater.sync_call(action, params)
    return call(false, action, params)
end

function Floater.create(url, frame, params)
    frame = frame or {}
    params = params or {}

    adjust_size = false -- 默认是由游戏自己计算尺寸并适配
    if params.adjust_size ~= nil then
        adjust_size = params.adjust_size
    end

    local type = params.window_type or "DEFAULT"
    local x, y, width, height = adjustToPoint(frame.x or 0, frame.y or 0, frame.width or 0, frame.height or 0)
    local size = { width = width, height = height }

    -- 初始位置如果传递了百分比，计算中心点的距离在横竖坐标的位置，忽略frame的x,y
    if params.use_center_per then
        local center_x_per = params.center_x_per or 50
        local center_y_per = params.center_y_per or 50
    
        if E.Sysinfo.screen then
            local screen_data = E.Sysinfo.screen() or {}
            local sw = screen_data.width or 0
            local sh = screen_data.height or 0
            local os = _ejoysdk.os()
            -- 默认是原来的wh
            local sxlen = sw
            local sylen = sh
            if os == 'android' then
                local is_portrait = screen_data.is_portrait
                if is_portrait then -- 宽 < 高
                    sylen = math.max(sw, sh)
                    sxlen = math.min(sw, sh)
                else -- 宽 > 高
                    sxlen = math.max(sw, sh)
                    sylen = math.min(sw, sh)
                end
                -- E.LOG.debug('Floater', "is_portrait :" .. tostring(is_portrait))
            elseif os == 'windows' then -- 总是横屏 宽 > 高
                local window_height = screen_data.window_height or -1
                local window_width = screen_data.window_width or -1
                -- E.LOG.debug('Floater', "window_width :" .. tostring(window_width) .. ", window_height :" .. tostring(window_height))
                if window_height > 0 and window_width > 0 then
                    sxlen = math.max(window_width, window_height)
                    sylen = math.min(window_width, window_height)
                else
                    sxlen = 0
                    sylen = 0
                end
            end

            E.LOG.debug('Floater', "sxlen :" .. tostring(sxlen) .. ", sylen :" .. tostring(sylen))
            
            if sxlen > 0 and sylen > 0 then
                x = math.floor(sxlen * center_x_per / 100 - width/2)
                y = math.floor(sylen * center_y_per / 100 - height/2)
            end
            -- E.LOG.debug('Floater', "scale :" .. tostring(scale))
            -- E.LOG.debug('Floater', "x :" .. tostring(x) .. ", y :" .. tostring(y))
        end
    end
    

    if params.create_type == 'webview' then
        -- 社区等入口的默认值
        if not params.options then
            params.options = {
                enable_loading = true,
                hide_close_btn = false,
                disable_auto_fontsize = true
            }
        end
    else -- 需要自己接管关闭等逻辑
        if not params.options then
            params.options = {
                enable_loading = false,
                hide_close_btn = true
            }
        end
    end

    local position = { x = x, y = y }

    event_callback = params.callbacks or {}

    params.window_type = nil
    params.callbacks = nil -- 防止async_call转换失败
    Floater.async_call(Floater.Action.CREATE, { url = url or '', window_type = type, size = size, pos = position, params = params })
end

function Floater.show()
    Floater.async_call(Floater.Action.SHOW)
end

function Floater.hide()
    Floater.async_call(Floater.Action.HIDE)
end

function Floater.destroy()
    Floater.async_call(Floater.Action.DESTROY)
end

-- 返回一个table,eg {"x"=1,"y"=1,"width"=1,"height"=1}
function Floater.get_frame()
    local os = _ejoysdk.os()

    local get_frame_data = Floater.sync_call(Floater.Action.FRAME)

    if os == 'ios' or os == 'windows' then
        local ret_json = JSON.safe_decode(get_frame_data) or { x = 0, y = 0, width = 0, height = 0 }
        local x, y, width, height = adjustToPixel(ret_json.x or 0, ret_json.y or 0, ret_json.width or 0, ret_json.height or 0)
        get_frame_data = { x = x, y = y, width = width, height = height }
    end

    return get_frame_data
end

-- 传入像素
function Floater.set_frame(x, y, width, height)
    if x and y and width and height and width >= 0 and height >= 0 then
        x, y, width, height = adjustToPoint(x, y, width, height)

        Floater.async_call(Floater.Action.SET_FRAME, { x = x, y = y, width = width, height = height })
    end
end

function Floater.resize(width, height)
    if (width and height and width >= 0 and height >= 0) then
        local _, _, w, h = adjustToPoint(nil, nil, width, height)
        Floater.async_call(Floater.Action.SIZE, { width = w, height = h })
    end
end

function Floater.reposition(x, y)
    if (x and y) then
        x, y = adjustToPoint(x, y)
        Floater.async_call(Floater.Action.POSITION, { x = x, y = y })
    end
end

function Floater.open_url(url)
    Floater.async_call(Floater.Action.OPEN_URL, { url = url })
end

function Floater.reload()
    Floater.async_call(Floater.Action.RELOAD)
end

function Floater.set_draggable(able)
    Floater.async_call(Floater.Action.DRAGGABLE, { draggable = able or false })
end

function Floater.call_js(js_str, cb)
    Floater.async_call(Floater.Action.CALL_JS, { script = js_str or '' }, cb)
end

return Floater
