---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ali.
--- DateTime: 2020/3/30 下午4:47
---
local _E = require 'ejoysdk_lua.ejoysdk'
local ET = require "ejoysdk_lua.ejoysdk_topic"
local STATES = require 'ejoysdk_lua.chat.ejoysdk_chat_states'
local CALLBACK = require 'ejoysdk_lua.chat.ejoysdk_chat_callback_manager'
local CONSTANTS = require 'ejoysdk_lua.ejoysdk_constants'
local EM = require "ejoysdk_lua.ejoysdk_module"
local chat_log = require 'ejoysdk_lua.ejoysdk_log_mgr'
local chat_log_util = require 'ejoysdk_lua.chat.ejoysdk_chat_log_util'
local compat = require 'ejoysdk_lua.compat.ejoysdk_compat'
local xpcall = compat.xpcall

local TAG = EM.MODULE.CHAT .. 'dsp'

local M = {}

local destination_chat_handlers_cache = {}
local server_handlers_cache = {}
local destination_chat_v2_handlers_cache = {}

function M.register_chat_handlers(destination, chat_handlers)
    M.unregister_chat_handlers(destination)
    --E.LOG.debug(TAG, 'register_handlers, destination:'..(destination or 'nil'))
    destination_chat_handlers_cache[destination] = chat_handlers
end

function M.unregister_chat_handlers(destination)
    --E.LOG.debug(TAG, 'unregister_handlers, destination:'..(destination or 'nil'))
    destination_chat_handlers_cache[destination] = nil
end

function M.register_server_handlers(server_handlers)
    for _, handler in ipairs(server_handlers_cache) do
        if handler == server_handlers then
            return
        end
    end
    server_handlers_cache[#server_handlers_cache + 1] = server_handlers
end

function M.unregister_server_handlers(server_handlers)
    local new = {}
    for _, handler in ipairs(server_handlers_cache) do
        if server_handlers ~= handler then
            new[#new + 1] = handler
        end
    end
    server_handlers_cache = new
end

function M.register_chat_v2_handlers(destination, chat_handlers)
    M.unregister_chat_v2_handlers(destination)
    --E.LOG.debug(TAG, 'register_handlers, destination:'..(destination or 'nil'))
    destination_chat_v2_handlers_cache[destination] = chat_handlers
end

function M.unregister_chat_v2_handlers(destination)
    --E.LOG.debug(TAG, 'unregister_handlers, destination:'..(destination or 'nil'))
    destination_chat_v2_handlers_cache[destination] = nil
end

local function exec_server_handler_method(method_name, params)
    for _, handlers in ipairs(server_handlers_cache) do
        --E.LOG.debug(TAG, 'start invoke exec_server_handler_method:'..(method_name or 'nil'))
        local method = handlers[method_name]
        if method then
            --E.LOG.debug(TAG, 'exec_server_handler_method, method_name:'..method_name)
            method(params);
        else
            chat_log.warn(chat_log_util.header(), TAG, 'exec_server_handler_method_not_found', {method=method_name}, {})
        end
    end
end

local function exec_server_handler_method_on_error(method_name, params, error_code)
    for _, handlers in ipairs(server_handlers_cache) do
        --E.LOG.debug(TAG, 'start invoke exec_server_handler_method:'..(method_name or 'nil'))
        local method = handlers[method_name]
        if method then
            --E.LOG.debug(TAG, 'exec_server_handler_method, method_name:'..method_name)
            method(params, error_code or CONSTANTS.CHAT_ERROR_CODES.CODE_DISPATCHER_ON_ERROR_NO_CODE);
        else
            chat_log.warn(chat_log_util.header(), TAG, 'exec_server_handler_method_on_error_not_found', {method=method_name}, {})
        end
    end
end

function M.on_connect_start()
    --E.LOG.debug(TAG,'chat server on_connect_start')

    ET.publish(ET.chat.UPDATE_STATE, STATES.CONNECT_START)

    exec_server_handler_method('on_connect_start')
end

function M.on_connect_error(error_msg)
    --E.LOG.warn(TAG,'chat server on_connect_error: ' .. (error_msg or ''))
    ET.publish(ET.chat.UPDATE_STATE, STATES.CONNECT_ERROR)

    exec_server_handler_method('on_connect_error', error_msg)
end

function M.on_connecting()
    --E.LOG.debug(TAG, 'chat server on_connecting')
    ET.publish(ET.chat.UPDATE_STATE, STATES.CONNECTING)
    exec_server_handler_method('on_connecting')
end

function M.on_connected()
    --E.LOG.debug(TAG,'chat server on_connected')
    ET.publish(ET.chat.UPDATE_STATE, STATES.CONNECTED)

    exec_server_handler_method('on_connected')
end

function M.on_disconnect()
    --E.LOG.debug(TAG,'chat server on_disconnect')
    ET.publish(ET.chat.UPDATE_STATE, STATES.DISCONNECT)

    exec_server_handler_method('on_disconnect')
end

function M.on_error(error_msg, error_code)
    --E.LOG.warn(TAG,'chat server on_error, err_msg:'..(error_msg or 'nil') .. ', err_code:' .. tostring(error_code))
    ET.publish(ET.chat.UPDATE_STATE, STATES.ERROR)

    exec_server_handler_method_on_error('on_error', error_msg, error_code)
end

function M.handle_message(header, msg)
    local destination = header.destination
    if not destination or destination == '' then
        --E.LOG.warn(TAG, 'handle_message failed, for destination is nil')
        return
    end

    local exe_chat_handlers = function()
        local chat_handlers = destination_chat_handlers_cache[destination]
        if not chat_handlers then
            --E.LOG.warn(TAG, 'handle_message failed, not find chat_handlers for destination:'..(destination or 'nil'))
            --chat_log.warn(chat_log_util.header(), TAG, 'handle_message_no_chat_handlers', {header=header, msg=msg}, {})
            return
        end

        _E.LOG.debug(TAG, 'exe_chat_handlers >>')
        _E.LOG.debug(TAG, {header=header, msg=msg})

        -- 服务端推送消息监听
        --E.LOG.debug(TAG, 'handle_message destination:'..destination)
        --E.log(msg)
        xpcall(chat_handlers, function (x)
            -- 把异常抛给游戏侧方便他们统计，debug调试, 只有chat_handlers需要通知，chat_handlers_v2不需要
            local notify_succ, notify_error = pcall(CALLBACK.callback, 'chat', CALLBACK.HANDLER_NAME.ON_HANDLERS_ERROR, '', x) -- x前面的参数原来是堆栈, 现在为了性能，不再抓堆栈
            if not notify_succ then
                chat_log.warn(chat_log_util.header(), TAG, 'chat_notify_cp_error', {notify_error=notify_error}, {})
            end

            chat_log.warn(chat_log_util.header(),
                    TAG,
                    'handle_message_has_error',
                    {
                        lua_error_msg = tostring(x)
                    },
                    {})

        end, header, msg)
    end

    exe_chat_handlers()

    local exe_chat_v2_handlers = function()
        local chat_v2_handlers = destination_chat_v2_handlers_cache[destination]
        if not chat_v2_handlers then
            --E.LOG.warn(TAG, 'handle_message failed, not find chat_handlers for destination:'..(destination or 'nil'))
            --chat_log.warn(chat_log_util.header(), TAG, 'handle_message_no_chat_handlers', {header=header, msg=msg}, {})
            return
        end

        _E.LOG.debug(TAG, 'exe_chat_v2_handlers >>')
        _E.LOG.debug(TAG, {header=header, msg=msg})

        -- 服务端推送消息监听
        --E.LOG.debug(TAG, 'handle_message destination:'..destination)
        --E.log(msg)
        xpcall(chat_v2_handlers,
                function (x)
                    chat_log.warn(chat_log_util.header(),
                            TAG,
                            'handle_message_has_error',
                            {
                                lua_error_msg = tostring(x)
                            },
                            {})

                end,
                header, msg)
    end

    exe_chat_v2_handlers()
end

return M