#!/usr/bin/env python3
"""Bundle the Node engine into a browser script for Route B.

Route B runs the same engine inside the page: the client's own socket layer is
replaced by a loopback that calls engine.dispatch() directly, so no WS server is
needed. This emits work/run/web/__offline-engine.js defining window.FrogEngine.

The engine is CommonJS, so we emit a tiny module registry plus browser stubs for
`fs` (localStorage-backed) and `path`.
"""
from pathlib import Path as _PortablePath
# 仓库根：本文件位于 <仓库根>/work/tools/ 下，因此向上两级。
# 不写死任何绝对路径 —— 换机器 / 换系统（Windows、Linux、macOS）都能直接跑。
PROJECT_ROOT = _PortablePath(__file__).resolve().parents[2]
import json, os, re, sys

RUN = str(PROJECT_ROOT) + "/work/run"
ENGINE = os.path.join(RUN, "engine")
OUT = os.path.join(RUN, "web", "__offline-engine.js")


def read(p):
    return open(p, encoding="utf8").read()


def strip_module_wrapper(src):
    """The engine body is used verbatim: the shim provides `module`/`exports`,
    so its own module.exports assignment is what defines FrogEngine."""
    return src


def main():
    protocol_src = read(os.path.join(ENGINE, "protocol.js"))
    m = re.search(r"module\.exports\s*=\s*(\{.*\})\s*;\s*$", protocol_src, re.S)
    if not m:
        print("could not find protocol table in protocol.js")
        return 1
    protocol_json = m.group(1)

    gamedata = read(os.path.join(ENGINE, "data", "gamedata.json"))
    # define.json is the original server's tuning table. It MUST be inlined too --
    # without it the engine's require() throws inside try/catch and every DEF() call
    # silently falls back to a hard-coded default. Node has the file so the unit
    # tests pass either way; only the browser was degraded, which is how this was
    # found (Frogpattern was empty there and the frog never changed activity).
    define_json = read(os.path.join(ENGINE, "data", "define.json"))
    engine_src = strip_module_wrapper(read(os.path.join(ENGINE, "index.js")))

    out = []
    out.append("""/* AUTO-GENERATED by work/tools/bundle_engine.py - do not edit by hand.
 *
 * Browser build of the offline engine (Route B): the same rules/logic that
 * server/main.js runs in Route A, but executing inside the game page.
 *
 *   window.FrogEngine.createEngine({ ... }) -> engine
 *
 * Persistence uses localStorage via the `fs` stub below. Pacing knobs can be
 * overridden with window.FROG_CONFIG = { env: { FROG_TRAVEL_MIN: 20, ... } }.
 */
(function (global) {
  'use strict';

  var modules = {};
  var cache = {};
  function define(name, fn) { modules[name] = fn; }
  function req(name) {
    if (cache[name]) return cache[name].exports;
    if (!modules[name]) throw new Error('[offline-engine] no module: ' + name);
    var m = { exports: {} };
    cache[name] = m;
    modules[name](m, m.exports, req);
    return m.exports;
  }

  var SAVE_KEY = 'frog.offline.save';
  /* The engine keeps its safety copies as sibling files (save.json.bak / .tmp /
     .corrupt-<ts>). A browser has no files to put them in, so each slot gets its
     own localStorage key under the primary. The primary key itself is UNCHANGED,
     so saves written by earlier builds keep loading. */
  var SAVE_FILE = 'save.json';
  var SLOT_PREFIX = SAVE_KEY + '::';
  function baseName(p) {
    var s = String(p == null ? SAVE_FILE : p).replace(/\\\\/g, '/');
    var i = s.lastIndexOf('/');
    return i < 0 ? s : s.slice(i + 1);
  }
  function slotName(p) {
    var b = baseName(p);
    return !b || b === SAVE_FILE ? '' : b;
  }
  function keyFor(p) {
    var s = slotName(p);
    return s ? SLOT_PREFIX + s : SAVE_KEY;
  }
  function isPrimary(p) { return slotName(p) === ''; }

  define('fs', function (module, exports) {
    /* On the phone the native wrapper also keeps a copy of the save in app
       storage (see FrogNative.readMirrorSave / mirrorSave). localStorage is tied
       to the page origin, so if the wrapper could not take its fixed port and fell
       back to a random one, the origin -- and the store -- changes between
       launches. The mirror is consulted ONLY when localStorage has nothing, so it
       can never override a healthy save. Off-device FrogNative is absent and this
       costs nothing. */
    function bridge() {
      try { return global.FrogNative || null; } catch (e) { return null; }
    }
    function localGet(p) {
      try { return global.localStorage.getItem(keyFor(p)); } catch (e) { return null; }
    }
    function mirrorGet() {
      var b = bridge();
      if (b && b.readMirrorSave) {
        try { return b.readMirrorSave() || null; } catch (e) { }
      }
      return null;
    }
    exports.existsSync = function (p) {
      if (!isPrimary(p)) return localGet(p) != null;
      return localGet(p) != null || mirrorGet() != null;
    };
    exports.readFileSync = function (p) {
      var local = localGet(p);
      if (local != null) return local;
      /* Deliberately NOT falling back to the mirror here. The engine reads the
         native mirror itself (exports.readMirrorSave below) as the last step of
         its main -> backup -> mirror chain, which is the only way it can REPORT
         which copy the player is actually playing from. Folding the mirror into
         this read would make a restored-from-phone save look like a normal load. */
      return null;
    };
    /* Returns false instead of throwing: some engines drop a setItem on quota
       without raising, and the engine's read-back check needs a signal either
       way. Only the primary reaches the native mirror. */
    exports.writeFileSync = function (p, data) {
      var v = String(data);
      try { global.localStorage.setItem(keyFor(p), v); } catch (e) { return false; }
      if (!isPrimary(p)) return true;
      var b = bridge();
      if (b && b.mirrorSave) {
        try { b.mirrorSave(v); } catch (e) { }
      }
      return true;
    };
    exports.removeFileSync = function (p) {
      try { global.localStorage.removeItem(keyFor(p)); return true; } catch (e) { return false; }
    };
    exports.readMirrorSave = function () { return mirrorGet(); };
    exports.listSaveSlots = function () {
      var out = [];
      try {
        var ls = global.localStorage;
        for (var i = 0; i < ls.length; i++) {
          var k = ls.key(i);
          if (k && k.indexOf(SLOT_PREFIX) === 0) out.push(k.slice(SLOT_PREFIX.length));
        }
      } catch (e) { }
      return out;
    };
    exports.mkdirSync = function () { };
  });

  define('path', function (module, exports) {
    exports.join = function () {
      return Array.prototype.slice.call(arguments).join('/');
    };
    exports.dirname = function (p) {
      var i = String(p).lastIndexOf('/');
      return i < 0 ? '.' : String(p).slice(0, i);
    };
    exports.basename = function (p) { return baseName(p); };
  });
""")
    out.append("  define('./protocol', function (module, exports) {\n    module.exports = ")
    out.append(protocol_json)
    out.append(";\n  });\n\n")

    out.append("  define('./data/gamedata.json', function (module, exports) {\n    module.exports = ")
    out.append(gamedata.strip())
    out.append(";\n  });\n\n")

    out.append("  define('./data/define.json', function (module, exports) {\n    module.exports = ")
    out.append(define_json.strip())
    out.append(";\n  });\n\n")

    # picture-layers.json (the composed postcard `layers`) must be inlined for
    # exactly the same reason define.json was: the engine's require() throws
    # inside try/catch, so a missing table degrades SILENTLY. With define.json
    # the symptom was every DEF() falling back; here it would be every postcard
    # rendering blank in the browser while the Node unit tests stayed green.
    layers_json = read(os.path.join(ENGINE, "data", "picture-layers.json"))
    out.append("  define('./data/picture-layers.json', function (module, exports) {\n    module.exports = ")
    out.append(layers_json.strip())
    out.append(";\n  });\n\n")

    # travel.json (the destination map: Area/Node/NodeConnect/NodeEdge/NodeGoal/
    # NodeItem + Item.effects). Same silent-degradation trap as define.json: the
    # engine's require() sits in try/catch and `TV_OK` would simply be false, so
    # every trip in the browser would fall back to the old uniform roll while the
    # Node tests stayed green.
    travel_json = read(os.path.join(ENGINE, "data", "travel.json"))
    out.append("  define('./data/travel.json', function (module, exports) {\n    module.exports = ")
    out.append(travel_json.strip())
    out.append(";\n  });\n\n")

    out.append("  var process = { env: (global.FROG_CONFIG && global.FROG_CONFIG.env) || {} };\n")
    out.append("  var __dirname = '';\n\n")
    out.append("  define('./index', function (module, exports, require) {\n")
    out.append(engine_src)
    out.append("\n  });\n\n")
    out.append("  global.FrogEngine = req('./index');\n")
    out.append("})(window);\n")

    text = "".join(out)
    open(OUT, "w", encoding="utf8").write(text)
    print(f"wrote {OUT} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
