"""Emit probe/check_res_names.js: the exact Egret resource NAMES the client will
request when drawing every composed postcard, so the page can verify that the
game's own resource manager resolves all of them.

    name = basename(ResourcesDB[resId]) + "_png"      (main.min.js getPicturePath)

If RES.getRes returns null for a name the picture does not draw at all, so this
is the precise failure mode to rule out.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', 'run'))
OUT = os.path.join(HERE, '..', 'probe', 'check_res_names.js')

L = json.load(open(os.path.join(ROOT, 'engine', 'data', 'picture-layers.json'), encoding='utf-8'))
R = json.load(open(os.path.join(ROOT, 'engine', 'data', 'tables', 'resources.json'), encoding='utf-8'))

names = set()
for rec in L.values():
    for l in rec['layers'] + rec.get('travelers', []):
        names.add(os.path.basename(R[str(l['layer'][0])]) + '_png')
names = sorted(names)

TEMPLATE = '''/* AUTO-GENERATED by work/tools/make_res_probe.py -- do not edit.
 *
 * The exact Egret resource NAMES the client asks for when drawing every
 * composed postcard:  name = basename(ResourcesDB[resId]) + "_png"
 * (main.min.js getPicturePath).  RES.getRes(name) === null means the picture
 * does not draw at all, which is the failure this rules out.
 *
 * NOTE: RES.getRes only returns resources that are ALREADY LOADED, so a miss
 * there proves nothing.  `hasRes` asks the manifest, and the async pass below
 * actually loads a sample through the real resource manager.
 */
(function () {
  var NAMES = %s;
  if (typeof RES === 'undefined' || !RES.getRes) {
    return JSON.stringify({ error: 'no RES global' });
  }
  var undeclared = [], declared = 0, cached = 0;
  for (var i = 0; i < NAMES.length; i++) {
    var t = null;
    try { t = RES.getRes(NAMES[i]); } catch (e) { t = null; }
    if (t) { cached++; }
    var has = false;
    try { has = RES.hasRes ? RES.hasRes(NAMES[i]) : false; } catch (e) { has = false; }
    if (has) { declared++; } else { undeclared.push(NAMES[i]); }
  }
  window.__RESCHECK__ = {
    total: NAMES.length, cached: cached, declared: declared,
    undeclared: undeclared.length, first: undeclared.slice(0, 12), done: false
  };
  // now really load a spread of them through the client's own loader
  var sample = [];
  for (var k = 0; k < NAMES.length; k += Math.ceil(NAMES.length / 24)) { sample.push(NAMES[k]); }
  var pending = sample.length, loadFail = [];
  sample.forEach(function (n) {
    RES.getResAsync(n, function (r) {
      if (!r) { loadFail.push(n); }
      if (--pending === 0) {
        window.__RESCHECK__.loaded = sample.length - loadFail.length;
        window.__RESCHECK__.loadSample = sample.length;
        window.__RESCHECK__.loadFail = loadFail;
        window.__RESCHECK__.done = true;
      }
    }, window);
  });
  return JSON.stringify(window.__RESCHECK__);
})()
''' % json.dumps(names)

open(OUT, 'w', encoding='utf-8', newline='').write(TEMPLATE)
print('distinct client resource names: %d' % len(names))
print('wrote %s' % OUT)
