---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ali.
--- DateTime: 4/13/22 2:02 PM
---
local E = require "ejoysdk_lua.ejoysdk"
local CA = require "ejoysdk_lua.cloud_game.cloud_adapter"
local DSP = require "ejoysdk_lua.protocal.ejoysdk_ds_protocal"
local CC = require "ejoysdk_lua.cloud_game.cloud_config"

local M = {}

local TAG = "cloud_time_limit_manager"

M.ENV = {
    DEBUG = 'debug',
    RELEASE = 'release',
    PRE_RELEASE = 'pre_release'
}

M.SERVICE = {
    -- 九游阿里云调度
    CLOUD_MSG_CHECK = 'cloud.msg.check'
}

M.DSP_SERVICE_MAPPING = {
    [M.SERVICE.CLOUD_MSG_CHECK] = DSP.SERVICE.CLOUD_MSG_CHECK
}

M.POLL_SCENE = {
    SCENE_NORMAL = 0,
    SCENE_KICK = 1
}

M.POLL_STATUS = {
    STATUS_STOP = 0,
    STATUS_POLLING = 1
}

M.CLOUD_ERROR_CODE = {
    TIME_OUT = '5003001'
}

M.POLL_MSG_ID = {
    MSG_TIPS_2 = '901000', --提示2，5分钟
    MSG_TIPS = '901001',  --提示1，10分钟
    MSG_H5 = '901002',
    MSG_FORBID_EXPERIENCE_TIME_END = '901003',  -- 体验时间到期
    MSG_FORBID_TOTAL_TIME_END = '901004'  -- 总试玩时长到期
}

M.TIME_LIMIT_STAGE = {
    UNKNOWN = "unkonwn", -- 在体验时间中
    IN_EXPERIENCE_TIME = "in_experience_time", -- 在体验时间中
    EXPERIENCE_TIME_END = "experience_time_end", -- 体验时间到期
    PLAY_TOTAL_TIME_COMING = "play_total_time_coming", -- 试玩总时间即将到期 -第一次，10分钟
    PLAY_TOTAL_TIME_COMING_2 = "play_total_time_coming_2", -- 试玩总时间即将到期 -第二次，5分钟
    PLAY_TOTAL_TIME_END = "play_total_time_end", -- 试玩总时间到期
}

local TIME_LIMIT_ORDER = {
    [M.TIME_LIMIT_STAGE.UNKNOWN] = 0,
    [M.TIME_LIMIT_STAGE.IN_EXPERIENCE_TIME] = 1,
    [M.TIME_LIMIT_STAGE.EXPERIENCE_TIME_END] = 2,
    [M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_COMING] = 3,
    [M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_COMING_2] = 4,
    [M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_END] = 5
}

M.STATE_INFO_KEY = {
    KEY_STAGE = "stage", -- 试玩时长
    KEY_PLAY_TIME_SEC = "play_time_sec", -- 试玩时长
    KEY_EXPERIENCE_TIME_LIMIT_SEC = "experience_time_limit_sec", -- 体验阶段试玩限制时长（秒）
    KEY_TOTAL_TIME_LIMIT_SEC = "total_time_limit_sec", -- 总试玩限制时长（秒）
    KEY_DOWNLOAD_COMPLETE_EXPERIENCE_LIMIT_SEC = "download_complete_experience_limit_sec",
    KEY_REFRESH_TIME_STAMP = "refresh_time_stamp", -- 这个是时长刷新时的时间戳
    KEY_NEXT_INTERVAL = "next_interval"  --下载轮询周期
}

local TIME_2_MIN_IN_SEC = 2 * 60 -- 两分钟
local _TEST_TIME_SEC = 5 -- 5秒轮询一次
M.DEFAULT_EXPERIENCE_TIME_LIMIT_SEC = 60 * 60
M.DEFAULT_TOTAL_TIME_LIMIT_SEC = 10 * 60 * 60
M.DEFAULT_DOWNLOAD_COMPLETE_EXPERIENCE_LIMIT_SEC = 30 * 60

local env = M.ENV.DEBUG
local current_play_sec = -1
local poll_status = M.POLL_STATUS.STATUS_STOP
local is_polling = false --记录实际是否在轮询中
local current_poll_scene = M.POLL_SCENE.SCENE_NORMAL
local heartbeat_interval_sec = TIME_2_MIN_IN_SEC -- 默认两分钟
local current_state_info = {
    stage = M.TIME_LIMIT_STAGE.UNKNOWN
}
local state_change_listeners = {}
local connect_state_instance = nil
local _test_monitor_coming_count = 2
local _test_monitor_coming2_count = 4
local _test_monitor_end_count = 6
local _test_monitor_poll_count = 0


local function update_stage_changed(stage)
    local previous_stage = current_state_info[M.STATE_INFO_KEY.KEY_STAGE]
    local previous_stage_order = -1
    local target_stage_order = -1
    if previous_stage then
        previous_stage_order = TIME_LIMIT_ORDER[previous_stage]
    end

    if stage then
        target_stage_order = TIME_LIMIT_ORDER[stage]
    end

    E.LOG.debug(TAG, "update_stage_changed before check, previous:" .. tostring(previous_stage) .. ", now:" .. tostring(stage)
            .. ", pre_order:" .. tostring(previous_stage_order) .. ", target_stage_order:" .. target_stage_order)
    if stage and previous_stage ~= stage and target_stage_order ~= -1 and target_stage_order > previous_stage_order then
        E.LOG.debug(TAG, "update_stage_changed, previous:" .. tostring(previous_stage) .. ", now:" .. tostring(stage))
        current_state_info[M.STATE_INFO_KEY.KEY_STAGE] = stage

        -- notify outside
        for _, callback in ipairs(state_change_listeners) do
            callback(current_state_info)
        end
    end
end

local function double_check_time_limit(timeCtl)
    if not timeCtl then
        return
    end

    local experience_time_limit_sec = timeCtl.limitTimeSec or M.DEFAULT_EXPERIENCE_TIME_LIMIT_SEC
    local total_time_limit_sec = timeCtl.maxLimitTimeSec or M.DEFAULT_TOTAL_TIME_LIMIT_SEC

    local target_stage = nil
    local current_stage = current_state_info[M.STATE_INFO_KEY.KEY_STAGE]
    if current_play_sec < experience_time_limit_sec then
        if current_stage ~= M.TIME_LIMIT_STAGE.IN_EXPERIENCE_TIME then
            target_stage = M.TIME_LIMIT_STAGE.IN_EXPERIENCE_TIME
        end
    else
        if current_play_sec >= experience_time_limit_sec and current_play_sec < total_time_limit_sec then
            if current_stage ~= M.TIME_LIMIT_STAGE.EXPERIENCE_TIME_END and current_stage ~= M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_COMING
                    and current_stage ~= M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_COMING_2 then
                target_stage = M.TIME_LIMIT_STAGE.EXPERIENCE_TIME_END
            end
        elseif current_play_sec >= total_time_limit_sec then
            if current_stage ~= M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_END then
                target_stage = M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_END
            end
        end
    end

    if target_stage ~= nil then
        -- modify current stage, for server may not notify some stage in some scene
        E.LOG.debug(TAG, "update_time_limit_info and find stage changed, current:" .. tostring(current_stage) .. ", target_stage:" .. tostring(target_stage))
        update_stage_changed(target_stage)
    end
end

-- timeCtl 结构参考这里：https://yuque.antfin-inc.com/mxb7qq/confluence-sdkdev-vg6uys/aauhz7
local function update_time_limit_info(timeCtl, next_interval)
    if not timeCtl then
        return
    end

    current_play_sec = timeCtl.playTimeSec or 0
    local experience_time_limit_sec = timeCtl.limitTimeSec or M.DEFAULT_EXPERIENCE_TIME_LIMIT_SEC
    local total_time_limit_sec = timeCtl.maxLimitTimeSec or M.DEFAULT_TOTAL_TIME_LIMIT_SEC
    current_state_info[M.STATE_INFO_KEY.KEY_PLAY_TIME_SEC] = current_play_sec
    current_state_info[M.STATE_INFO_KEY.KEY_EXPERIENCE_TIME_LIMIT_SEC] = experience_time_limit_sec
    current_state_info[M.STATE_INFO_KEY.KEY_TOTAL_TIME_LIMIT_SEC] = total_time_limit_sec
    current_state_info[M.STATE_INFO_KEY.KEY_DOWNLOAD_COMPLETE_EXPERIENCE_LIMIT_SEC] = M.DEFAULT_DOWNLOAD_COMPLETE_EXPERIENCE_LIMIT_SEC
    current_state_info[M.STATE_INFO_KEY.KEY_REFRESH_TIME_STAMP] = os.time()
    current_state_info[M.STATE_INFO_KEY.KEY_NEXT_INTERVAL] = next_interval
end

local function on_handle_time_ctrl_info(timeCtl, next_interval, _msg)
    -- update time limit info
    update_time_limit_info(timeCtl, next_interval)

    -- process response
    local msg = _msg
    if CC.DEBUG_OPTIONS.TestTimeLimitComing then
        E.LOG.warn(TAG, "TestTimeLimitComing enabled")
        next_interval = _TEST_TIME_SEC

        msg = {}

        if _test_monitor_poll_count == _test_monitor_coming_count then
            msg.templateId = M.POLL_MSG_ID.MSG_TIPS
        elseif _test_monitor_poll_count == _test_monitor_coming2_count then
            msg.templateId = M.POLL_MSG_ID.MSG_TIPS_2
        elseif _test_monitor_poll_count == _test_monitor_end_count then
            msg.templateId = M.POLL_MSG_ID.MSG_FORBID_TOTAL_TIME_END
        end

        _test_monitor_poll_count = _test_monitor_poll_count + 1
    end

    if next_interval > 0 then
        heartbeat_interval_sec = next_interval
        E.LOG.debug(TAG, "update heartbeat interval:" .. tostring(heartbeat_interval_sec))
    end

    if msg then
        local templateId = msg.templateId

        E.LOG.debug(TAG, "request_play_time_limit_from_server, templateId:" .. tostring(templateId))
        if templateId == M.POLL_MSG_ID.MSG_TIPS or templateId == M.POLL_MSG_ID.MSG_TIPS_2
                or templateId == M.POLL_MSG_ID.MSG_H5 then  -- 901000 or 901001 or 901002
            --提示
            if templateId == M.POLL_MSG_ID.MSG_TIPS then
                update_stage_changed(M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_COMING)
            elseif templateId == M.POLL_MSG_ID.MSG_TIPS_2 then
                update_stage_changed(M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_COMING_2)
            end
        elseif templateId == M.POLL_MSG_ID.MSG_FORBID_EXPERIENCE_TIME_END then -- 901003
            update_stage_changed(M.TIME_LIMIT_STAGE.EXPERIENCE_TIME_END)
        elseif templateId == M.POLL_MSG_ID.MSG_FORBID_TOTAL_TIME_END then  -- 901004
            --踢出
            E.LOG.debug(TAG, 'poll out !')
            current_poll_scene = M.POLL_SCENE.SCENE_KICK
            update_stage_changed(M.TIME_LIMIT_STAGE.PLAY_TOTAL_TIME_END)
        end
    else
        E.LOG.debug(TAG, 'msg is nil, do nothing,')
    end

    -- 在普通templateId之后再次按时间检查
    double_check_time_limit(timeCtl)
end

local function request_play_time_limit_from_server(msg_token, cb)
    local cur_connect_state = connect_state_instance.current_connect_state()
    if current_play_sec >= 0 and cur_connect_state == "connected" then
        current_play_sec = current_play_sec + heartbeat_interval_sec
    elseif current_play_sec < 0 then
        current_play_sec = 0
    end

    local service = M.SERVICE.CLOUD_MSG_CHECK
    local dsp_service = M.DSP_SERVICE_MAPPING[service]
    local params = {
        msgToken = msg_token,
        playSeconds = current_play_sec
    }

    E.LOG.debug(TAG, "cloud heartbeat play_time:" .. tostring(current_play_sec) .. ", interval:" .. tostring(heartbeat_interval_sec) .. ", cur_connect_state:" .. tostring(cur_connect_state))
    E.log(params)
    DSP.post(dsp_service, params, function(succ, ...)
        -- 停掉轮询之后， 可能还有一次请求没有返回，导致外部下载完成的逻辑又插入了试玩到期
        if poll_status == M.POLL_STATUS.STATUS_STOP then
            E.LOG.debug(TAG, 'poll state is stop')
            return
        end
        if current_poll_scene == M.POLL_SCENE.SCENE_NORMAL then
            if succ then
                local resp = ...
                -- process time ctrl resp
                --E.log("request_play_time_limit_from_server >>")
                --E.log(resp)
                on_handle_time_ctrl_info(resp.timeCtl, resp.nextInterval, resp.msg)
            else
                local code, message = ...
                E.LOG.error(TAG, 'get remain time error >> code:'.. code .. ', msg: ' .. message)
            end

        end

        E.LOG.debug(TAG, "time once next:" .. tostring(heartbeat_interval_sec))
        cb(succ, ...)
    end)
end

local function get_msg_token()
    -- 1. request
    -- get_cloud_config
    local server_config_data = CA.get_cloud_server_config()
    local msgToken = server_config_data.msgToken
    E.LOG.debug(TAG, "get token msg token >> " .. tostring(msgToken) .. "， env:" .. tostring(env))
    return msgToken
end

--启动轮询，查询试玩的剩余时间
function M.start_poll_time()
    local msg_token = get_msg_token()
    E.LOG.debug(TAG, "start_poll_time remain time interval is " .. heartbeat_interval_sec .. ", msgToken:" .. tostring(msg_token))
    local getLastTryTime
    getLastTryTime = function()
        if poll_status == M.POLL_STATUS.STATUS_STOP then
            is_polling = false
            return
        end
        E.LOG.debug(TAG, "start_poll_time, schedule next")
        request_play_time_limit_from_server(msg_token, function(succ, ...)
            E.LOG.debug(TAG, "start_poll_time, result:" .. tostring(succ))
            if poll_status == M.POLL_STATUS.STATUS_POLLING and current_poll_scene == M.POLL_SCENE.SCENE_NORMAL then
                E.Timer.once(heartbeat_interval_sec, getLastTryTime)
            end
        end)
    end

    poll_status = M.POLL_STATUS.STATUS_POLLING
    if not is_polling then
        is_polling = true
        getLastTryTime(M.POLL_SCENE.SCENE_NORMAL)
    else
        E.LOG.debug(TAG, 'is polling, return')
    end
end

function M.stop_poll_time()
    E.LOG.warn(TAG, "stop_poll_time begin")
    poll_status = M.POLL_STATUS.STATUS_STOP
end

function M.request_time_config(cb)
    E.LOG.debug(TAG, "request_time_config begin2")

    local msg_token = get_msg_token()
    request_play_time_limit_from_server(msg_token, cb)
end

-- 首次启动的时间信息可以从参数下发一起返回
function M.on_change_from_cloud_config()
    E.LOG.debug(TAG, "on_change_from_cloud_config")
    local server_config_data = CA.get_server_config_data()
    local play_time_info = server_config_data.playTimeInfo
    if not play_time_info or not play_time_info.timeCtl then
        E.LOG.warn(TAG, "on_change_from_cloud_config skip, no play_time_info in resp")
        return
    end

    E.LOG.debug(TAG, "on_change_from_cloud_config begin update time ctrl info")
    local next_interval = play_time_info.nextInterval or heartbeat_interval_sec
    on_handle_time_ctrl_info(play_time_info.timeCtl, next_interval)
end

function M.init()
    connect_state_instance = require "ejoysdk_lua.cloud_game.cloud_connect_statemachine"

    env = CA.get_cloud_env()
    DSP.set_env(DSP.ENV.RELEASE)
    if env == M.ENV.DEBUG then
        DSP.set_env(DSP.ENV.DEBUG)
    elseif env == M.ENV.PRE_RELEASE then
        DSP.set_env(DSP.ENV.PRE_RELEASE)
    end
end

function M.register_time_limit_state_changed(_state_change_listener)
    for _, handler in ipairs(state_change_listeners) do
        if handler == _state_change_listener then
            return
        end
    end

    state_change_listeners[#state_change_listeners + 1] = _state_change_listener
end

function M.current_state_info()
    return current_state_info
end

return M