---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hanami.
--- DateTime: 6/19/23 2:21 PM
---
local E = require 'ejoysdk_lua.ejoysdk'

local M = {}

local TAG = 'cloud_time_pass_ticker'

local last_remain_time
local current_remain_time_tick
local pass_time
local is_time_pass_loop_run = false
local local_next_interval = 0
local current_refresh_time

local time_pass_loop = function()
    if is_time_pass_loop_run then
        return
    end
    is_time_pass_loop_run = true
    local loop
    loop = function()
        E.Timer.once(1, function()
            if not is_time_pass_loop_run then
                E.LOG.debug(TAG, 'is_time_pass_loop_run is false')
                return
            end
            if pass_time > local_next_interval then
                is_time_pass_loop_run = false
                E.LOG.debug(TAG, 'pass_time > local_next_interval, stop loop >> ' .. tostring(pass_time) .. ', ' .. tostring(local_next_interval))
                return
            end
            pass_time = pass_time + 1
            -- 对tick的倒计时做一个修正，避免应用切后台太久停跳回来照成的误差较大
            -- 为避免设备系统时间被更改，只有在当前时间不超过下一个剩余时长的刷新周期时，才修正时间
            -- 如果当前时间超过了下一个剩余时长的刷新周期，则直接将时间更新到下一个刷新周期的剩余时长
                -- 这种情况发生在：1.切后台太久，2.大幅度向后修改系统时间
            local time_now = os.time()
            if time_now > current_refresh_time then
                local interval = time_now - current_refresh_time
                if interval < local_next_interval then
                    local offset = interval - pass_time
                    if offset > 5 then
                        E.LOG.debug(TAG, 'offset > 5 seconds, update pass time to ' .. tostring(interval))
                        pass_time = interval
                    end
                else
                    E.LOG.debug(TAG, 'time now is later than next interval >> ' .. tostring(local_next_interval))
                    pass_time = local_next_interval
                end
            end
            E.LOG.debug(TAG, 'pass_time >> ' .. tostring(pass_time) .. ', ' .. tostring(local_next_interval))
            loop()
        end)
    end
    loop()
end


function M.tick_remain_time(remain_time, next_interval, refresh_time)
    if local_next_interval ~= next_interval then
        E.LOG.debug(TAG, 'update next interval >> ' .. tostring(next_interval))
        local_next_interval = next_interval
    end
    if current_refresh_time ~= refresh_time then
        E.LOG.debug(TAG, 'update refresh time >> ' .. tostring(refresh_time))
        current_refresh_time = refresh_time
    end
    if remain_time <= 0 then
        E.LOG.debug(TAG, 'remain time <= 0, stop loop')
        current_remain_time_tick = 0
        is_time_pass_loop_run = false
        return 0
    end
    if not is_time_pass_loop_run then
        E.LOG.debug(TAG, 'is_time_pass_loop_run = false, start loop')
        time_pass_loop()
    end
    if remain_time ~= last_remain_time then
        last_remain_time = remain_time
        pass_time = 0
        current_remain_time_tick = remain_time
        return remain_time
    else
        current_remain_time_tick = remain_time - pass_time
        return current_remain_time_tick
    end
end


return M