---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gang.
--- DateTime: 3/31/23 4:30 PM
---

local E = require "ejoysdk_lua.ejoysdk"
local FLOW_TASK = require 'ejoysdk_lua.res.flow_task'
local SC = require "ejoysdk_lua.res.startup.startup_res_config"
local STAT = require "ejoysdk_lua.res.res_stat"
--local ER = require 'ejoysdk_lua.res.ejoysdk_res'
local END = require "ejoysdk_lua.res.ejoy_namespace_dispatcher"
local EL = require "ejoysdk_lua.res.ejoy_res_log"
local utils = require "ejoysdk_lua.ejoysdk_utils"
local UT = require "ejoysdk_lua.res.startup.modules.update_task"
--local ECC = require 'ejoysdk_lua.ejoysdk_config_center'
--local CONSTANTS = require 'ejoysdk_lua.ejoysdk_constants'

local MODULE_NAME = SC.STARTUP_CORE_MODULE_NAME.RES_UPDATE_CHECK
local TAG = MODULE_NAME
local M = FLOW_TASK:new(MODULE_NAME)

--local PATCH_PATH_EJOYSDK_LUA = E.LazyKeyStore:New("PATCH_PATH_EJOYSDK_LUA", false, false, false)
--local RES_TYPE_EJOY_LUA = "ejoysdk_lua"

local RES_UPDATING_STATE = {
    CHECKING = 0, -- 检查中
    UPDATE_COMPLETE = 1, -- 更新完成
    UPDATE_FAILED = -1 -- 更新失败
}

local updating_res_state = {}
local updating_tasks = {}
local startup_res_update_state = false -- 标记当前启动资源更新状态
--local lua_res_update_state = false -- lua 资源更新状态

local function namespace_res_key(namespace, res_key)
    return tostring(namespace) .. "@" .. tostring(res_key)
end

local function current_res_update_state(namespace, res_key)
    local k = namespace_res_key(namespace, res_key)
    return updating_res_state[k]
end

--[[
@param updating_state {@link RES_UPDATING_STATE}
--]]
local function update_res_updating_state(namespace, res_key, updating_state, update_complete_cb)
    if utils.is_text_empty(namespace) or utils.is_text_empty(res_key) then
        EL.LOG.warn(TAG, "update_res_updating_state skip for namespace or res_key is empty")
        return
    end

    EL.LOG.debug(TAG, "update_res_updating_state ns:" .. tostring(namespace) .. ", rk:" .. tostring(res_key) .. ", state:" .. tostring(updating_state))
    local key = namespace_res_key(namespace, res_key)
    updating_res_state[key] = updating_state

    -- checking update state
    --    CHECKING = 0, -- 检查中
    --    UPDATE_COMPLETE = 1 -- 更新完成
    local is_all_complete = true
    for _, state in pairs(updating_res_state) do
        if state ~= RES_UPDATING_STATE.UPDATE_COMPLETE then
            is_all_complete = false
            break
        end
    end

    local has_checking_task = false
    if is_all_complete then
        EL.LOG.debug(TAG, "update_res_updating_state all update complete, now cb succ")
        if update_complete_cb then
            update_complete_cb(true)
        end
    else
        for _, state in pairs(updating_res_state) do
            if state == RES_UPDATING_STATE.CHECKING then
                has_checking_task = true
                break
            end
        end
    end

    return is_all_complete, has_checking_task
end

function M:_check_res_update(cb)
    -- 启动时更新信息
    local startup_update_infos = SC.get_game_startup_res_update_infos()
    -- namespace对应的拓展信息
    local update_namespace_exts = SC.get_namespace_ext_infos()
    --- 本地namespace + res_key 对应的启动参数
    local local_res_params = SC.get_startup_local_res_infos()
    -- 游戏传入的启动参数和options
    local _startup_params, startup_update_opts = SC.get_game_startup_params()
    -- 兼容逻辑lua_resources的namespace仍然走旧协议
    local startup_update_complete = function(succ, ...)
        EL.LOG.debug(TAG, "_check_res_update_state update complete")
        startup_res_update_state = succ
        cb(succ, ...)
    end

    local is_force = SC.is_force_check_update()
    if startup_res_update_state and not is_force then
        EL.LOG.debug(TAG, "startup update has completed, return")
        startup_update_complete(true)
        return
    end

    EL.LOG.debug(TAG, "_check_res_update begin with startup_update_infos >>")
    E.log(startup_update_infos)

    if next(startup_update_infos) == nil then
        EL.LOG.debug(TAG, "no startup_update_infos, skip update, just return")
        startup_update_complete(true)
        return
    end

    EL.LOG.debug(TAG, "_startup_params >>>")
    E.log(_startup_params)
    -- here filter check complete ones, leave only checking res
    -- mark res updating
    local is_force_check_update = SC.is_force_check_update()
    if next(updating_res_state) == nil or is_force_check_update then
        for ns, res_map in pairs(startup_update_infos) do
            for rk, _ in pairs(res_map) do
                if _startup_params[ns] and _startup_params[ns][rk] then
                    update_res_updating_state(ns, rk, RES_UPDATING_STATE.CHECKING)
                end
            end
        end
    end

    local pending_update_infos = {}
    for ns, res_map in pairs(startup_update_infos) do
        for rk, uinfo in pairs(res_map) do
            --只关注本次更新的rk
            if _startup_params[ns] and _startup_params[ns][rk] then
                local cur_update_state = current_res_update_state(ns, rk)
                EL.LOG.debug(TAG, "rk: " .. tostring(rk) .. ', state is ' .. tostring(cur_update_state))
                if cur_update_state ~= RES_UPDATING_STATE.UPDATE_COMPLETE then
                    pending_update_infos[ns] = pending_update_infos[ns] or {}
                    pending_update_infos[ns][rk] = uinfo
                    update_res_updating_state(ns, rk, RES_UPDATING_STATE.CHECKING)
                end
            end
        end
    end

    EL.LOG.debug(TAG, "current pending update infos >>")
    E.log(pending_update_infos)
    self:_test_set_pending_list(pending_update_infos)

    if next(pending_update_infos) == nil then
        EL.LOG.debug(TAG, "pending_update_infos is empty")
        startup_update_complete(true)
        return
    end

    for ns, res_map in pairs(pending_update_infos) do
        update_namespace_exts = update_namespace_exts or {}
        local namespace_ext = update_namespace_exts[ns] or {}

        for _res_key, _update_info in pairs(res_map) do
            local ns_res_info = local_res_params[ns] or {}
            local res_info = ns_res_info[_res_key] or {}
            local using_res_info = res_info

            local task_key = namespace_res_key(ns, _res_key)
            local update_task = updating_tasks[task_key]
            if not update_task then
                local retry_times = 0
                local max_retry_times = SC.get_max_retry_times()
                local _update_state_listener = function(_ns, _rk, _state, _state_obj, ...)
                    EL.LOG.debug(TAG, "_update_state_listener ns:".. tostring(_ns) ..", rk:".. tostring(_rk) .. ", state:" .. tostring(_state))
                    E.log(_state_obj)
                    _state_obj = _state_obj or {}
                    if _state == UT.PUB_STATES.FINISH then
                        EL.LOG.debug(TAG, "state complete")
                        update_res_updating_state(_ns, _rk, RES_UPDATING_STATE.UPDATE_COMPLETE, startup_update_complete)
                    else
                        -- 单个资源失败，则整体更新失败/通知单个资源失败
                        if _state == UT.PUB_STATES.APPLY_FAILED or _state == UT.PUB_STATES.DOWNLOAD_FAILED or _state == UT.PUB_STATES.IDLE then
                            local err_code = _state_obj.err_code
                            local err_msg = _state_obj.err_msg
                            EL.LOG.warn(TAG, "resource process failed, ns:" .. tostring(_ns) .. ", rk:" .. tostring(_rk) .. ", state:" .. tostring(_state) .. ", code:" .. tostring(err_code) .. ", msg:" .. tostring(err_msg))
                            local _is_all_complete, has_checking_task = update_res_updating_state(_ns, _rk, RES_UPDATING_STATE.UPDATE_FAILED)
                            -- 如果没有更多更新中的资源，则返回整体失败
                            if not _is_all_complete and not has_checking_task then
                                EL.LOG.warn(TAG, "receive res err, now not is all complete and not has_checking_task, so notify on_global_failed, code:" .. tostring(err_code) .. ", msg:" .. tostring(err_msg))
                                startup_update_complete(false, err_code, err_msg)
                            else
                                local dispatch_retry_succ = END.dispatch_res_failed_retry_listener(_ns, _rk, function()
                                    EL.LOG.debug(TAG, "receive retry callback")
                                    -- 这里不使用reset，因为这里的reset不彻底，资源更新信息还是本地缓存的
                                    retry_times = retry_times + 1
                                    if retry_times > max_retry_times then
                                        EL.LOG.warn(TAG, "reach max retry times, now callback global failed")
                                        retry_times = 0
                                        startup_update_complete(false, err_code, err_msg)
                                    else
                                        update_task:start()
                                    end
                                end, err_code, err_msg)

                                if not dispatch_retry_succ then
                                    EL.LOG.warn(TAG, "game not override on_res_failed_retry_listener, so callback global failed")
                                    startup_update_complete(false, err_code, err_msg)
                                end
                            end
                        end
                    end
                end

                -- 1. check update task state, if all succ now run next
                -- 2. if one failed, notify failed（FIXME conio check if could notify more efficient）
                update_task = UT:New(ns, _res_key, _update_info, using_res_info, namespace_ext, _startup_params, startup_update_opts, _update_state_listener)
                updating_tasks[task_key] = update_task
            end

            STAT.stat_check_res_update_state_begin(ns, _res_key, is_force_check_update)
            if is_force_check_update then
                EL.LOG.debug(TAG, "is_force_check_update now do reset, ns:" .. tostring(ns) .. ", rk:" .. tostring(_res_key))
                update_task:reset(_update_info, using_res_info)
            else
                EL.LOG.debug(TAG, "now do start, ns:" .. tostring(ns) .. ", rk:" .. tostring(_res_key))
                update_task:start()
            end
        end
    end
end

--function M:_check_lua_res_update(cb)
--    local lua_update_result_handler = function(succ, ...)
--        -- update lua update state
--        lua_res_update_state = succ
--
--        if succ then
--            local ejoysdk_lua_res_path = ER.get_res_location(RES_TYPE_EJOY_LUA);
--            PATCH_PATH_EJOYSDK_LUA:set(ejoysdk_lua_res_path or "")
--
--            local res_config_data = ...
--            res_config_data = res_config_data or {}
--            local has_res_updated = res_config_data[ER.RES_CONFIG_KEY.KEY_RESOURCE_UPDATED] or false
--            local res_locations = ER.get_all_res_locations()
--
--            local result_data = {}
--            result_data["res_locations"] = res_locations
--            result_data["res_updated"] = has_res_updated
--
--            SC.update_lua_res_update_result(result_data)
--
--            E.LOG.debug(TAG, "init_app_start_res succ, res_updated:" .. tostring(has_res_updated) .. ", update url:" .. tostring(ejoysdk_lua_res_path))
--        else
--            SC.update_lua_res_update_result(nil)
--        end
--
--        cb(succ, ...)
--    end
--
--    local is_lua_update_enabled = SC.is_lua_res_update_enabled()
--    EL.LOG.debug(TAG, "_check_lua_res_update is_lua_update_enabled:" .. tostring(is_lua_update_enabled) .. ", lua_res_update_state:" .. tostring(lua_res_update_state))
--    if not is_lua_update_enabled then
--        EL.LOG.warn(TAG, "lua update not enable, skip")
--        lua_update_result_handler(true, {
--            [ER.RES_CONFIG_KEY.KEY_RESOURCE_UPDATED] = false
--        })
--        return
--    end
--
--    if not lua_res_update_state or SC.is_force_check_update() then
--        ER.res_update(ECC.NAMESPACE.LUA_RESOURCE, RES_TYPE_EJOY_LUA, function(succ, ...)
--            if not succ then
--                local code, _msg = ...
--                if code == CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_CACHE_NOT_SUPPORT then
--                    E.LOG.warn(TAG, "init_app_start_res with cache not support")
--                    -- STAT not support
--                    STAT.stat("res_update_warn", "not support", true)
--
--                    lua_update_result_handler(true, {
--                        [ER.RES_CONFIG_KEY.KEY_RESOURCE_UPDATED] = false
--                    })
--                    return
--                end
--            end
--            lua_update_result_handler(succ, ...)
--        end)
--    else
--        EL.LOG.debug(TAG, "lua res update already succ, directly return true")
--        cb(true)
--    end
--end

function M:_init(_module_mgr_instance)
    self._data = {
        module_instance = _module_mgr_instance
    }
end

function M:run()
    -- 1. 获取namespace对应的更新信息数组
    -- 2. 遍历检查更新
    -- 3. 遍历提交confirm and download(check and download move together)
    E.LOG.debug(TAG, "begin run")
    STAT.stat_update_check_begin()
    --local game_startup_res_update_succ_handler = function()
    --    self:_check_lua_res_update(function(succ, ...)
    --        if succ then
    --            EL.LOG.debug(TAG, "_check_lua_res_update succ")
    --            STAT.stat_update_check_end(true)
    --            self:run_next()
    --        else
    --            local code, msg = ...
    --            EL.LOG.warn(TAG, "_check_lua_res_update failed, code:" .. tostring(code) .. ", msg:" .. tostring(msg))
    --            STAT.stat_update_check_end(false, code, msg)
    --            self._data.module_instance.on_global_failed(code, msg)
    --        end
    --    end)
    --end

    self:_check_res_update(function(succ, ...)
        if succ then
            EL.LOG.debug(TAG, "_check_res_update succ, now run next")
            STAT.stat_update_check_end(true)
            self:run_next()
        else
            local code, msg = ...
            E.LOG.debug(TAG, "_check_res_update failed, code:" .. tostring(code) .. ", msg:" .. tostring(msg))
            STAT.stat_update_check_end(false, code, msg)
            self._data.module_instance.on_global_failed(code, msg)
        end
    end)
end

function M:_test_set_pending_list(_pending_update_infos)
    -- do nothing here
end

return M