---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hufeng.
--- DateTime: 2021/5/8 4:47 下午
---

local API = require "ejoysdk_lua.user_center.usercenter_api"
local E = require "ejoysdk_lua.ejoysdk"
local EM = require "ejoysdk_lua.ejoysdk_module"

local TAG = EM.MODULE.REALNAME .. 'heartbeat'

local M = {}

local global_ptoken = nil  -- 用于保存替换后的ptoken
local global_check_time_gap = 60*2 --默认2分钟循环一次
local loop_time_gap = global_check_time_gap -- 轮询时间间隔,
local expired_time_gap = 60*30 -- 提前多久去换token --60*60*22+60*59

local is_excuting = false
local is_need_stop = false
local function exchange_ptoken_HTTP_Request()
    local EG = require 'ejoysdk_lua.ejoysdk_gangplank'
    local userInfo = EG.user_info()
    local params = {
        token = global_ptoken or (userInfo.ptoken or ''),
    }

    API.user_center_replace_ptoken(params, function(succ, ...)
        if succ then
            E.LOG.debug(TAG, 'user_center_replace_ptoken success -----')
            local data = ...
            E.LOG.debug(TAG, data)
            if data and data.token then
                global_ptoken = data.token
            end
        else
            E.LOG.debug(TAG, 'user_center_replace_ptoken failed -----')
            local code, msg = ...
            E.LOG.debug(TAG, 'code = '..tostring(code)..', msg = '.. tostring(msg))
        end
    end)

end





local function headrtbeat_HTTP_Request()
    if is_need_stop then
        E.log('已暂停心跳--')
        return
    end

    if is_excuting then
        E.log('同时只执行一次心跳就好，避免多次调用导致心跳多次')
        return
    end

    is_excuting = true

    local EG = require 'ejoysdk_lua.ejoysdk_gangplank'
    local tempRoleId = ''
    local tempServerId = ''
    local tempPToken = ''
    local tempPlatform = ''
    local userInfo = EG.user_info()
    local playerInfo = EG.player_info()
    if userInfo and playerInfo  then
        tempRoleId = playerInfo.player_id or '' --角色id
        tempServerId = playerInfo.server_id or ''
        tempPToken = global_ptoken or (userInfo.ptoken or '') -- 仅对pc这个接口而言，传uid给家铭，因为它就是account_id，家铭可以根据这个映射到ptoken
    end

    if userInfo and userInfo.pinfo and userInfo.pinfo.platform then
        tempPlatform = userInfo.pinfo.platform
    end

    --E.log('userInfo is ----')
    --E.log(userInfo)
    --E.log('playerInfo is -----')
    --E.log(playerInfo)

    local params = {
        token = tempPToken,
        serverId = tempServerId,
        roleId = tempRoleId,
        platform = tempPlatform,
        scene = 201 -- entergame进入游戏
    }

    --E.log('params----- heartbeat start')
    --E.log(params)

    API.user_center_heartbeat(params, function(succ, ...)
        if succ then
            E.log('heartbeat success -----')
            local data = ...
            if data then
                --E.log(data)
                if data.checkPeriod then
                    -- 更新定时器间隔
                    local tempValue = tonumber(data.checkPeriod) -- 单位是秒
                    if tempValue and tempValue > 0 then
                        loop_time_gap = tempValue
                    end
                else
                    loop_time_gap = global_check_time_gap -- 恢复成最初的轮询间隔
                end

                if data.serverTime and data.tokenExpiredTime then
                    local validTime = (tonumber(data.tokenExpiredTime)  - tonumber(data.serverTime))/1000 --单位是毫秒
                    E.log('validTime = ' .. tostring(validTime))
                    E.log('expired_time_gap = '.. tostring(expired_time_gap))
                    if validTime <= expired_time_gap then
                        -- token过期前sdk提前去换token
                        exchange_ptoken_HTTP_Request()
                    end
                end
            end

        else

            E.log('heartbeat failed -----')
            local code, msg = ...
            E.log('code = '..tostring(code)..', msg = '..msg)
            if code == 4001003 then
                E.log("此错误码表示ptoken过期了，需要停止轮询")
                M.heartbeat_stop()
            end
        end

        -- 无论网络成功或失败，就进行轮询，避免因为偶然的网络失败而导致轮询停止
        E.Timer.once(loop_time_gap, function()
            is_excuting = false -- 恢复标志位
            headrtbeat_HTTP_Request()
        end)
    end)

end

-- 是否支持lua心跳
local function use_lua_heartbeat()

    -- aligames带了Native心跳，Android扫码包无aligames心跳
    if E.Sysinfo.os() ~= 'windows' then
        -- 非扫码包(理论过打包系统Android才会有这个字段，这里iOS不做os限制，后面如需要iOS扫码包可直接兼容)
        if not E.is_scan_pkg() then -- Android扫码包兼容
            E.log('当前设备不是Windows/Android扫码包, 不用走心跳的逻辑，直接返回')
            return false
        end
    end

    local CG = require('ejoysdk_lua.cloud_game.cloud_config')

    -- TODO:需要在云游上面测试，
    local pkgInfo = E.get_pkg_info()
    if pkgInfo.cloud_game_mode and pkgInfo.cloud_game_mode == CG.CLOUD_MODE.CLOUD then
        E.log('云微端不需要心跳，直接返回')
        return false
    end


    if E.CONFIG.get_config(E.CONFIG.KEY.MULTI_REGIONS_ENABLED) then
        E.log("PC海外地区不需要心跳，直接返回")
        return false
    end

    return true
end

function M.heartbeat_start()
    
    if not use_lua_heartbeat() then
        return
    end

    is_need_stop = false -- 恢复标志位


    pcall(headrtbeat_HTTP_Request)

end



function M.heartbeat_stop()
    -- 在角色退出游戏时调用，exitGame
    is_need_stop = true

end



return M
