---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pangang.
--- DateTime: 2021/10/12 4:27 PM
---

local E = require "ejoysdk_lua.ejoysdk"
local ET = require "ejoysdk_lua.ejoysdk_topic"
local EM = require "ejoysdk_lua.ejoysdk_module"

local TAG = EM.MODULE.REALNAME .. "adult_limit"
-- realname_info结构
-- 文档链接：https://yuque.antfin.com/mxb7qq/confluence-sdkdev-vg6uys/28808027
--[[
"realNameInfo":{
                    "ex":{
                        "page_version":"1.0",
                        "biz_id":"2100000234",
                        "app_id":"9cc708b148794ff5a0f40340663d3db1",
                        "game_id":"10000100"
                    },
                    "antiAddictionStatus":1,
                    "verifyStatus":1,
                    "di":"",
                    "accountType":0,
                    "pi":"",
                    "personId":"322509384",
                    "payLimitZone":-1,
                    "realNameStatus":1,
                    "adult":1,
                    "antiAddictionStatusReason":""
                }
--]]

--[[
0 未知
1 已成年
2 未成年
--]]
local ADULT_STATUS = {
    UNKNOWN = 0,
    ADULT = 1,
    CHILD = 2
}

local ENV = {
    RELEASE = "RELEASE",
    TEST = "TEST"
}

local CHILD_LIMIT_PAGE = {
    [ENV.RELEASE] = "https://act.lingxigames.com/anti-addiction/#/nonage_tips",
    [ENV.TEST] = "http://render-test.aligames.com/common/anti_nonage_tips/index.html"
}

local current_env = ENV.RELEASE
local child_limit_page_url = CHILD_LIMIT_PAGE[current_env]
local current_realname_info = nil
local M = {}

local function handle_child_acquire_succ(_user_info)
    -- show limit dialog
    local params = {
        realNameInfo = current_realname_info
    }

    local function on_js_callback(value)
        E.LOG.debug(TAG, 'on_js_callback >>')
        E.LOG.debug(TAG, value)
    end

    local function on_close_callback(value)
        E.LOG.debug(TAG, 'on_close_callback >>')
        E.LOG.debug(TAG, value)
    end

    E.open_webview(child_limit_page_url, {}, params, nil, on_js_callback, on_close_callback)
end

local function reset_child_check_status()
    current_realname_info = nil
    ET.unsubscribe(ET.gangplank.ACQUIRE, handle_child_acquire_succ)
    E.LOG.debug(TAG, "cancel listen acquire succ")
end

-- 检查未成年限制相关的业务
function M.check_child_limit(realname_info, is_enter_game_tips)
    -- first reset child check status
    reset_child_check_status();

    if not realname_info or next(realname_info) == nil then
        E.LOG.debug(TAG, "check_adult_limit skip, realname info is nil")
        return
    end

    local adult_status = realname_info.adult
    local needShowChildDialog = (adult_status == ADULT_STATUS.CHILD)
    E.LOG.debug(TAG, "check_adult_limit needShowChildDialog:" .. tostring(needShowChildDialog))

    current_realname_info = realname_info

    if is_enter_game_tips and needShowChildDialog then
        -- listen acquire succ listener
        ET.subscribe(ET.gangplank.ACQUIRE, handle_child_acquire_succ)
        E.LOG.debug(TAG, "begin listen acquire succ")
    end
end

return M