---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ligs.
--- DateTime: 2020-07-08 16:13
---
---
local file = require "ejoysdk_lua.ejoysdk_file"

local M = {}

function M.download_file(url, opts, cb)
    -- 没有回调，调用方执行该方法就没意义，可以直接return
    if not cb or type(cb) ~= 'function' then
        return
    end

    file.download_file(url, opts, function(succ, ...)
        if succ then
            local body = ...
            body = body or {}
            cb({code=200, msg='succ', data=body})
        else
            local code, msg = ...
            code = code or 0
            msg = msg or 'fail'
            cb({code=code, msg=msg})
        end
    end)
end

return M
