---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ali.
--- DateTime: 6/21/22 2:01 PM
---

local DIF = require "ejoysdk_lua.res.ui.download_ui_presenter_interface"
local PUSH = require "ejoysdk_lua.push.ejoysdk_push"
local E = require "ejoysdk_lua.ejoysdk"
local RTM = require "ejoysdk_lua.res.model.ejoy_res_type_model"
local Lang = require 'ejoysdk_lua.lang.util' 

local VENDOR_NAME = "ANDROID_NOTIF"
local M = DIF:Inherit(VENDOR_NAME)

local TAG = "download_android_notif_presenter"

local _notify_id = PUSH.NOTIFY_ID_SDK_INNER.NOTIFY_ID_FOREGROUND_SERVICE
local last_log_progress = -1

M.NOTIFICATION_ACTION = {
    ACTION_INVOKE_LUA = "ACTION_INVOKE_LUA", -- 调用lua
    ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE" -- 停止服务
}

function M.present_download_complete(progress_info)
    local _title = Lang.getString('noti_download_finish_title', '游戏资源下载完成')
    local _local_text = Lang.getString('noti_download_finish_desc', '请点击切换游戏完整版本体验~')

    local task_info = {
        title = _title,
        left_text = _local_text,
        right_text = "",
        task_status = 1,
        task_id = _notify_id,
        task_status_icon = "", -- 下载完成通过通知栏可以拉起游戏，需要lua拉起。另外对于后台activity拉起页面有权限问题
        progress = progress_info.progress,
        progress_visibility = false
    }

    local ext = {
    }

    PUSH.update_foreground_service_notification(task_info, ext, true)
end

function M.present_downloading(progress_info)
    local _title_txt_placeholder = Lang.getString('noti_downloading_title', '游戏资源下载中：${progress}%')
    local _speed_txt_placeholder = "${speed} KB/s"
    local _progress_txt_placeholder = "${downloading_size_in_mega}/${total_size_in_mega}M"

    local downloading_size_in_mega = progress_info.downloading_size / 1024 / 1024
    downloading_size_in_mega = string.format("%.1f", downloading_size_in_mega)
    local total_size_in_mega = progress_info.total_size / 1024 / 1024
    total_size_in_mega = string.format("%.1f", total_size_in_mega)
    local _right_text = string.gsub(_progress_txt_placeholder, "${downloading_size_in_mega}", tostring(downloading_size_in_mega))
    _right_text = string.gsub(_right_text, "${total_size_in_mega}", tostring(total_size_in_mega))

    local speed_format_txt = string.format("%.1f", progress_info.speed)
    local _local_text = string.gsub(_speed_txt_placeholder, "${speed}", tostring(speed_format_txt))
    local _title = string.gsub(_title_txt_placeholder, '${progress}', tostring(progress_info.progress))

    local task_info = {
        title = _title,
        left_text = _local_text,
        right_text = _right_text,
        task_status = 1,
        task_action = M.NOTIFICATION_ACTION.ACTION_STOP_SERVICE,
        task_id = _notify_id,
        task_status_icon = "epn_stop_service",
        progress = progress_info.progress
    }

    local ext = {
        --module = "cloud_game.cloud_manager",
        --func = "exit_cloud_game_app"
    }

    if last_log_progress ~= progress_info.progress then
        _ejoysdk.log("present_download_progress:" .. tostring(progress_info.progress) .. ", downloading_size:" .. tostring(downloading_size_in_mega) .. ", total_size:" .. tostring(total_size_in_mega))
    end

    PUSH.update_foreground_service_notification(task_info, ext, false)
end

function M.present_download_progress(progress_info)
    if progress_info.state == RTM.DOWNLOAD_STATE.COMPLETE then
        E.LOG.debug(TAG, "present_download_progress complete")
        M.present_download_complete(progress_info)

        -- begin stop foreground
        PUSH.stop_notification_service_foreground()
    else
        --E.LOG.debug(TAG, "present_download_progress downloading")
        M.present_downloading(progress_info)
    end
end

function M.setup_passive_mode_progress_presenter_info(progress_info, _downloading_list_info, _opts)
    local _noti_title = Lang.getString('noti_download_finish_title', '游戏资源下载完成')
    local _noti_local_text = Lang.getString('noti_download_finish_desc', '请点击切换游戏完整版本体验~')
    local _title_txt_placeholder = Lang.getString('noti_downloading_title', '游戏资源下载中：${progress}%')
    local _title_txt_static = Lang.getString('noti_downloading_static_title', '游戏资源下载中')

    local _speed_txt_placeholder = "${speed} KB/s"
    local _progress_txt_placeholder = "${downloading_size_in_mega}/${total_size_in_mega}M"

    local _downloading_size_in_mega = progress_info.downloading_size / 1024 / 1024
    _downloading_size_in_mega = string.format("%.1f", _downloading_size_in_mega)
    local _total_size_in_mega = progress_info.total_size / 1024 / 1024
    _total_size_in_mega = string.format("%.1f", _total_size_in_mega)

    local progress_presenter_info = {
        progress_info = progress_info,
        present_info = {
            task_id = _notify_id,
            title_txt_static = _title_txt_static,
            title_txt_placeholder = _title_txt_placeholder,
            left_txt_placeholder = _speed_txt_placeholder,
            right_txt_placeholder = _progress_txt_placeholder,
            complete_title_txt_placeholder = _noti_title,
            complete_left_txt_placeholder = _noti_local_text,
            complete_right_txt_placeholder = ""
        },
        present_info_data = {
            progress = progress_info.progress,
            speed = progress_info.speed,
            downloading_size_in_mega = _downloading_size_in_mega,
            total_size_in_mega = _total_size_in_mega
        },
        present_info_convert = {
            downloading_size_in_mega = {
                origin_key = "downloading_size",
                target_unit = "mega"
            },
            total_size_in_mega = {
                origin_key = "total_size",
                target_unit = "mega"
            }
        },
        downloading_list_info = _downloading_list_info,
        opts = _opts -- 标记为仅native更新
    }

    PUSH.setup_passive_mode_progress_presenter_info(progress_presenter_info)
end


return M