---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hufeng.
--- DateTime: 2022/7/21 下午5:02
--- 轻舟管理模块，对接配置中心和下载组件，主要对接h5部分的资源
local E = require 'ejoysdk_lua.ejoysdk'
local ECC = require 'ejoysdk_lua.ejoysdk_config_center'
local JSON = require 'ejoysdk_lua.ejoysdk_json'
local VER_CHECK = require 'ejoysdk_lua.ejoysdk_version_check'
local CONSTANTS = require 'ejoysdk_lua.ejoysdk_constants'
local ERF = require "ejoysdk_lua.res.base_ejoysdk_res"
local ET = require 'ejoysdk_lua.ejoysdk_topic'
local utils = require "ejoysdk_lua.ejoysdk_utils"
--local WebviewManager = require "ejoysdk_lua.ejoysdk_webview_manager" -- 这里不应该耦合webview逻辑
local HRU = require "ejoysdk_lua.res.ejoy_http_res_utils"
local RTM = require "ejoysdk_lua.res.model.ejoy_res_type_model"
local TAG =  "ejoysdk_lightboat"
local RES_BUILTIN_PATH = 'ejoysdk_lightboat_res'
local RES_CONFIG = 'config'
local pkg_webview_data_size = 0

local M = {}

local ecc_config_data_cache = {} -- 配置中心的数据缓存，有内存缓存就足够了，配置中心自己有磁盘缓存
--local backup_server_domains = {} -- 备选的文件下载域名列表，下载超时的时候使用
local webview_url_to_file_path_cache = {} -- 网页域名和本地文件路径的映射表
local webview_url_path_table_cache = {}
local pkg_webview_data_cache = {} -- 包内webview资源配置缓存

local function stat(action, key, succ, params)
    local ejoysdk_stat = require 'ejoysdk_lua.ejoysdk_stat'
    E.LOG.debug(TAG, "action=" .. tostring(action) .. ', key=' .. tostring(key) .. ', succ=' .. tostring(succ or 'nil'))
    ejoysdk_stat.stat_action(action, key, succ, params)
end

local function get_webview_cache_file_path()
    return RES_BUILTIN_PATH .. '/' .. RES_CONFIG
end

local function load_webview_cache_config()
    local json_str = E.File.readfile(get_webview_cache_file_path())
    E.LOG.debug(TAG, ', json_str = '..tostring(json_str))
    if json_str and string.len(json_str) > 0 then
        webview_url_to_file_path_cache = JSON.decode(json_str) or {}
    else
       webview_url_to_file_path_cache = {}
    end
end

-- 加载包内webview缓存
local function load_pkg_webview_cache_config()
    local base_path = RES_BUILTIN_PATH
    local qz_h5_config = base_path .. '/' .. RES_CONFIG
    local assets_qz_h5_config_content = _ejoysdk.lread(qz_h5_config)
    E.LOG.debug(TAG, "assets qz_h5_config_content is " .. tostring(assets_qz_h5_config_content))
    if assets_qz_h5_config_content and assets_qz_h5_config_content ~= '' then
        local qz_h5_list = E.Utils.split_string(assets_qz_h5_config_content, '\n')
        local index = 0
        for _, qz_h5_rk in pairs(qz_h5_list) do
            local qz_h5_res_config_path = base_path .. '/' .. qz_h5_rk .. '/' .. RES_CONFIG
            local assets_qz_res_config_content = _ejoysdk.lread(qz_h5_res_config_path)
            local assets_qz_res_config = JSON.decode(assets_qz_res_config_content) or {}
            E.LOG.debug(TAG, qz_h5_rk .. ' h5 res config is >>>')
            E.LOG.debug(TAG, assets_qz_res_config)
            local urls = assets_qz_res_config.urls
            --没有url配置认为无效
            if urls and next(urls) then
                for _, url in ipairs(urls) do
                    local code = E.Utils.url_clipping(url)
                    --code, version, res_key / res_key.zip
                    pkg_webview_data_cache[code] = assets_qz_res_config
                    index = index + 1
                end
            else
                E.LOG.debug(TAG, 'qz res config is invalid, skip cache, key is ' .. tostring(qz_h5_rk))
            end
        end
        pkg_webview_data_size = index
    end
end

-- START H5资源本地映射
-- code是URL去掉HTTP协议投和query之后的完整字符串，local_path是webview可直接打开的本地完整路径
local function set_local_path_to_url_code(code, local_path)
    if not code or not local_path then
        return
    end

    if not webview_url_path_table_cache[code] then
        E.LOG.debug(TAG, 'set path for code, code = '..code..', path = '..local_path)
    else
        E.LOG.debug(TAG, 'code already has local_path cache, code = '..code..', old path = '..webview_url_path_table_cache[code] ..' new path = '..local_path)

    end

    webview_url_path_table_cache[code] = local_path

end

local function remove_local_path_with_url_code(code)
    if code then
        webview_url_path_table_cache[code] = nil
        E.LOG.debug(TAG, 'remove code cache, code is ' .. tostring(code))
    end
end

--local function remove_all_cache_local_paths()
--    webview_url_path_table_cache = {}
--end

-- 保存根目录上的配置文件
local function save_webview_cache_config_to_disk()
    local str = JSON.encode(webview_url_to_file_path_cache)
    E.LOG.debug(TAG, "str=" .. tostring(str))
    -- 该函数会自己拼接document目录的前缀，所以只需要有后续的文件夹就行
    E.File.writefile(get_webview_cache_file_path(), str, false)
end
-- END H5资源本地映射

-- 查找最大版本号所对应的path
local function get_latest_version(path_table)
    local max_version = nil

    if path_table and type(path_table) == 'table' then
        for version, _temp_path in pairs(path_table) do
            if not max_version then
                max_version = version
            else
                if VER_CHECK.compare_versions(max_version, version) < 0 then
                    max_version = version
                end
            end
        end
    end

    return max_version
end

local function get_latest_version_with_code(code)
    if not code then
        return nil
    end

    local code_table = webview_url_to_file_path_cache[code]
    if not code_table then
        return nil
    end

    local paths = code_table.paths
    return get_latest_version(paths)
end

-- 处理更新请求
local function update_resource_with_config(res_info, local_res_latest_version, invalid_res_key_table, cb)
    local stat_action = 'webview_preload_download'
    local config_info = res_info.config_info

    E.LOG.debug(TAG, ' update_resource_with_config-------called')
    local res_key = config_info.key -- 目前这个key一定存在，但是后续其他业务则不一定有
    if not res_key then
        E.LOG.debug(TAG, 'res_info.key is nil, can not to download file, return now, res_info.url')
        return
    end

    -- 这里暂时用key来做唯一标识符，目前是可以的，后面别的业务也需要保证同一个namespace下key是唯一的
    local base_path = RES_BUILTIN_PATH .. '/' .. res_key .. '/'
    local ext_file_dir = E.File.get_ext_file_dir()
    local unzip_path = base_path .. config_info.version -- 解压缩到的位置
    unzip_path = string.format("%s/%s", ext_file_dir, unzip_path)
    local notify = function(succ, ...)
        if cb then
            cb(succ, ...)
        end
    end

    if config_info.restrict then
        -- 严格模式下，把本地的旧版本给忽略掉，在新版本下载完成前让用户加载远端URL
        -- 否则可以在更新结束前正常加载（有本地用本地无本地用远程）, 因为版本号不同，资源目录不同，在打开本地资源时更新不会导致问题
        -- 等更新结束后指标识统一指向新资源地址，旧的资源下次初始化时清理删除
        for _, code in ipairs(res_info.codes) do
            local code_local_latest_version = get_latest_version_with_code(code)
            if VER_CHECK.compare_versions(config_info.version, code_local_latest_version) > 0 then
                remove_local_path_with_url_code(code)
            end
        end
    end

    --
    ---- 使用替补域名重新下载
    stat(stat_action..'_start', res_key)

    local qz_h5_engine_handler = {
        on_res_apply = function(_res_key, _res_location, _res_state_infos, apply_cb)
            local file_list_info = _res_state_infos[RTM.INFO_TYPE_KEY.TYPE_PENDING_FILE_LIST_INFO] or {}
            if file_list_info[1] == nil or  file_list_info[1].name == nil then
                apply_cb(false, CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_GET_FILE_NAME_FAILED, "资源文件名获取失败")
                return
            end
            local file_name = file_list_info[1].name
            local zip_save_path = E.Utils.trim_end(_res_location, '/') .. '/' .. file_name
            E.LOG.debug(TAG, "下载路径为: " .. tostring(zip_save_path))
            stat(stat_action .. '_unzip', res_key)
            E.File.unzip_full_path(zip_save_path, unzip_path, function(ret)
                if ret.succ then
                    E.LOG.debug(TAG, tostring(res_key) .. " 解压成功")
                    local server_path = config_info.path
                    if E.Utils.start_with(server_path, './') then
                        server_path = string.sub(server_path, 2, -1)
                    end
                    if not E.Utils.start_with(server_path, '/') then
                        server_path = '/' .. server_path
                    end

                    -- 存储的是本地H5文件所在的相对于document文件夹的路径，不能存储完整路径，因为iOS覆盖安装会变
                    local local_file_path = unzip_path .. server_path
                    E.LOG.debug(TAG, ' 本地文件路径为 = '.. local_file_path)
                    local_file_path = E.Utils.trim_start(local_file_path, ext_file_dir)
                    local_file_path = E.Utils.trim_start(local_file_path, "/")
                    E.LOG.debug(TAG, ' 本地文件相对路径为 = '.. local_file_path)
                    -- 更新到webview配置表里去
                    for _, code in ipairs(res_info.codes) do
                        local latest_version = get_latest_version_with_code(code)
                        if VER_CHECK.compare_versions(config_info.version, latest_version) > 0 and VER_CHECK.compare_versions(config_info.version, invalid_res_key_table[code]) > 0 then
                            E.LOG.debug(TAG, "download_version is valid, now refresh local data")
                            local temp_table = config_info
                            local path_table
                            if webview_url_to_file_path_cache[code]  then
                                -- 可能存在旧版本，就需要取出来旧版本的值，同时更新一部分值到新版本
                                local temp = utils.deepcopy(webview_url_to_file_path_cache[code])
                                path_table = temp.paths or {}
                            else
                                path_table = {}
                            end

                            -- 增加新的版本号映射
                            path_table[config_info.version] = local_file_path
                            temp_table.paths = path_table
                            webview_url_to_file_path_cache[code] = temp_table
                            set_local_path_to_url_code(code, local_file_path)
                        end
                    end

                    -- 保存到内存里
                    -- 这里要把网页code和本地路径的映射保存起来，内存存一分，然后磁盘也存一份
                    save_webview_cache_config_to_disk()
                    apply_cb(true)
                else
                    E.LOG.debug(TAG, tostring(res_key) .. " 解压失败")
                    stat(stat_action .. '_unzip', res_key, false)
                    apply_cb(false, CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_UNZIP_FAILED, ret.msg)
                end
                E.File.remove_fullpath(zip_save_path) -- 删除zip文件
            end)
        end
    }

    local current_res_info = {
        res_key = res_key,
        engine_handler = qz_h5_engine_handler,
        --把本地版本传递过去
        version = local_res_latest_version
    }

    local _on_confirm_res_update_handler = function(_res_key, res_state_info, confirm_update_cb)
        local update_info = res_state_info[ERF.RES_STATE_INFOS.TYPE_RES_UPDATE_STATE] or {}
        local update_ver = update_info[ERF.UPDATE_INFO_KEY.VERSION_NAME]
        local has_new_update = update_info[ERF.UPDATE_INFO_KEY.HAS_NEW_UPDATE] or false
        E.LOG.debug(TAG, "on_receive_res_update_confirm, res_key:" .. tostring(res_key) .. ", ver:" .. tostring(update_ver))
        if has_new_update then
            confirm_update_cb(true)
            E.LOG.debug(TAG, "on_receive_res_update_confirm has update, confirm true")
        else
            confirm_update_cb(false)
            E.LOG.debug(TAG, "on_receive_res_update_confirm has not update, confirm false")
        end
    end

    local on_res_update_complete_handler = function(update_result, ...)
        if update_result then
            E.LOG.debug(TAG, "res_key: " .. tostring(res_key) .. ' 下载成功')
            notify(true, config_info)
            stat(stat_action .. '_unzip', res_key, true)
        else
            E.LOG.debug(TAG, "res_key: " .. tostring(res_key) .. ' 下载失败')
            local code, msg = ...
            notify(false, code, msg, config_info)
            stat(stat_action, res_key, false)
        end
    end

    local listeners = {
        on_confirm_res_update = _on_confirm_res_update_handler,
        on_res_update_complete = on_res_update_complete_handler
    }

    local opts = {
        [ERF.NAMESPACE_UPDATE_OPTIONS.FOREGROUND_NOTIFICATION_ENABLED] = false,
        [ERF.NAMESPACE_UPDATE_OPTIONS.USING_CC_CACHE_DATA] = true
    }

    ERF.check_and_update(ECC.NAMESPACE.MARKET_H5_RESOURCE, current_res_info, opts, listeners)

end


-- 寻找父目录，返回不带斜杆结尾的路径
local function find_parent_folder(path)
    if not path or string.len(path) == 0 then
        return path
    end

    if E.Utils.end_with(path, '/') then
        path = string.sub(path,1,string.len(path)-1)
    end

    local full_url = path
    local temp = string.reverse(full_url)
    local i = string.find(temp,"/")
    if i ~= nil and i > 0 then
        local offset = string.len(full_url) - i +1
        return string.sub(full_url,1, offset)
    end

    return path
end



-- 判断当前的native APP版本是否支持资源更新的功能，以及是否有必要去检查资源功能
local function is_support_use_local_res(key)
    local pkg_info = E.get_pkg_info()
    local has_cache = ecc_config_data_cache and key and ecc_config_data_cache[key] ~= nil and next(ecc_config_data_cache[key])-- 配置中心有下发且不为空才能开启
    local is_device_support = has_cache
            and E.File.is_support_handling_file_cache() --避免native是低版本
            -- 判断 ios 10 以上才开启, 涉及CORS
            and (pkg_info.os ~= 'android' or (pkg_info.os == 'android' and VER_CHECK.compare_versions(pkg_info.versions.os_version, 23) >= 0))
            and (pkg_info.os ~= 'ios' or (pkg_info.os == 'ios' and VER_CHECK.compare_versions(pkg_info.versions.os_version, "10.0") >= 0))

    return is_device_support
end

local function check_webview_cache(cb)
    local index = 0
    local total_size = pkg_webview_data_size
    E.LOG.debug(TAG, 'total size is ' .. tostring(total_size))
    if total_size == 0 then
        cb()
        return
    end
    local cb_wrapper = function()
        if index == total_size then
            --这里保存一次
            save_webview_cache_config_to_disk()
            cb()
        end
    end
    -- 资源key释放的缓存，释放过则不用再释放
    local cache_release_res = {}

    for code, _ in pairs(pkg_webview_data_cache) do
        index = index + 1
        local cache_config_info = webview_url_to_file_path_cache[code] or {}
        local latest_version = cache_config_info.version
        local code_pkg_webview_data = pkg_webview_data_cache[code] or {}
        local code_version = code_pkg_webview_data.version
        E.LOG.debug(TAG, code .. ', latest version is ' .. tostring(latest_version) .. ', pkg version is ' .. tostring(code_version))
        local code_pkg_res_key = code_pkg_webview_data.res_key
        --包内的版本大于包外，需要解压
        if VER_CHECK.compare_versions(code_version, latest_version) > 0 then
            local base_path = RES_BUILTIN_PATH .. '/' .. code_pkg_res_key .. '/'
            local unzip_path = base_path .. code_version -- 解压缩到的位置
            local bundle_zip_path = RES_BUILTIN_PATH .. '/' .. code_pkg_res_key .. '/' .. code_version .. '.zip'
            local handler_release_bundle_res = function(_unzip_path)
                if not webview_url_to_file_path_cache[code] then
                    webview_url_to_file_path_cache[code] = {}
                end
                -- 如果包外没资源，只有包内，则默认开；如果包外有资源开关，则对比版本，认高的，这里认高的也是开
                local activeStatus = code_pkg_webview_data.activeStatus
                if activeStatus == nil then
                    activeStatus = 1
                end
                webview_url_to_file_path_cache[code] = webview_url_to_file_path_cache[code] or {}
                webview_url_to_file_path_cache[code].activeStatus = activeStatus
                webview_url_to_file_path_cache[code].paths = webview_url_to_file_path_cache[code].paths or {}
                webview_url_to_file_path_cache[code].key = code_pkg_res_key
                webview_url_to_file_path_cache[code].version = code_version
                local path = code_pkg_webview_data.path
                webview_url_to_file_path_cache[code].path = path
                local real_path = _unzip_path .. tostring(path)
                --real_path = string.format("%s/%s", E.File.get_ext_file_dir(), real_path)
                webview_url_to_file_path_cache[code].paths[code_version] = real_path
                E.LOG.debug(TAG, 'set code ' .. tostring(code) .. ', version is ' .. tostring(code_version) .. ', path is ' .. tostring(real_path))
                E.LOG.debug(TAG, webview_url_to_file_path_cache[code].paths)
            end

            if cache_release_res[code_pkg_res_key] then
                E.LOG.debug(TAG, "this res_key has release, do not release again, now set new code config")
                handler_release_bundle_res(cache_release_res[code_pkg_res_key])
                cb_wrapper()
            else
                cache_release_res[code_pkg_res_key] = unzip_path
                E.File.release_bundle_res(bundle_zip_path, bundle_zip_path, function(release_ret)
                    if release_ret.succ then
                        E.LOG.debug(TAG, "res_key: " .. tostring(code_pkg_res_key) .. ' 释放成功')
                        E.File.unzip(bundle_zip_path, unzip_path, function(ret)
                            if ret.succ then
                                handler_release_bundle_res(unzip_path)
                            else
                                E.LOG.debug(TAG, "res_key: " .. tostring(code_pkg_res_key) .. ' 解压失败')
                            end
                            cb_wrapper()
                        end)
                    else
                        E.LOG.debug(TAG, "res_key: " .. tostring(code_pkg_res_key) .. ' 释放失败')
                        cb_wrapper()
                    end
                end)
            end
        else
            cb_wrapper()
        end
    end
end

local function get_latest_version_path(path_table)
    local max_version = get_latest_version(path_table)
    local result_path = path_table[max_version]
    return result_path
end


-- 根据配置参数和本地已有的文件版本，检查是否需要更新资源
local function check_config_to_update_resource(key, remote_res, invalid_res_key_table, cb)
    cb = cb or function() end

    local stat_action = 'webview_preload_request'

    E.LOG.debug(TAG, ', check_config_to_update_resource-------called, key = '..key)
    E.LOG.debug(TAG, remote_res)

    if not is_support_use_local_res(key) then
        cb(false, CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_CACHE_NOT_SUPPORT, "not support")
        return
    end

    if next(remote_res) == nil then
        E.LOG.debug(TAG, "res_update_by_key response nil, skip")
        cb(false, CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_RESPONSE_INVALID, 'config is nil, skip update')
        return
    end

    if not remote_res.handler then
        cb(false, CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_TYPE_UNKOWN, 'type is nil, can not to download it')
        E.LOG.debug(TAG, ', type is nil, return now---')
        stat(stat_action..'_no_type', key)
        return
    end

    local ext = remote_res.ext or {}
    -- remote_res里要有key和code才能继续下载
    if remote_res.handler == 'qzH5Handler' then
        if not remote_res.key or not ext._qz_urls or not next(ext._qz_urls) then
            cb(false, CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_CACHE_NOT_SUPPORT, 'data is wrong, has no [key] or no [ext._qz_urls] value， can not to download')
            E.LOG.debug(TAG, ', data is wrong ,no key or noe code. return now---')
            stat(stat_action..'_no_key_code', key)
            return
        end
    end

    --if tonumber(remote_res.downloadCondition) == 1 then
    --    -- TODO: 是WiFi下才能下载，感觉这个跟用户确认的需求点要一起做
    --end

    local expireOn = nil
    if ext._qz_expireOn and tonumber(ext._qz_expireOn) then
        expireOn = tonumber(ext._qz_expireOn)
        local file_expired_time = expireOn / 1000
        if file_expired_time > 0 and file_expired_time < E.time() then
            -- 判断有效期，看看是否过期，过期了则不再下载
            cb(false, CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_RES_EXPIRED, 'file has already expired, do not download anymore')
            E.LOG.debug(TAG, ', file has already expired, return now---, E.time() = '..tostring(E.time())..', file_expired_time = '..tostring(file_expired_time))

            stat(stat_action..'_expired', key)
            return
        end
    end

    -- 要判断磁盘空间，如果磁盘空间不够就不去下载了，返回失败
    local storage_data = E.Sysinfo.get_storage_info()
    local free_size = storage_data.internal_available_storage_size
    local size_left = 500*1024*1024 -- 500M余量空间比较合适
    -- 能获取磁盘可用空间，此时当做容量够用可直接下载
    if free_size ~= nil and free_size > 0 and remote_res.origin and remote_res.origin.size and (free_size <= remote_res.origin.size + size_left) then
        cb(false, CONSTANTS.RESOURCE_UPDATE_ERROR_CODES.RES_DEVICE_NOT_HAS_ENOUGH_SPACE, 'device not has enough space to download this file.')
        E.LOG.debug(TAG, ', device has no space to download file, return now---')
        stat(stat_action..'_no_device_memory_left', key)
        return
    end

    -- 读取本地资源的最大版本号, 取所有code里的最小的版本，只要远端版本比最小的大，就需要下载
    local urls = ext._qz_urls
    local local_res_latest_version = nil
    local codes = {}
    for _, url in pairs(urls) do
        local code = E.Utils.url_clipping(url)
        table.insert(codes, code)
        local code_local_latest_version = get_latest_version_with_code(code)
        if invalid_res_key_table[code] and VER_CHECK.compare_versions(invalid_res_key_table[code], code_local_latest_version) > 0 then
            -- 如果有高版本的无效资源，这里的版本应该用高版本的无效资源版本号
            code_local_latest_version = invalid_res_key_table[code]
        end
        if code_local_latest_version then
            if not local_res_latest_version then
                local_res_latest_version = code_local_latest_version
            elseif VER_CHECK.compare_versions(local_res_latest_version, code_local_latest_version) > 0 then
                local_res_latest_version = code_local_latest_version
            end
        end
    end


    -- 保留记录到文件中的格式
    remote_res.config_info = {
        key = remote_res.key,
        version = remote_res.version,
        path = ext._qz_path,
        urls = urls, -- 保存下
        expireOn = expireOn,
        restrict = ext._qz_restrict,
        activeStatus = ext._qz_activeStatus
    }
    remote_res.codes = codes

    E.LOG.debug(TAG, "local min version: " .. tostring(local_res_latest_version) .. ', remote version: ' .. tostring(remote_res.version))
    -- 本地没有文件，或者本地文件版本号小于远端版本号，则去更新
    if not local_res_latest_version or (VER_CHECK.compare_versions(local_res_latest_version, remote_res.version) < 0) then
        --需要更新了，才走这个逻辑
        update_resource_with_config(remote_res, local_res_latest_version, invalid_res_key_table, function(update_succ, ...)
            if update_succ then
                local res_config_data = ...
                cb(true, res_config_data)
            else
                cb(false, ...)
            end

            stat(stat_action, key, update_succ)
        end)
    else
        E.LOG.debug(TAG, ', version is new, no need to download file.')
    end
end


-- 配置中心返回
local function update_data_with_config(config)
    E.LOG.debug(TAG, ', update_data_with_config-----called')
    E.LOG.debug(TAG, config)
    config = config or {}
    local util = require 'ejoysdk_lua.ejoysdk_utils'
    --过期/开关没开的记录
    local invalid_res_key_table = {}
    --未过期且开关开了的记录
    local pending_res_key_table = {}
    if config.config then
        local namespace = config.namespace
        local version_table = {} -- 各个业务的版本号，用于设置到配置中心进行轮询用
        local temp_ecc_table = {}
        for key, res_config in pairs(config.config) do
            -- key如果是initConf则不需要下载，要用来做备选轮询
            if key == 'initConf'  then
                --if res_config.addressList and type(res_config.addressList) == 'table' then
                    --backup_server_domains = res_config.addressList
                --else
                --    E.LOG.debug(TAG, 'initConf get, and addressList is empty')
                --end
                E.LOG.debug(TAG, 'ignore initConf key')
            elseif type(res_config) == 'table' and util.tablelength(res_config) > 0 then
                -- 这个key可能要结合namespace一起才唯一，不过这里返回就是该namespace目录下的数据，所以没关系
                ecc_config_data_cache[key] = res_config -- 保存下配置数据
                temp_ecc_table[key] = res_config
                -- 开关处于激活状态才往下跑后续的流程
                local ext = res_config.ext or {}
                --local res_valid = false
                local expireOn = ext._qz_expireOn and tonumber(ext._qz_expireOn)
                local is_expired = false
                if expireOn then
                    local file_expired_time = expireOn / 1000
                    if file_expired_time < E.time() then
                        is_expired = true
                    end
                end
                

                local activeStatus = ext._qz_activeStatus
                if activeStatus and tonumber(activeStatus) == 1 and is_expired == false then
                    E.LOG.debug(TAG, "key: " .. tostring(key) .. ', res is valid, version is ' .. tostring(res_config.version))
                    --res_valid = true
                    pending_res_key_table[key] = res_config
                else
                    -- 关闭后，则需要删除webview映射表里的数据
                    -- 如果后台配置了两个res_key对应到同一个url的情况下，需要以高版本的过期及开关为准
                    E.LOG.debug(TAG, "key: " .. tostring(key) .. ', res is invalid, version is ' .. tostring(res_config.version))
                    local urls = ext._qz_urls or {}
                    for _, url in ipairs(urls) do
                        local code = E.Utils.url_clipping(url)
                        -- 版本是高的才需要改动，版本低的情况下忽略该设置
                        local code_latest_version = get_latest_version_with_code(code)
                        if VER_CHECK.compare_versions(res_config.version, code_latest_version) >= 0 then
                            remove_local_path_with_url_code(code)
                            --记录下来最大的无效版本
                            if VER_CHECK.compare_versions(res_config.version, invalid_res_key_table[code]) > 0 then
                                E.LOG.debug(TAG, "code is " .. tostring(code) .. ", local real version is " .. tostring(res_config.version) .. ", remote version is " .. tostring(res_config.version) .. ", code cache invalid max version is " .. tostring(invalid_res_key_table[code]))
                                E.LOG.debug(TAG,  ", a bigger version exist, use it's expireOn and activeStatus, expireOn is " .. tostring(expireOn) .. ', activeStatus is ' .. tostring(activeStatus))
                                invalid_res_key_table[code] = res_config.version
                                if webview_url_to_file_path_cache[code] then
                                    local config_info = {
                                        key = key,
                                        version = res_config.version,
                                        path = ext._qz_path,
                                        urls = urls, -- 保存下
                                        expireOn = expireOn,
                                        restrict = ext._qz_restrict,
                                        activeStatus = ext._qz_activeStatus
                                    }
                                    --本地缓存的路径保留原来的，下次启动删除需要用
                                    config_info.paths = webview_url_to_file_path_cache[code].paths
                                    webview_url_to_file_path_cache[code] = config_info
                                end
                            end
                        end
                    end
                end

                if res_config.version then
                    version_table[key] = {version = res_config.version}
                end
            end
        end
        save_webview_cache_config_to_disk()
        E.LOG.debug(TAG, "invalid_res_key_table is ")
        E.LOG.debug(TAG, invalid_res_key_table)
        for pending_key, pending_config in pairs(pending_res_key_table) do
            check_config_to_update_resource(pending_key, pending_config, invalid_res_key_table)
        end


        -- 设置配置中心的exInfo数据，把业务版本号带上
        if util.tablelength(version_table) > 0 then
            ECC.set_ex_info(namespace, version_table)
            E.LOG.debug(TAG, 'set config center exinfo, version_table = ')
            E.LOG.debug(TAG, version_table)
        end


        -- 后台并不支持删除资源key，这里不用处理
        --for key, res_config in pairs(ecc_config_data_cache) do
        --    if not temp_ecc_table[key] then
        --        -- 旧数据存在，新数据没了，则删除
        --
        --        -- 这里如果webview没有在打开才删文件，避免本地文件正在使用中被删除的情况
        --        if not E.WebView.is_opened() then
        --            local temp_table = webview_url_to_file_path_cache[res_config.code]
        --            if temp_table and temp_table.paths then
        --                local path_table = temp_table.paths
        --                local real_path = get_latest_version_path(path_table)
        --                if real_path then
        --                    real_path = find_parent_folder(real_path)
        --                    E.LOG.debug(TAG, '， delete local file, real_path = '..tostring(real_path))
        --                    E.File.remove(real_path) -- 删除文件夹
        --                end
        --            end
        --        end
        --
        --        remove_local_path_with_url_code(res_config.code, res_config.hosts) -- 删除映射关系
        --        webview_url_to_file_path_cache[res_config.code] = nil -- 删除内存缓存
        --        save_webview_cache_config_to_disk() --保存到磁盘
        --    end
        --end

        ecc_config_data_cache = temp_ecc_table

    end
end

-- 接口封装
M.get_config_center_data_with_namespace = ECC.get_config
M.get_configs_in_whitelist = ECC.get_configs_in_whitelist

function M.init(cb)
    cb = cb or function()
    end

    -- TODO:暂不支持PC，PC没有解压缩功能
    local os_value = E.Sysinfo.os()
    if os_value ~= "android" and os_value ~= "ios" then
        ET.publish(ET.lightboat.INITED)
        cb(true)
        return
    end

    local stat_action = 'local_path_set_to_webview'
    -- 1.加载磁盘缓存
    load_webview_cache_config()

    -- 2.加载包内配置
    load_pkg_webview_cache_config()

    -- 3.校验包内和包外资源
    check_webview_cache(function()
        local need_save = false
        for code, temp_table in pairs(webview_url_to_file_path_cache) do
            local path_table = temp_table.paths or {}
            local real_path = get_latest_version_path(path_table)
            E.LOG.debug(TAG, 'code is ' .. tostring(code))
            E.LOG.debug(TAG, path_table)
            E.LOG.debug(TAG, '， real_path = '..tostring(real_path))
            local activeStatus = temp_table.activeStatus
            -- 1表示开关有效，开关有效才去设置webview的映射表，让其使用本地资源

            local res_valid = true
            if temp_table.expireOn then
                local file_expired_time = tonumber(temp_table.expireOn) / 1000
                if file_expired_time > 0 and file_expired_time < E.time() then
                    res_valid = false -- 资源已过期
                end
            end

            if activeStatus and tonumber(activeStatus) == 1 and res_valid and real_path then
                -- 2.把最大版本资源的本地路径写到webview配置表里去
                set_local_path_to_url_code(code, real_path)
                stat(stat_action, code, true)
            else
                -- 关闭或过期后，则需要删除webview映射表里的数据
                remove_local_path_with_url_code(code)
                stat(stat_action, code, false)
            end


            local new_path_table = {}
            -- 3.把其他版本号的文件删除
            for version, temp_path in pairs(path_table) do
                -- 如果过期了，则该code对应的所有本地的文件都可以删除，因为配置数据只保留最新的，如果它都过期了，则所有版本文件就都过期了
                if not res_valid or temp_path ~= real_path then
                    -- 拼接成完整路径再删
                    -- temp_path可能是v1遗留的相对路径, 这里做一下兼容
                    if not HRU.is_file_exists(temp_path) then
                        E.LOG.debug(TAG, 'temp_path is not exist, maybe v1, now try append base path')
                        local temp_path_v2 = E.File.get_ext_file_dir() .. '/' .. temp_path
                        if HRU.is_file_exists(temp_path_v2) then
                            temp_path = temp_path_v2
                            E.LOG.debug(TAG, 'temp_path_v2 is ' .. tostring(temp_path_v2))
                        else
                            E.LOG.debug(TAG, 'temp_path_v2 is not exist, temp_path_v2 is ' .. tostring(temp_path_v2))
                        end
                    end
                    local inner_path = find_parent_folder(temp_path)
                    E.LOG.debug(TAG, '， delete local file, inner_path = '..tostring(inner_path))
                    E.File.remove_fullpath(inner_path) -- 删除文件夹
                    need_save = true
                else
                    -- 只保留一份就好
                    new_path_table[version] = real_path
                end
            end

            -- 更新内存缓存值，只保留最新的版本就好
            temp_table.paths = new_path_table
        end

        -- 如果有删除旧文件，就再次保存下这个数据
        if need_save then
            E.LOG.debug(TAG, '，has delete local file, so need save cache to file again')
            save_webview_cache_config_to_disk()
        end



        -- 根据配置请求一次下载，并且订阅配置更新
        local namespace = ECC.NAMESPACE.MARKET_H5_RESOURCE
        --namespace = 'test' -- 测试用
        --E.LOG.debug(TAG, ECC.get_config(namespace))
        update_data_with_config(ECC.get_config(namespace))
        ECC.subscribe(namespace, update_data_with_config)

        --ECC.subscribe(ECC.NAMESPACE.EJOYSDK_H5_RESOURCE,update_data_with_config)

        ET.publish(ET.lightboat.INITED)
        cb(true)
    end)
end

local function suit_query_to_local_path_with_url(code, url, local_path)
    if not url or not local_path then
        return local_path
    end

    if code == nil then
        code = E.Utils.url_clipping(url)
    end

    -- 关闭模式匹配
    local code_index = string.find(url, code, 1, true)
    local full_path = local_path
    if code_index then
        local last_url = string.sub(url, code_index+string.len(code))
        if last_url then
            E.LOG.debug(TAG, 'last_url = ' .. last_url)
            full_path = local_path .. last_url
        end
    end

    return full_path
end

function M.get_url_from_cache(url)
    if _ejoysdk.os() == "windows" then
        return url
    end

    E.LOG.debug(TAG, ',get_local_path_with_url----')
    local code = E.Utils.url_clipping(url)
    E.LOG.debug(TAG, webview_url_path_table_cache)
    if code then
        local path = webview_url_path_table_cache[code]
        E.LOG.debug(TAG, ' get_local_path_with_url, path = '.. tostring(path))
        local action = 'webview_open_path_url'
        if path then
            E.LOG.debug(TAG, ',  path = '..path)
            -- 兼容v1存相对路径的模式
            if not HRU.is_file_exists(path) then
                E.LOG.debug(TAG, 'path: ' .. tostring(path) .. ' not exist, try a new path: ')
                path = E.File.get_ext_file_dir() .. '/' .. path
                E.LOG.debug(TAG, path)
            end
            -- 文件必须要存在
            if HRU.is_file_exists(path) then
                -- 插入startupdata
                --inject_data_local_path(url,full_path,injection)

                if not E.Utils.start_with(path, 'file://') then
                    path = 'file://' .. path
                end

                path = suit_query_to_local_path_with_url(code, url, path)

                E.LOG.debug(TAG, ', local path = '..path)
                stat(action, code, true)

                return path
            end
        else
            stat(action, code, false)
        end
    end
    -- 找不到就返回原始URL
    return url
end

-- 支持返回url和是否有本地资源信息
function M.get_url_infos_from_cache(url, _namespace)

    local prefer_namespace = _namespace or ECC.NAMESPACE.MARKET_H5_RESOURCE
    local r_url = M.get_url_from_cache(url)
    E.LOG.debug(TAG, "url is " .. tostring(url) .. ', r_url is ' .. tostring(r_url))
    local use_remote_res = false
    local code = E.Utils.url_clipping(url)

    local config = ECC.get_config(prefer_namespace) or {}
    local util = require 'ejoysdk_lua.ejoysdk_utils'
    if config.config then
        local code_max_version_config = {}
        for _, res_config in pairs(config.config) do
            if type(res_config) == 'table' and util.tablelength(res_config) > 0 then
                if res_config.ext and res_config.ext._qz_urls then
                    for _, config_url in ipairs(res_config.ext._qz_urls) do
                        local config_url_code = E.Utils.url_clipping(config_url)

                        if config_url_code == code then
                            if VER_CHECK.compare_versions(res_config.version, code_max_version_config.version) > 0 then
                                code_max_version_config = res_config
                            end
                        end
                    end
                end
            end
        end
        if code_max_version_config then
            code_max_version_config.ext = code_max_version_config.ext or {}
            local activeStatus = code_max_version_config.ext._qz_activeStatus
            local res_valid = true
            if code_max_version_config.ext._qz_expireOn and tonumber(code_max_version_config.ext._qz_expireOn) then
                local file_expired_time = tonumber(code_max_version_config.ext._qz_expireOn) / 1000
                if file_expired_time > 0 and file_expired_time < E.time() then
                    res_valid = false -- 资源已过期
                end
            end
            if (code_max_version_config.ext._qz_restrict and code_max_version_config.ext._qz_restrict == true) or (not (activeStatus and tonumber(activeStatus) == 1)) or (not res_valid) then
                -- 严格模式，直接忽略本地 或 --资源未开启/关闭，需要使用远端
                E.LOG.debug(TAG, 'use_remote_res = true')
                use_remote_res = true
            end
        end
    end
    -- url不变表示没有本地资源
    -- use_remote_res 为true表示需要使用远端资源
    return { url = r_url, use_remote_res = use_remote_res }
end

-- 内部单元测试用
M.test_update_data_with_config = update_data_with_config
M.test_suit_query_to_local_path_with_url = suit_query_to_local_path_with_url
M.test_update_resource_with_config = update_resource_with_config
M.test_check_config_to_update_resource = check_config_to_update_resource
M.test_ecc_config_data_cache = ecc_config_data_cache
return M