---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hufeng.
--- DateTime: 2020/10/23 11:09 上午
---
local E = require "ejoysdk_lua.ejoysdk"
local EM = require "ejoysdk_lua.ejoysdk_module"
local ML = require "ejoysdk_lua.vendors.media_log"

local TAG = EM.MODULE.NATIVE .. 'modules.logbus'

local M = {}

function M.commit_event(event_name, param, opts)
    opts = opts or {}
    -- 兼容之前的入参内容，如果不传COMMIT_ONLY_ONCE，则值为false
    if opts[ML.OPT_KEY.COMMIT_ONLY_ONCE] == nil then
        opts[ML.OPT_KEY.COMMIT_ONLY_ONCE] = false
    end

    if opts[ML.OPT_KEY.MEDIAS] == nil and opts[ML.OPT_KEY.INCLUDE_ALL_MEDIAS] == nil then
        -- 兼容之前的传参，如果没有过滤medias，则默认传给所有media
        opts[ML.OPT_KEY.INCLUDE_ALL_MEDIAS] = true
        opts[ML.OPT_KEY.MEDIAS] = {"JF"}
    end

    E.LOG.debug(TAG, 'commit_event:' .. tostring(event_name))
    E.log(param)
    E.log(opts)

    ML.commit_event(event_name, param, opts)
end

return M