---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ali.
--- DateTime: 2/10/22 5:42 PM
---
local E = require 'ejoysdk_lua.ejoysdk'
local ET = require 'ejoysdk_lua.ejoysdk_topic'
local EC = require 'ejoysdk_lua.user_center.system_config'
local EUUID = require "ejoysdk_lua.ejoysdk_uuid"
local BaseModel = require "ejoysdk_lua.user_center.agst_token_model_base"

local MODEL_NAME = "AGST_TOKEN_OVERSEA"
local M = BaseModel:Inherit(MODEL_NAME)
local TAG = "agst_token_oversea"

local AGST_IOS_PID_PERMANENT = nil -- 用于ios保存在Keychain的pid
local AGST_IOS_EXT_PERMANENT = nil -- 用于ios保存在keychain的agst_token扩展信息，如agst_token的版本号
local AGST_IOS_EXT = nil -- 用于ios保存在UserDefault的agst_token扩展信息，如agst_token的版本号

local AGST_PID = nil -- 当前使用的pid，各端命名一致,三端指向的都是临时的缓存区，只要有值，不管开关，都不应该改

local AGST_EXT_GAID = nil

local AGST_VER = 'AGST_VER'

local last_agst_android_gaid = nil
local last_agst_android_pid = nil

local android_userinfo_handler = function(_user_info)
    -- 海外登录都需要经过海外用户中心，所以登录成功代表游客ID已经同步到服务端
    E.LOG.debug(TAG, 'is official, now save gaid and pid')
    local gaid = AGST_EXT_GAID:get()
    if not gaid then
        E.LOG.debug(TAG, 'android set agst gaid: ' .. tostring(last_agst_android_gaid))
        AGST_EXT_GAID:set(last_agst_android_gaid)
    else
        E.LOG.debug(TAG, 'android has agst gaid: ' .. tostring(last_agst_android_gaid))
    end
    local pid = AGST_PID:get()
    if not pid then
        E.LOG.debug(TAG, 'android set agst pid: ' .. tostring(last_agst_android_pid))
        AGST_PID:set(last_agst_android_pid)
    else
        E.LOG.debug(TAG, 'android has agst pid： ' .. tostring(last_agst_android_pid))
    end
end

function M.get_android_agst_info(cb)
    local pid = AGST_PID:get()
    if not pid then
        pid = E.Sysinfo.device_with_android_id()
    end

    local function get_gaid_callback(gaid)
        last_agst_android_gaid = gaid
        last_agst_android_pid = pid

        local result = M.build_agst_info(last_agst_android_pid, last_agst_android_gaid)

        -- callback result
        cb(result)
    end

    local gaid = AGST_EXT_GAID:get()
    E.LOG.debug(TAG, 'agst# login and check cache gaid:' .. tostring(gaid))
    if gaid then
        -- if no cache, gaid is nil
        get_gaid_callback(gaid)
    else
        E.LOG.debug(TAG, 'agst# start get gaid async')
        E.Sysinfo.gaid_async(function(result)
            gaid = result.value
            E.LOG.debug(TAG, "gaid# async callback:" .. tostring(gaid))
            gaid = gaid or ''
            get_gaid_callback(gaid)
        end)
    end
end

function M.get_ios_agst_info(cb)
    local agst_ios_pid = AGST_PID:get()
    if agst_ios_pid then
        E.LOG.debug(TAG, 'get_ios_token si:' .. agst_ios_pid)

        local ios_ext = AGST_IOS_EXT:get() or {}
        local result = M.build_agst_info(agst_ios_pid, "", ios_ext[AGST_VER])
        -- callback result
        cb(result)
    else
        cb(nil)
    end
end

-- windows 暂时和ios保持一致
M.get_windows_agst_info = M.get_ios_agst_info

local function is_pid_nil(pid)
    return pid == nil or pid == ''
end

function M.init()
    local os = E.Sysinfo.os()
    if os == 'ios' or os == 'windows' then
        AGST_IOS_PID_PERMANENT = E.LazyKeyStore:New('OFFICIAL_AGST_IOS_PID')
        AGST_PID = E.LazyKeyStore:New('OFFICIAL_AGST_IOS_PID_UD', false, false, false) -- 临时缓存，在旧版是不存在的

        -- ext与pid的关系需要保持同步
        AGST_IOS_EXT_PERMANENT = E.LazyKeyStore:New('OFFICIAL_AGST_IOS_EXT', false, true)
        AGST_IOS_EXT = E.LazyKeyStore:New('OFFICIAL_AGST_IOS_EXT_UD', false, true, false)
    elseif os == 'android' then
        AGST_PID = E.LazyKeyStore:New('OFFICIAL_AGST_ANDROID_PID')
        AGST_EXT_GAID = E.LazyKeyStore:New('AGST_EXT_GAID')
        ET.subscribe(ET.gangplank.ACQUIRE, android_userinfo_handler)
    end

    ET.subscribe(ET.user_center.USER_CENTER_INIT_SUCCESS, function(values)
        local user_center = require 'ejoysdk_lua.user_center.ejoysdk_usercenter'
        local si = user_center.get_si()
        local guest_persist = EC.get('guest_persist') or 0 -- 默认不保留游客记录

        -- 如果安装后已经生成过pid，则直到清数据或重装前都是使用这个pid,无论guest_persist此时是0还是1
        local sp_pid = AGST_PID:get()

        E.LOG.debug(TAG, "guest_persist = " .. guest_persist)
        if guest_persist == 0 then
            if is_pid_nil(sp_pid) then
                -- 如果是热更新lua，但热更前是没有记录sp_pid的，这种情况下pid会重置, 要是这个游戏刚好也是不保留记录的就GG了
                if values.first_launch then
                    E.LOG.debug(TAG, "first launch, reset pid ")
                    -- android的si都是存sp的，重装就变; ios的si是存keychain的，就算重装后下一次还是能读到同一个
                    -- 为了统一处理，在不保留游客记录的情况下pid为si+uuid, 为保证游戏更新前后表现一致，仅针对新安装的才重置pid
                    -- 其中si由服务端保证不同的机器可以获取到不同的值（即使已经保存到本机也是），uuid保证不同次安装是不一样的
                    -- NOTE: ios的pid解析有个坑，服务端会把对pid使用AES解密，2022.3月后服务端处理在解密失败后直接使用原串（与android一致）
                    AGST_PID:set(si .. (EUUID.random_i64() or E.time()))

                    if os == 'ios' or os == 'windows' then
                        AGST_IOS_EXT:set({ [AGST_VER]= 2 })
                    end
                    return
                end
            end
        end

        E.LOG.debug(TAG, "keep pid record")
        if os == 'ios' or os == 'windows' then
            -- android use devicesId as pid
            local permanent_pid = AGST_IOS_PID_PERMANENT:get()
            if is_pid_nil(sp_pid) then
                -- sp缓存不存在
                if is_pid_nil(permanent_pid) then
                    -- keychain缓存都不存在时，重新设置pid
                    -- NOTE: ios直接使用si的话服务端会解密，后续慢慢会淘汰si解密，针对新用户就直接使用不能解密的数据
                    AGST_IOS_PID_PERMANENT:set(si .. (EUUID.random_i64() or E.time()))
                    AGST_IOS_EXT_PERMANENT:set({ [AGST_VER] = 2 })
                end

                -- keychain缓存存在，同步到sp缓存，本次安装的生命周期内都用sp缓存
                AGST_PID:set(AGST_IOS_PID_PERMANENT:get())
                -- sp缓存不存在，pid取自keychain，同样ext的信息也要跟随
                AGST_IOS_EXT:set(AGST_IOS_EXT_PERMANENT:get())
            else
                -- sp缓存存在，不应该同步到keychain，除非keychain都不存在，否则其他游戏如果开关是关的，结果这个游戏的修改影响到了另一个游戏（共享keychain group情况下）
                if is_pid_nil(permanent_pid) then
                    AGST_IOS_PID_PERMANENT:set(sp_pid)
                    AGST_IOS_EXT_PERMANENT:set(AGST_IOS_EXT:get())
                end
            end
        end
    end)
end

return M
