---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pangang.
--- DateTime: 2019/12/2 下午4:14
--- 这个用户中心是给海外用的，国内不走这里
local API = require "ejoysdk_lua.user_center.usercenter_api"
local E = require "ejoysdk_lua.ejoysdk"
local CONSTANTS = require 'ejoysdk_lua.ejoysdk_constants'
local PROTOCAL = require 'ejoysdk_lua.user_center.usercenter_protocal'
local ET = require "ejoysdk_lua.ejoysdk_topic"
local UTILS = require 'ejoysdk_lua.ejoysdk_utils'
local EGC = require 'ejoysdk_lua.ejoysdk_gangplank_config'
local EM = require "ejoysdk_lua.ejoysdk_module"

local TAG = EM.MODULE.USER_CENTER .. 'ejoysdk_usercenter'

local SYSTEM_CONFIG = E.LazyKeyStore:New('SYSTEM_CONFIG', false, true, false)
local CONFIG_CHECK_TIME = E.LazyKeyStore:New('CONFIG_CHECK_TIME', false, false, false)
local USERCENTER_SI = E.LazyKeyStore:New('si')
local is_first_launch = (CONFIG_CHECK_TIME:get() == nil)

local THIRD_PARTY_TYPES = {
    FACEBOOK = 'facebook',
    APPLE = 'apple_game_center',
    GOOGLE = 'google',
    GOOGLE_PLAY = 'google_play',
    GUEST = 'guest',
    -- 主体登录方式的统称，其包含qookka，青鸟，东风，发香港地区则是qookka，发台湾则是青鸟，同一份代码，不同的品牌和UI
    AIRLINE = 'airline',
    -- H5扫码登录，目前用于海外，扫的是账号中心给的二维码，获取二维码和轮询都是H5自己实现的，扫码成功后会拿到ptoken
    QR_LOGIN = 'qr_login',
    MOCK = 'mock',
    -- sign with apple登录方式
    APPLE_LOGIN = "apple_login",
    BBG_LOGIN = "bbg_login",
    HW_LOGIN = "hw_login",
    TWITTER_LOGIN = "twitter_login",
    LINE = "line",
    -- 日本地区我们自己做的一个登录方式，引继码
    CITA_LOGIN = "cita_login",
    ST_LOGIN = "st_login",
    -- google的游戏中心登录
    PGA_LOGIN = "pga_login",
    -- 日本一个游戏平台的第三方登录方式，类似Facebook
    DMM_LOGIN = "dmm_login"
}

local VENDOR_NAME_MAP = {
    FB = THIRD_PARTY_TYPES.FACEBOOK,
    APPLE = THIRD_PARTY_TYPES.APPLE,
    GOOGLE = THIRD_PARTY_TYPES.GOOGLE,
    GOOGLE_PLAY = THIRD_PARTY_TYPES.GOOGLE_PLAY,
    AGST = THIRD_PARTY_TYPES.GUEST,
    AIRLINE = THIRD_PARTY_TYPES.AIRLINE,
    QR_LOGIN = THIRD_PARTY_TYPES.QR_LOGIN,
    APPLE_LOGIN = THIRD_PARTY_TYPES.APPLE_LOGIN,
    BBG_LOGIN = THIRD_PARTY_TYPES.BBG_LOGIN,
    HW_LOGIN = THIRD_PARTY_TYPES.HW_LOGIN,
    TWITTER_LOGIN = THIRD_PARTY_TYPES.TWITTER_LOGIN,
    LINE = THIRD_PARTY_TYPES.LINE,
    CITA_LOGIN = THIRD_PARTY_TYPES.CITA_LOGIN,
    ST_LOGIN = THIRD_PARTY_TYPES.ST_LOGIN,
    PGA_LOGIN = THIRD_PARTY_TYPES.PGA_LOGIN,
    DMM_LOGIN = THIRD_PARTY_TYPES.DMM_LOGIN
}

local THIRD_PARTY_TYPE_MAP = {
    [THIRD_PARTY_TYPES.FACEBOOK] = 'FB',
    [THIRD_PARTY_TYPES.APPLE] = 'APPLE',
    [THIRD_PARTY_TYPES.GOOGLE] = 'GOOGLE',
    [THIRD_PARTY_TYPES.GOOGLE_PLAY] = 'GOOGLE_PLAY',
    [THIRD_PARTY_TYPES.GUEST] = 'AGST',
    [THIRD_PARTY_TYPES.AIRLINE] = 'AIRLINE',
    [THIRD_PARTY_TYPES.QR_LOGIN] = 'QR_LOGIN',
    [THIRD_PARTY_TYPES.APPLE_LOGIN] = 'APPLE_LOGIN',
    [THIRD_PARTY_TYPES.BBG_LOGIN] = 'BBG_LOGIN',
    [THIRD_PARTY_TYPES.HW_LOGIN] = 'HW_LOGIN',
    [THIRD_PARTY_TYPES.TWITTER_LOGIN] = 'TWITTER_LOGIN',
    [THIRD_PARTY_TYPES.CITA_LOGIN] = 'CITA_LOGIN',
    [THIRD_PARTY_TYPES.ST_LOGIN] = 'ST_LOGIN',
    [THIRD_PARTY_TYPES.PGA_LOGIN] = 'PGA_LOGIN',
    [THIRD_PARTY_TYPES.DMM_LOGIN] = 'DMM_LOGIN',
}

local usercenter_url_base = nil
local cache_user_info = {}

local M = {}

M.USER_CENTER_ERROR_CODES = {
    -- 存在游客数据及第三方账号未绑定
    ERR_AGST_ROLE_BIND_CONFLICT = 2001000,
    -- 无效的账号中心token
    ERR_TOKEN_INVALID = 4001101,
    -- 过期的账号中心token
    ERR_TOKEN_EXPIRED = 4001102,
    -- 第三方token校验失败，目前是QOOKKA的子渠道错误码
    ERR_THIRD_PART_TOKEN_FAILED = 4001103,
    --渠道接口异常，包括谷歌、Facebook
    ERR_SERVER_THIRD_PART = 5000004,
    -- 账号需要迁移
    ERR_ACCOUNT_NEED_MIGRATED = 4002007,
    -- 宙斯盾挑战，data 附带挑战信息
    ERR_NEED_CHALLENGE = 5000014,
    -- 宙斯盾挑战校验失败
    ERR_CHALLENGE_FAIL = 5000015
}

local function init_usercenter_url(cb)
    E.LOG.debug(TAG, 'init_usercenter_url begin')
    local current_cdn_config = EGC.get_current_cdn_config()
    if current_cdn_config then
        E.LOG.debug(TAG, 'init_usercenter_url find current cdn config')

        -- update usercenter url_base
        local temp_usercenter_url_base = current_cdn_config.account_center
        PROTOCAL.set_url_base_with_type(PROTOCAL.SERVICE_TYPE.ACCOUNT_CENTER, temp_usercenter_url_base)

        -- 边缘服务地址
        local temp_edge_server_url_base = current_cdn_config.edge_center
        PROTOCAL.set_url_base_with_type(PROTOCAL.SERVICE_TYPE.EDGE_CENTER, temp_edge_server_url_base)

        --callback
        cb(true, temp_usercenter_url_base)
    else

        E.LOG.warn(TAG, 'init_usercenter_url NOT find current cdn config')
        cb(false, CONSTANTS.USER_CENTER_ERROR_CODES.CODE_CONFIG_INVALID, 'not find current cdn config')
    end
end

local function init_with_system_config(config_data)
    --TODO 1、解析clientConfig
    local sc = require 'ejoysdk_lua.user_center.system_config'
    --if config_data.clientConfig and config_data.configCheckTime and CONFIG_CHECK_TIME:get() ~= tostring(config_data.configCheckTime) then
    local client_config_data
    if config_data.clientConfig and next(config_data.clientConfig) ~= nil then
        client_config_data = config_data.clientConfig
        SYSTEM_CONFIG:set(client_config_data)
        sc.init(client_config_data)
        E.LOG.debug(TAG, "init_with_system_config receive config from server side")
    else
        client_config_data = SYSTEM_CONFIG:get()
        sc.init(client_config_data)
        E.LOG.debug(TAG, "init_with_system_config from local SP cache")
    end

    E.log(client_config_data)

    -- 2、更新configCheckTime
    if config_data.configCheckTime then
        local config_check_time = config_data.configCheckTime
        CONFIG_CHECK_TIME:set(config_check_time)
    end

    -- 3、更新si
    if config_data.si and config_data.si ~= '' then
        local si = config_data.si
        E.LOG.debug(TAG, 'init_with_system_config udpate si:' .. tostring(si))
        USERCENTER_SI:set(si)
        PROTOCAL.set_si(si)
    end
end

local function region_config_change_handle(new_region)
    init_usercenter_url(function(succ, ...)
        if succ then
            E.LOG.debug(TAG, 'region_config_change_handle new region:' .. (new_region or 'nil') .. ', get usercenter url success!')
        else
            local code, msg = ...
            E.LOG.warn(TAG, 'region_config_change_handle new_region:' .. (new_region or 'nil' .. ', get usercenter url failed, code:' .. tostring(code) .. ', msg:' .. (msg or 'nil')))
        end
    end)
end

local function get_risk_info(challengeInfo)
    local aegis_info = {}
    if challengeInfo then
        aegis_info.type = 'auth'
        aegis_info.challengeData = challengeInfo
    else
        aegis_info.type = 'check'
        local ACD = require 'ejoysdk_lua.aegis.aegis_collect_data'
        local JSON = require 'ejoysdk_lua.ejoysdk_json'
        local encrypt_data = ACD.get_encrypt_data()
        aegis_info.datagram = JSON.encode({ w = encrypt_data })
    end
    return aegis_info
end

function M.request_system_config(cb)
    local config_check_time = CONFIG_CHECK_TIME:get()
    API.usercenter_system_config_check(config_check_time, function(succ2, ...)
        if succ2 then
            --3. 缓存下发参数
            local config_data = ...
            if config_data then
                --4. 初始化账号中心模块
                init_with_system_config(config_data)
                cb(true)
            else
                E.LOG.warn(TAG, 'usercenter_system_config_check failed, data is empty:')
                cb(false, CONSTANTS.USER_CENTER_ERROR_CODES.CODE_SYSTEM_CONFIG_DATA_EMPTY, 'system config response data is empty')
            end
        else
            local code, msg = ...
            E.LOG.warn(TAG, 'usercenter_system_config_check failed, code:' .. tostring(code) .. ', msg:' .. tostring(msg))
            cb(false, ...)
        end
    end)
end

function M.init_si()
    local si = USERCENTER_SI:get()
    PROTOCAL.set_si(si)
    E.LOG.debug(TAG, "init_si last_si:" .. tostring(si))
end

-- 用户中心模块初始化
function M.init(cb)
    --1. 检查和更新SI
    M.init_si()

    --2. 从gangplank查找账号中心地址
    init_usercenter_url(function(succ, ...)
        if succ then
            usercenter_url_base = ...
            if not usercenter_url_base or usercenter_url_base == '' then
                cb(false, CONSTANTS.USER_CENTER_ERROR_CODES.CODE_GET_URL_BASE_FAILED, 'get usercenter url failed')
            else
                --2. 请求账号中心参数下发接口
                E.LOG.debug(TAG, 'init start request for system config')
                M.request_system_config(function(_succ, ...)
                    if _succ then
                        -- 通知用户中心初始化成功
                        ET.publish(ET.user_center.USER_CENTER_INIT_SUCCESS, { first_launch = is_first_launch })
                    end

                    cb(_succ, ...)
                end)
            end
        else
            cb(false, ...)
        end
    end)

    --监听地区变更
    ET.subscribe(ET.config.CONFIG_CHANGED .. '_' .. E.CONFIG.KEY.REGION, region_config_change_handle)
end

local function get_third_party_type_by_name(vendor_name)
    if not vendor_name or vendor_name == '' then
        E.LOG.warn(TAG, 'bind >> NOT find third party name for vendor is empty')
        return nil
    end

    return VENDOR_NAME_MAP[vendor_name]
end

local function update_current_region_user_cache(user_data)
    local region = E.CONFIG.get_config(E.CONFIG.KEY.REGION) or 'default-region'
    if region then
        cache_user_info[region] = user_data or {}
        E.LOG.debug(TAG, "update_current_region_user_cache succ, region:" .. tostring(region))
    else
        E.LOG.warn(TAG, "update_current_region_user_cache failed, region is nil")
    end
end

local function get_current_region_user_cache()
    local region = E.CONFIG.get_config(E.CONFIG.KEY.REGION) or 'default-region'

    local result_data = {}
    if region then
        result_data = cache_user_info[region] or {}
        E.LOG.debug(TAG, "get_current_region_user_cache succ, region:" .. tostring(region))
    else
        E.LOG.warn(TAG, "get_current_region_user_cache failed, region is nil")
    end

    return result_data
end

local function clear_user_cache()
    cache_user_info = {}
end

-- 该接口不止用于实名制，也扩展到海外儿童年龄等场景
local function handle_realname(user_data,cb)
    local overseas_login = require 'ejoysdk_lua.overseas.login'
    overseas_login.handle_realname(user_data, function(realname_succ)
        if (realname_succ == true) then
            cb(true, user_data)
        else
            cb(false,CONSTANTS.OFFICIAL_ERR_CODES.CODE_USER_INFO_VERIFY_FAIL,'用户信息校验失败')
        end
    end)
end

-- 用户中心模块登录
function M.login(vendor_name, third_party_token, agst_token, is_create, challenge_info, ext, cb)
    E.LOG.debug(TAG, 'login begin')

    local third_party_type = get_third_party_type_by_name(vendor_name)
    if not third_party_type or third_party_type == '' then
        E.LOG.warn(TAG, 'login >> NOT find third party name for vendor is empty')
        cb(false, CONSTANTS.USER_CENTER_ERROR_CODES.CODE_INVALID_PARAMETER, 'vendor name is empty')
        return
    end

    -- BBG迁移特有逻辑，BBG登录后需要将bbg token 以新字段传递给服务器
    local migrate_token = ''
    if third_party_type == THIRD_PARTY_TYPES.BBG_LOGIN then
        migrate_token = { type = "bbg", token = third_party_token }
        third_party_token = ''
        third_party_type = ''
    elseif (ext and ext.pass_ext and ext.pass_ext.migrate_token and '' ~= ext.pass_ext.migrate_token) then
        migrate_token = ext.pass_ext.migrate_token
    end

    local risk = get_risk_info(challenge_info)

    if third_party_type then
        E.LOG.debug(TAG, 'login >> find third party name:' .. tostring(third_party_type) .. ', vendor_name:' .. tostring(vendor_name))
        API.usercenter_login(third_party_type, third_party_token, agst_token, migrate_token, is_create, risk, function(succ, ...)
            if succ then
                E.LOG.debug(TAG, 'login usercenter_login succ')
                local user_data = ...
                user_data = user_data or {}
                update_current_region_user_cache(user_data)

                M.set_limit_data_usage((user_data.limitDataUsage == true) or false) -- 设置LDU状态

                handle_realname(user_data,cb)
            else
                E.LOG.warn(TAG, 'login usercenter_login failed')

                -- bbg的迁移需要将migrate_token返回出去，并返回前端
                local code, msg, data = ...
                if code == M.USER_CENTER_ERROR_CODES.ERR_ACCOUNT_NEED_MIGRATED then
                    cb(false, code, msg, migrate_token)
                else
                    cb(false, code, msg, data)
                end
            end
        end)
    else
        E.LOG.warn(TAG, 'login >> NOT find third party name with vendor:' .. tostring(vendor_name))
        cb(false, CONSTANTS.USER_CENTER_ERROR_CODES.CODE_INVALID_PARAMETER, 'vendor name not recognized, vendor name:' .. tostring(vendor_name))
    end
end

function M.logout()
    E.LOG.debug(TAG, 'usercenter logout')
    clear_user_cache()
end

function M.user_info()
    local current_region_user_info = get_current_region_user_cache()
    return UTILS.deepcopy(current_region_user_info)
end

function M.async_user_info(cb)
    if cb then
        cb(M.user_info())
    end
end

-- 绑定
function M.bind(agst_token, vendor_name, third_party_token, cb)
    local third_party_type = get_third_party_type_by_name(vendor_name)
    if not third_party_type or third_party_type == '' then
        E.LOG.warn(TAG, 'login >> NOT find third party name for vendor is empty')
        cb(false, CONSTANTS.USER_CENTER_ERROR_CODES.CODE_INVALID_PARAMETER, 'vendor name is empty')
        return
    end

    local current_region_user_info = get_current_region_user_cache()
    local usercenter_token = current_region_user_info.token or ''
    if usercenter_token == '' then
        E.LOG.debug(TAG, 'bind with usercenter_token nil, its outside game bind')
    else
        E.LOG.debug(TAG, 'bind with usercenter_token nil, its inside game bind')
    end

    API.usercenter_bind(usercenter_token, agst_token, third_party_type, third_party_token, function(succ, ...)
        if succ then
            E.LOG.debug(TAG, 'bind success')
            local user_data = ...
            update_current_region_user_cache(user_data)
            --E.LOG.debug(TAG, 'update cached user info, bind data >>')
            --E.log(user_data)

            handle_realname(user_data,cb)
        else
            E.LOG.warn(TAG, 'bind failed')
            cb(false, ...)
        end
    end)
end

-- 查询绑定账号列表接口
function M.get_bind_info(cb)
    E.LOG.debug(TAG, 'get_bind_info begin')

    local current_region_user_info = get_current_region_user_cache()
    local usercenter_token = current_region_user_info.token or ''
    if usercenter_token == '' then
        E.LOG.debug(TAG, 'get_bind_info failed, usercenter_token is empty! for current region')
        cb(false, CONSTANTS.USER_CENTER_ERROR_CODES.CODE_TOKEN_INVALID, 'token is nil')
        return
    end

    API.usercenter_bind_list(usercenter_token, function(succ, ...)
        if succ then
            E.LOG.debug(TAG, 'usercenter_bind_list succ')
            local data = ...
            local bind_list = {}
            if data and data.bindList then
                for _, v in pairs(data.bindList) do
                    if v.thirdPartyType then
                        local vendor_name = THIRD_PARTY_TYPE_MAP[v.thirdPartyType]
                        if vendor_name then
                            v.vendorName = vendor_name
                            bind_list[vendor_name] = v
                        else
                            E.LOG.warn(TAG, 'thirdPartyType not recognized:' .. tostring(v.thirdPartyType))
                        end
                    else
                        E.LOG.warn(TAG, 'thirdPartyType is nil:')
                    end
                end
            end

            cb(true, bind_list)
        else
            local code, msg = ...
            E.LOG.warn(TAG, 'usercenter_bind_list failed, code:' .. tostring(code) .. ', msg:' .. (msg or 'nil'))
            cb(false, code, msg)
        end
    end)
end

function M.get_si()
    local si = USERCENTER_SI:get()
    return si or ''
end

function M.set_limit_data_usage(enable)
    local OVERSEA_APPLOG = require "ejoysdk_lua.vendors.oversea_applog"
    OVERSEA_APPLOG.set_limit_data_usage(enable)
end

return M
