---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ali.
--- DateTime: 2019/12/2 下午4:30
---
local E = require "ejoysdk_lua.ejoysdk"
local UP = require "ejoysdk_lua.user_center.usercenter_protocal"
local EM = require "ejoysdk_lua.ejoysdk_module"

local TAG = EM.MODULE.USER_CENTER .. 'usercenter_api'

local M = {}

M.ENV = {
    DEBUG = 'debug',
    RELEASE = 'release'
}
-- 心跳和更新token这两个业务是国内的，APP更新是国内海外都有
M.URL_BASE_HEARTBEAT = {
    RELEASE = 'https://msg.flysdk.cn/ejoyclient/',
    DEBUG = 'http://dssdk-msg.alibaba.net/ejoyclient/',
}

M.URL_BASE_EXCHANGE_TOKEN = {
    RELEASE = 'https://account.flysdk.cn/ejoyclient/',
    DEBUG = 'http://dsaccount.game.alibaba.net/ejoyclient/',
}

--


local l_env

-- 环境
function M.set_env(env)
    E.LOG.debug(TAG, "set_env: " .. tostring(env))
    l_env = env
end

local function get_env()
    if l_env then
        return l_env
    end

    local EI = require "ejoysdk_lua.ejoysdk_init"
    return EI.env()
end

-- desc: 获取客户端业务配置参数接口
-- api: system.config.check
-- doc: https://yuque.antfin-inc.com/ejoy-platform/ejoy-platform/qs19z6
-- params:
-- @param configCheckTime: long, 配置检查时间
-- return:
-- configCheckTime: long, 配置检查时间
-- clientConfig: json, key-value配置项
function M.usercenter_system_config_check(config_check_time, cb)
    E.LOG.debug(TAG, 'usercenter_system_config_check begin')
    local params = {}
    params.configCheckTime = config_check_time
    --E.log(params)

    UP.post(UP.SERVICE.CONFIG_CHECK, params, function(succ, ...)
        if succ then
            local data = ...
            cb(true, data)
        else
            local code, msg = ...
            cb(false, code, msg)
        end
    end)
end

-- desc: 账号中心登录
-- api: account.thirdParty.login
-- doc: https://yuque.antfin-inc.com/ejoy-platform/ejoy-platform/ndwxug
-- params:
-- @param third_party_type: string, 账号类型(google,apple,facebook,qookka,guest,mock)
-- @param third_party_token: string, 第三方账号授权登录成功后返回的用于服务器获取信息的令牌。当thirdPartyType=guest时， thirdPartyToken={agstToken}
-- @param agst_token: string, agstToken
-- @param is_create: thirdPartyType等于facebook/google/apple/qookka时有效, true:  创建新账号
-- @param migrateToken: 用于转移外部账号
-- @param risk 风险数据
-- return:
-- token: string, 登录会话ID
-- tokenTimeout: int, 返回的token过期的时间(单位:秒)
function M.usercenter_login(third_party_type, third_party_token, agst_token, migrate_token, is_create, risk, cb)
    E.LOG.debug(TAG, 'usercenter_login begin')
    local params = {}
    params.thirdPartyType = third_party_type
    params.thirdPartyToken = third_party_token
    params.agstToken = agst_token
    params.isCreate = is_create
    params.risk = risk

    if migrate_token and '' ~= migrate_token then
        -- BBGame 迁移特有字段
        params.migrateToken = migrate_token
    end

    --E.log(params)

    UP.post(UP.SERVICE.LOGIN, params, function(succ, ...)
        if succ then
            local data = ...
            cb(true, data)
        else
            local code, msg, data = ...
            cb(false, code, msg, data)
        end
    end)
end

-- desc: 查询绑定账号列表接口
-- api: account.thirdParty.list
-- doc: https://yuque.antfin-inc.com/ejoy-platform/ejoy-platform/hr8n3x
-- params:
-- @param token: string, 登录会话
-- return:
-- bindList: array, item: object, thirdPartyType: string, 当前登录的账号类型（google，apple，facebook），thirdPartyUid：string, 绑定第三方账号
function M.usercenter_bind_list(token, cb)
    E.LOG.debug(TAG, 'usercenter_bind_list begin')
    local params = {}
    params.token = token
    --E.log(params)

    UP.post(UP.SERVICE.BIND_LIST, params, function(succ, ...)
        if succ then
            local data = ...
            cb(true, data)
        else
            local code, msg = ...
            cb(false, code, msg)
        end
    end)
end

-- desc: 账号绑定接口
-- api: account.thirdParty.bind
-- doc: https://yuque.antfin-inc.com/ejoy-platform/ejoy-platform/ymdcdv
-- params:
-- @param token : string, 账号中心token, 1、token为空时,  未进行登录; 2、token非空时，即在游戏内绑定，填当前登录会话token。
-- @param agst_token: string, 游客token
-- @param third_party_type: string, 账号平台类型。可选值：google,apple,facebook,qookka,guest。当thirdPartyType=guest时， thirdPartyToken={agstToken}。当thirdPartyType=mock时， 为模拟第三方。 thirdPartyToken='successToken'时， 模拟第三方校验成功。
-- @param third_party_token: 账号平台登录令牌, 第三方账号授权登录成功后返回的用于服务器获取信息的令牌。如果Apple账号，为account.appleGameCenterAuthLogin接口的data结构中的参数组成JSON字符串并Base64编码
-- return:
-- 成功：object, token：string, 登录会话ID; tokenTimeout: int, 返回的token过期的时间(单位:秒)
function M.usercenter_bind(token, agst_token, third_party_type, third_party_token, cb)
    E.LOG.debug(TAG, 'usercenter_bind begin')
    local params = {}
    params.token = token
    params.agstToken = agst_token
    params.thirdPartyType = third_party_type
    params.thirdPartyToken = third_party_token
    --E.log(params)

    UP.post(UP.SERVICE.BIND, params, function(succ, ...)
        if succ then
            local data = ...
            cb(true, data)
        else
            local code, msg = ...
            cb(false, code, msg)
        end
    end)
end


-- 检查是否需要更新版本
function M.usercenter_check_version_update(params, cb)
    UP.post(UP.SERVICE.VERSION_UPDATE_CHECK, params, function(succ, ...)
        if cb then
            cb(succ, ...)
        end
    end)

end

function M.user_center_heartbeat(params, cb)
    -- 因为只有国内Windows端使用（及Andriod模拟器扫码包），所以直接在此处拼接URL即可，避免影响别的业务
    local V = require "ejoysdk_lua.version"

    local api = UP.SERVICE.HEART_BEAT

    local domain = M.URL_BASE_HEARTBEAT.RELEASE
    local _env = get_env()
    if _env == M.ENV.DEBUG then
        domain = M.URL_BASE_HEARTBEAT.DEBUG
    end

    local url =  domain .. api .. '?ver=1.0&df=json&gt=ng&cver='..V.LUA_VERSION..'&os='..E.Sysinfo.os()


    -- 这个接口传入api其实没啥用了
    UP.post_to(url, api, params, function(succ, ...)
        if cb then
            cb(succ, ...)
        end
    end)

end

function M.user_center_replace_ptoken(params, cb)
    -- 因为只有国内Windows端使用，所以直接在此处拼接URL即可，避免影响别的业务
    local V = require "ejoysdk_lua.version"

    local api = UP.SERVICE.TOKEN_EXCHANGE

    local domain = M.URL_BASE_EXCHANGE_TOKEN.RELEASE
    local _env = get_env()
    if _env == M.ENV.DEBUG then
        domain = M.URL_BASE_EXCHANGE_TOKEN.DEBUG
    end


    local url =  domain .. api .. '?ver=1.0&df=json&gt=ng&cver='..V.LUA_VERSION..'&os='..E.Sysinfo.os()

    -- 这个接口传入api其实没啥用了
    UP.post_to(url, api, params, function(succ, ...)
        if cb then
            cb(succ, ...)
        end
    end)
end

function M.get_user_ip_info(cb)
    UP.post(UP.SERVICE.GET_USER_IP_INFO, {}, cb or function() end)
end

-- 云微端轮询接口，查询试玩的剩余时间
function M.get_remain_time(token, scene,  cb)
    E.LOG.debug(TAG, 'get try game remain time...')
    local params = {}
    params.token = token
    params.scene = scene
    --E.log(params)
    UP.post(UP.SERVICE.CLOUD_CHECK, params, function(succ, ...)
        if cb then
            cb(succ, ...)
        end
    end
    )
end

-- 以下为边缘服务
-- 获取预约状态
function M.get_pre_order_status(platform, items,cb)
    local params = {
        bundleId =  E.Sysinfo.package_name(),
        bizAppId = E.get_game_id(),
        reserveIds = items,
        platform = platform
    }

    UP.post(UP.SERVICE.RESERVER_CHECK,params,function(succ,...)
        if cb then
            cb(succ,...)
        end
    end)
end

return M
